if(/^u/.test(typeof define)){var def={};this.define=function(f,n){def[f]=n()};this.require=function(f){return def[f]}}
define("minifiedUtil",function(){function f(c){return c.substr(0,3)}function n(c){return null!=c?""+c:""}function h(c){return"string"==typeof c}function j(c){return"function"==typeof c}function k(c){return!!c&&"object"==typeof c}function s(c){return"number"==typeof c}function u(c){return k(c)&&!!c.getDay}function e(c){return!0===c||!1===c}function x(c){var S=typeof c;return"object"==S?!(!c||!c.getDay):"string"==S||"number"==S||e(c)}function t(c){return!!c&&null!=c.length&&!h(c)&&!(c&&c.nodeType)&&
!j(c)}function m(c){return c}function E(c){return c+1}function v(c,S,a){return n(c).replace(S,null!=a?a:"")}function T(c){return v(c,/[\\\[\]\/{}()*+?.$|^-]/g,"\\$&")}function N(c){return v(c,/^\s+|\s+$/g)}function A(c,a){for(var b in c)c.hasOwnProperty(b)&&a(b,c[b]);return c}function z(c,a){if(c)for(var b=0;b<c.length;b++)a(c[b],b);return c}function O(c,a){var b=[];z(c,function(c,d){a(c,d)&&b.push(c)});return b}function B(c,a,b){var d=[];c(a,function(c,a){t(c=b(c,a))?z(c,function(c){d.push(c)}):
null!=c&&d.push(c)});return d}function F(c,a){return B(z,c,a)}function G(c){var a=[];A(c,function(c){a.push(c)});return a}function w(c,a){var b=[];z(c,function(c,d){b.push(a(c,d))});return b}function C(c,a,b){var d=a;z(c,function(c,a){d=b(d,c,a)});return d}function H(c,a){if(t(c)){var b=P(a);return g(P(c).sub(0,b.length),b)}return null!=a&&c.substr(0,a.length)==a}function I(c,a){if(t(c)){var b=P(a);return P(c).sub(-b.length).equals(b)||!b.length}return null!=a&&c.substr(c.length-a.length)==a}function Y(c){var a=
c.length;return w(c,function(){return c[--a]})}function K(c,a,b){if(!t(c))return[];var d=c.length,g=0>a?d+a:a,p=null==b?d:0<=b?b:d+b;return O(c,function(c,a){return a>=g&&a<p})}function U(c,a){var b={};z(c,function(c){b[c]=a});return b}function a(c,a,b){A(c,function(c,d){if(null==a[c]||!b)a[c]=d});return a}function b(c,a){for(var b=j(a)?a:function(c,b){if(a===c)return b},d,g=0;g<c.length;g++)if(null!=(d=b(c[g],g)))return d}function d(c,a){if(t(c))for(var b=0;b<c.length;b++)if(c[b]==a)return!0;return!1}
function g(c,a){if(c==a)return!0;if(null==c||null==a)return!1;if(x(c)||x(a))return u(c)&&u(a)&&c.getTime()==a.getTime();if(t(c))return t(a)?c.length!=a.length?!1:!b(c,function(c,b){if(!g(c,a[b]))return!0}):!1;if(t(a))return!1;var d=G(c),p=d.length,e=0;A(a,function(){e++});return p!=e?!1:!b(d,function(b){if(!g(c[b],a[b]))return!0})}function p(c,a,b){return c.apply(b&&a,w(b||a,m))}function y(c,a,b){return w(c,function(c){return j(c)?p(c,a,b):V})}function W(c,a,b,d){return function(){return p(c,a,F([b,
arguments,d],m))}}function D(c,a,b,d){setTimeout(function(){p(a,b,d)},c)}function ca(c,a,b){/^u/.test(typeof process)||!process.nextTick?setTimeout(function(){p(c,a,b)},delayMs):process.nextTick(function(){p(c,a,b)})}function Z(c,a){return da(a,0,0,0,c)}function da(c,a,b,d,g,p,e){function t(c){var a=c.length;return a>e?t(c.substr(0,a-e))+(p||",")+c.substr(a-e):c}var j=0>c,f=/(\d+)(\.(.*))?/.exec((j?-c:c).toFixed(a));c=f[1];for(d=(d||".")+f[3];c.length<(g||1);)c="0"+c;e&&(c=t(c));return(j?"-":"")+
c+(a?b?v(d,/[.,]?0+$/):d:"")}function X(c,a,b){return null==a||!c?0:60*parseInt(c[a])+parseInt(c[a+1])+b.getTimezoneOffset()}function aa(c,a){c=v(c,/^\?/);if(u(a)){var d,g,p=c,e=a,j={y:["FullYear",m],M:["Month",E],n:["Month",ia],N:["Month",ea],d:["Date",m],m:["Minutes",m],H:["Hours",m],h:["Hours",function(c){return c%12||12}],K:["Hours",E],k:["Hours",function(c){return c%12+1}],s:["Seconds",m],S:["Milliseconds",m],a:["Hours",function(c,a){return(a||ja)[12>c?0:1]}],w:["Day",pa],W:["Day",ka],z:["TimezoneOffset",
function(c){if(d)return d;var a=0<c?c:-c;return(0>c?"+":"-")+Z(2,Math.floor(a/60))+Z(2,a%60)}]};if(g=/^\[(([+-]\d\d)(\d\d))\]\s*(.*)/.exec(c))d=g[1],e=ba(a,"minutes",X(g,2,a)),p=g[4];return v(p,/(y+|M+|n+|N+|d+|m+|H+|h+|K+|k+|s+|S+|a+|w+|W+|z+)(?:\[([^\]]+)\])?/g,function(c,a,b){c=a.length;a=j[a.charAt(0)];var d=e["get"+(t(a)?a[0]:a)].call(e);b=b&&b.split(",");d=t(a[1])?(b||a[1])[d]:a[1](d,b);null!=d&&!h(d)&&(d=Z(c,d));return d})}return b(c.split(/\s*\|\s*/),function(c){var b,d;if(b=/^([<>]?)(=?)([^:]*?)\s*:\s*(.*)$/.exec(c)){c=
a;var g=parseFloat(b[3]);if(isNaN(g)||!s(c))c=null==c?"null":n(c),g=b[3];if(b[1]){if(!b[2]&&c==g||"<"==b[1]&&c>g||">"==b[1]&&c<g)return null}else if(c!=g)return null;c=b[4]}if(s(a)&&(b=/(?:(0[0.,]*)|(#[#.,]*))(_*)(9*)/.exec(c))){d=n(b[1])+n(b[2]);var g=n(b[1]).length?v(d,/[.,]/g).length:1,p=v(v(d,/^.*[0#]/),/[^,.]/g),e=n(b[3]).length+n(b[4]).length,t,j;if(d=/([.,])[^.,]+[.,]/.exec(b[0]))t=d[1],j=d[0].length-2;t=da(a,e,n(b[3]).length,p,g,t,j);j=c;c=b.index;b=n(b[0]).length;return j.substr(0,c)+t+j.substr(c+
b)}return c})}function la(c,a){if(1==arguments.length)return la(null,c);if(/^\?/.test(c)){if(""==N(a))return null;c=c.substr(1)}var b,d=(b=/[0#]([.,])[_9]/.exec(c))?b[1]:(b=/^[.,]$/.exec(c))?b[0]:".";b=parseFloat(v(v(v(a,","==d?/\./g:/,/g),d,"."),/^[^\d-]*(-?\d)/,"$1"));return isNaN(b)?V:b}function ma(c){return new Date(c.getTime())}function fa(c,a,b){c["set"+a].call(c,c["get"+a].call(c)+b);return c}function ba(c,a,b){return 3>arguments.length?ba(new Date,c,a):fa(ma(c),a.charAt(0).toUpperCase()+a.substr(1),
b)}function na(c,a,b){var d=a.getTime(),g=b.getTime(),p=g-d;if(0>p)return-na(c,b,a);if(a={milliseconds:1,seconds:1E3,minutes:6E4,hours:36E5}[c])return p/a;a=c.charAt(0).toUpperCase()+c.substr(1);c=Math.floor(p/{fullYear:31536E6,month:2628E6,date:864E5}[c]-2);d=fa(new Date(d),a,c);for(p=c;p<1.2*c+4;p++)if(fa(d,a,1).getTime()>g)return p}function ga(c,a,b){var d=/^((?:[^.]|\.\.)+)\.([^.].*)/.exec(a);if(d){a=v(d[1],/\.\./g,".");var g=c[a];return ga(j(g)?g():g,d[2],b)}a=v(a,/\.\./g,".");g=c[a];return b===
V?j(g)?g():g:j(g)?g(b):c[a]=b}function ha(){function c(c,d){null==a&&(a=c,f=t(d)?d:[d],ca(function(){z(b,function(a){a()})}))}var a,b=[],d=arguments,g=d.length,e=0,f=[];z(d,function oa(a,b){try{a.then(function(a){a&&j(a.then)?oa(a.then,b):(f[b]=w(arguments,m),++e==g&&c(!0,2>g?f[b]:f))},function(a){f[b]=w(arguments,m);c(!1,2>g?f[b]:[f[b][0],f,b])})}catch(d){c(!1,[d,f,b])}});c.then=function(c,d){var g=ha(),e=function(){try{var b=a?c:d;if(j(b)){var e=p(b,f);e&&j(e.then)?e.then(function(a){g(!0,[a])},
function(a){g(!1,[a])}):g(!0,[e])}else g(a,f)}catch(t){g(!1,[t])}};null!=a?ca(e):b.push(e);return g};c.always=function(a){return then(a,a)};c.error=function(a){return then(0,a)};return c}function Q(a,b){for(var d=0,g=0;g<a.length;g++){var p=a[g];if(b&&t(p))for(var e=0;e<p.length;e++)this[d++]=p[e];else this[d++]=p}this.length=d;this._=!0}function P(){return new Q(arguments,!0)}function R(a){return function(b,d){return new Q(a(this,b,d))}}function L(a){return function(b,d){return a(this,b,d)}}function M(a){return function(b,
d,g){return new Q(a(b,d,g))}}var V,ea="January February March April May June July August September October November December".split(" "),ia=w(ea,f),ka="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),pa=w(ka,f),ja=["am","pm"];a({each:L(z),filter:R(O),collect:R(F),map:R(w),reduce:L(C),toObject:L(U),equals:L(g),sub:R(K),reverse:R(Y),find:L(b),startsWith:L(H),endsWith:L(I),contains:L(d),call:R(y),array:function(){return w(this,m)},func:function(){var a=this;return function(){return new Q(y(a,
arguments))}},join:function(a){return w(this,m).join(a)},sort:function(a){return new Q(w(this,m).sort(a))},uniq:function(){var a={};return this.filter(function(b){if(a[b])return!1;a[b]=1;return!0})},intersection:function(a){var b=U(a,1);return this.filter(function(a){var c=b[a];b[a]=0;return c})},tap:function(a){a(this);return this},toString:function(){return"["+this.map(function(a){return h(a)?"'"+v(a,/'/g,"\\'")+"'":a}).join(", ")+"]"}},Q.prototype);a({bind:W,partial:function(a,b,d){return W(a,
null,b,d)},once:function(a){var b=0;return function(){if(!b++)return p(a,this,arguments)}},selfFunc:m,each:z,eachObj:A,toObject:U,filter:M(O),filterObj:function(a,b){var d={};A(a,function(a,c){b(a,c)&&(d[a]=c)});return d},collect:M(F),collectObj:M(function(a,b){return B(A,a,b)}),map:M(w),mapObj:function(a,b){var d={};A(a,function(a,c){d[a]=b(a,c)});return d},reduce:C,find:b,contains:d,sub:M(K),reverse:M(Y),startsWith:H,endsWith:I,equals:g,toString:n,isList:t,isFunction:j,isObject:k,isNumber:s,isBool:e,
isDate:u,isValue:x,isString:h,toString:n,prop:ga,escapeRegExp:T,trim:N,defer:ca,delay:D,dateClone:ma,dateAdd:ba,dateDiff:na,dateMidnight:function(a){a=a||new Date;return new Date(a.getFullYear(),a.getMonth(),a.getDate())},formatNumber:da,pad:Z,formatValue:aa,parseDate:function(a,d){var g={y:0,M:[1,1],n:[1,ia],N:[1,ea],d:2,m:4,H:3,h:3,K:[3,1],k:[3,1],s:5,S:6,a:[3,ja]},p={},e=1,f,j,k;if(/^\?/.test(a)){if(""==N(d))return null;a=a.substr(1)}if(k=/^\[([+-]\d\d)(\d\d)\]\s*(.*)/.exec(a))f=k,a=k[3];if(!(k=
RegExp(a.replace(/(m+|y+|d+|h+|k+|s+|z+|\s+|n+|a+|w+)(?:\[([^\]]*)\])?/ig,function(a,b,c){a=b.charAt(0);return/[dmhkyhs]/i.test(a)?(p[e++]=a,b=b.length,"(\\d"+(2>b?"+":"{1,"+b+"}")+")"):"z"==a?(j=e,e+=2,"([+-]\\d\\d)(\\d\\d)"):/[Nna]/.test(a)?(p[e++]=[a,c&&c.split(",")],"(\\w+)"):/w/i.test(a)?"\\w+":/\s/.test(a)?"\\s+":T(b)})).exec(d)))return V;for(var y=[0,0,0,0,0,0,0],n=1;n<e;n++){var x=k[n],m=p[n];if(t(m)){var h=m[0],D=g[h],s=D[0],m=b(m[1]||D[1],function(a,b){return H(x.toLowerCase(),a.toLowerCase())?
b:null});if(null==m)return V;y[s]="a"==h?y[s]+12*m:m}else m&&(h=parseInt(x),D=g[m],t(D)?y[D[0]]+=h-D[1]:y[D]+=h)}g=new Date(y[0],y[1],y[2],y[3],y[4],y[5],y[6]);return ba(g,"minutes",-X(f,1,g)-X(k,j,g))},parseNumber:la,keys:M(G),values:M(function(a){var b=[];A(a,function(a,c){b.push(c)});return b}),copyObj:a,coal:function(){return b(arguments,m)},promise:ha,format:function(a,b){return v(a,/{([^,}]*)(,([^}]*))?}/g,function(a,c,d,g){a=""==c?b:ga(b,c);return d?aa(g,a):n(a)})},wait:function(a){var b=ha();
D(function(){b(!0,[a])},a);return b}},P);return{_:P}});var l=!0,q=null,r=!1;if(/^u/.test(typeof define)){var J={};this.define=function(f,n){J[f]=n()};this.require=function(f){return J[f]}}
define("minified",function(){function f(a){return a!=q?""+a:""}function n(a){return"string"==typeof a}function h(a){return"function"==typeof a&&!a.item}function j(a){return a&&a.length!=q&&!n(a)&&!(a&&a.nodeType)&&!h(a)}function k(a,b){for(var d in a)a.hasOwnProperty(d)&&b(d,a[d]);return a}function s(a,b){for(var d=0;a&&d<a.length;d++)b(a[d],d);return a}function u(a,b){var d=[];s(a,function(a,p){b(a,p)&&d.push(a)});return d}function e(a,b){var d=[];s(a,function(a,p){j(a=b(a,p))?s(a,function(a){d.push(a)}):
a!=q&&d.push(a)});return d}function x(a,b){var d=[];k(a,function(a,p){j(a=b(a,p))?s(a,function(a){d.push(a)}):a!=q&&d.push(a)});return d}function t(a,b,d){return f(a).replace(b,d||"")}function m(a){return parseFloat(t(a,/^[^\d-]+/))}function E(a){var b={$position:"absolute",$visibility:"hidden",$display:"block",$height:q},d=a.get(b);a.set(b);b=a[0].offsetHeight;a.set(d);return b}function v(a){a()}function T(){s(H,v);H=q}function N(a){H?H.push(a):w.setTimeout(a,0)}function A(a,b,d,g){return function(){var p=
B(C.createElement(a));j(b)||"object"!=typeof b?p.add(b):p.set(b).add(d);g&&g(p);return p}}function z(){function a(a,p){b==q&&(b=a,d=p,w.setTimeout(function(){s(g,v)},0))}var b,d=[],g=[],p=a.then=function(a,p){function e(){try{var g=b?a:p;if(h(g)){var j=g.apply(q,d);j&&h(j.then)?j.then(function(a){f(l,[a])},function(a){f(r,[a])}):f(l,[j])}else f(b,d)}catch(t){f(r,[t])}}var f=z();b!=q?w.setTimeout(e,0):g.push(e);return f};a.always=function(a){return p(a,a)};a.error=function(a){return p(0,a)};return a}
function O(a){return U[a]||"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}function B(a,b,d){return h(a)?N(a):new G(F(a,b,d))}function F(a,b,d){function g(a){a=function X(a){return j(a)?e(a,X):a}(a);return p?u(a,function(a){for(;a=a.parentNode;){if(a===p)return l;if(d)return r}}):a}var p,f,k,m,h;if(b&&1!=(b=F(b)).length)return e(b,function(b){return F(a,b,d)});p=b&&b[0];if(!n(a))return g(j(a)?a:[a]);if(1<(b=a.split(/\s*,\s*/)).length)return e(b,function(a){return F(a,p,d)});if(b=/(\S+)\s+(.+)$/.exec(a))return F(b[2],
F(b[1],p),d);if(a!=(b=t(a,/^#/)))return g([C.getElementById(b)]);p=p||C;f=(b=/([^.]*)\.?([^.]*)/.exec(a))[1];m=b[2];b=(k=p.getElementsByClassName&&m)?p.getElementsByClassName(m):p.getElementsByTagName(f||"*");if(f=k?f:m)h=RegExp("\\b"+f+"\\b","i"),b=u(b,function(a){return h.test(a[k?"nodeName":"className"])});return p?g(b):b}function G(a){for(var b=this.length=a.length,d=0;d<b;d++)this[d]=a[d]}var w=this,C=document,H=[],I=[],Y=e(["msR","webkitR","mozR","r"],function(a){return w[a+"equestAnimationFrame"]})[0]||
function(a){w.setTimeout(a,33)},K=!!C.all&&!H.map,U={"\t":"\\t","\r":"\\r","\n":"\\n",'"':'\\"',"\\":"\\\\"};k({each:function(a){return s(this,a)},filter:function(a){return new G(u(this,a))},collect:function(a){return new G(e(this,a))},sub:function(a,b){var d=0>a?this.length+a:a,g=0<=b?b:this.length+(b||0);return new G(u(this,function(a,b){return b>=d&&b<g}))},find:function(a){for(var b,d=h(a)?a:function(b,d){if(a===b)return d},g=0;g<this.length;g++)if((b=d(this[g],g))!=q)return b},hasClass:function(a){var b=
RegExp("\\b"+a+"\\b");return this.find(function(a){return b.test(a.className)?a:q})},remove:function(){s(this,function(a){a.parentNode.removeChild(a)})},get:function(a,b){var d=this,g=d[0];if(g){if(n(a)){var p=t(a,/^[$@]/),e;e="$"==a?g.className:"$$"==a?K?g.style.cssText:g.getAttribute("style"):/\$\$/.test(a)&&("hidden"==g.style.visibility||"none"==g.style.display)?0:"$$fade"==a?isNaN(e=K?m(g.style.filter)/100:m(g.style.opacity))?1:e:"$$slide"==a?g.offsetHeight+"px":/^\$/.test(a)?w.getComputedStyle?
w.getComputedStyle(g,q).getPropertyValue(t(p,/[A-Z]/g,function(a){return"-"+a.toLowerCase()})):(g.currentStyle||g.style)[p]:/^@/.test(a)?g.getAttribute(p):g[p];return b?m(e):e}var f={};(j(a)?s:k)(a,function(a){f[a]=d.get(a,b)});return f}},set:function(a,b){var d=this,g;void 0!==b?"$$fade"==a||"$$slide"==a?d.set({$visibility:0<(g=m(b))?"visible":"hidden",$display:"block"}).set("$$fade"==a?K?{$filter:"alpha(opacity = "+100*g+")",$zoom:1}:{$opacity:g}:{$height:/px$/.test(b)?b:function(a,b,d){return g*
(g&&E(B(d)))+"px"},$overflow:"hidden"}):s(d,function(d,g){var e=t(a,/^[@$]/),f=d.className||"",j=/^\$/.test(a)?d.style:d,m=h(b)?b(B(d).get(a),g,d):b;"$"==a?m!=q&&(s(m.split(/\s+/),function(a){var b=t(a,/^[+-]/),d=f;f=t(f,RegExp("\\b"+b+"\\b"));if(/^\+/.test(a)||b==a&&d==f)f+=" "+b}),d.className=t(f,/^\s+|\s+(?=\s|$)/g)):"$$"==a?K?j.cssText=m:m!=q?d.setAttribute("style",m):d.removeAttribute("style"):/^@/.test(a)?m!=q?j.setAttribute(e,m):j.removeAttribute(e):j[e]=m}):n(a)||h(a)?d.set("$",a):k(a,function(a,
b){d.set(a,b)});return d},add:function(a,b){return s(this,function(d,g){var e;(function W(a){j(a)?s(a,W):h(a)?W(a(d,g)):a!=q&&(a=a&&a.nodeType?a:C.createTextNode(a),e?e.parentNode.insertBefore(a,e.nextSibling):b?b(a,d,d.parentNode):d.appendChild(a),e=a)})(a&&a.nodeType&&g?q:a)})},fill:function(a){return s(this,function(a){B(a.childNodes).remove()}).add(a)},addBefore:function(a){return this.add(a,function(a,d,g){g.insertBefore(a,d)})},addAfter:function(a){return this.add(a,function(a,d,g){g.insertBefore(a,
d.nextSibling)})},addFront:function(a){return this.add(a,function(a,d){d.insertBefore(a,d.firstChild)})},replace:function(a){return this.add(a,function(a,d,g){g.replaceChild(a,d)})},clone:function(a){return new G(e(this,function(b){var d=b&&b.nodeType;if(1==d){var g={$:b.className||q,$$:K?b.style.cssText:b.getAttribute("style")};s(b.attributes,function(a){var d=a.name;"id"!=d&&"style"!=d&&"class"!=d&&b.getAttribute(d)&&(g["@"+d]=a.value)});return A(b.tagName,g,B(b.childNodes).clone(),a)}return 5>
d?b.data:q}))},animate:function(a,b,d,g){var e=this,j=[],n=/-?[\d.]+/,x,u=z(),v=h(d)?d:function(a,b,g){return a+g*(b-a)*(d+(1-d)*g*(3-2*g))};g=g||{};g.time=0;g.stop=function(){x();u(r)};b=b||500;d=d||0;s(e,function(b){var d={a:B(b),c:{}};k(d.b=d.a.get(a),function(b,g){var e=a[b];"$$slide"==b&&(e=e*E(d.a)+"px");d.c[b]=/^[+-]=/.test(e)?t(e.substr(2),n,m(g)+m(t(e,/\+?=/))):e});j.push(d)});x=B.loop(function(a){function d(a,b){return/^#/.test(a)?parseInt(6<a.length?a.substr(1+2*b,2):(a=a.charAt(1+b))+
a,16):parseInt(t(a,/[^\d,]+/g).split(",")[b])}g.time=a;a>=b||0>a?(s(j,function(a){a.a.set(a.c)}),x(),g.time=q,u(l,[e])):s(j,function(g){k(g.b,function(e,j){var p="rgb(",k=g.c[e],x=a/b;if(/^#|rgb\(/.test(k))for(var h=0;3>h;h++)p+=Math.round(v(d(j,h),d(k,h),x))+(2>h?",":")");else p=t(k,n,f(v(m(j),m(k),x)));g.a.set(e,p)})})});return u},toggle:function(a,b,d,g){var e=this,f={},j=r,m=/\b(?=\w)/g;return!b?e.toggle(t(a,m,"-"),t(a,m,"+")):e.set(a)&&function(m){m!==j&&(j=m===l||m===r?m:!j,d?e.animate(j?b:
a,f.stop?f.stop()||f.time:d,g,f):e.set(j?b:a))}},on:function(a,b,d,g){return s(this,function(e,f){s(a.split(/\s/),function(a){function j(e){e=e||w.event;if((!b.apply(g?d:e.target,g||d||[e,f])||g)&&a==m)e.stopPropagation&&(e.preventDefault(),e.stopPropagation()),e.returnValue=r,e.cancelBubble=l}var m=t(a,/\|/);(b.M=b.M||[]).push({e:e,h:j,n:m});e.addEventListener?e.addEventListener(m,j,l):e.attachEvent("on"+m,j)})})}},function(a,b){G.prototype[a]=b});k({request:function(a,b,d,g,m,t){var h,s=d,u=0,v=
z();try{return h=w.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Msxml2.XMLHTTP.3.0"),d!=q&&(g=g||{},!n(d)&&!(d&&d.nodeType)&&(s=x(d,function aa(a,b){return j(b)?e(b,function(b){return aa(a,b)}):encodeURIComponent(a)+(b!=q?"="+encodeURIComponent(b):"")}).join("&")),/post/i.test(a)?!(d&&d.nodeType)&&!n(d)&&!g["Content-Type"]&&(g["Content-Type"]="application/x-www-form-urlencoded"):(b+="?"+s,s=q)),h.open(a,b,l,m,t),k(g,function(a,b){h.setRequestHeader(a,b)}),h.onreadystatechange=function(){4==
h.readyState&&!u++&&(200==h.status?v(l,[h.responseText,h.responseXML]):v(r,[h.status,h.statusText,h.responseText]))},h.send(s),v}catch(A){u||v(r,[0,q,f(A)])}},toJSON:function b(d){return d==q?""+d:n(d=d.valueOf())?'"'+t(d,/[\\\"\x00-\x1f\x22\x5c]/g,O)+'"':j(d)?"["+e(d,b).join()+"]":"object"==typeof d?"{"+x(d,function(d,e){return b(d)+":"+b(e)}).join()+"}":f(d)},parseJSON:w.JSON?w.JSON.parse:function(b){b=t(b,/[\x00\xad\u0600-\uffff]/g,O);if(/^[[\],:{}\s]*$/.test(t(t(b,/\\["\\\/bfnrtu]/g),/"[^"\\\n\r]*"|true|false|null|[\d.eE+-]+/g)))return eval("("+
b+")")},ready:N,setCookie:function(b,d,g,e,f,j){C.cookie=b+"="+(j?d:escape(d))+(g?"; expires="+("object"==typeof g?g:new Date((new Date).getTime()+864E5*g)).toUTCString():"")+"; path="+(e?escapeURI(e):"/")+(f?"; domain="+escape(f):"")},getCookie:function(b,d){var g,e=(g=RegExp("(^|;)\\s*"+b+"=([^;]*)").exec(C.cookie))&&g[2];return d?e:e&&unescape(e)},loop:function(b){var d={d:b,f:(new Date).getTime(),b:function(){for(var b=0;b<I.length;b++)I[b]===d&&I.splice(b--,1)}};2>I.push(d)&&function p(){s(I,
function(b){b.d(Math.max(0,(new Date).getTime()-b.f),b.b)}).length&&Y(p)}();return d.b},off:function(b){s(b.M,function(b){b.e.removeEventListener?b.e.removeEventListener(b.n,b.h,l):b.e.detachEvent("on"+b.n,b.h)});b.M=q}},function(b,d){B[b]=d});w.onload=T;C.addEventListener&&C.addEventListener("DOMContentLoaded",T,r);return{$:B,$$:function(b){return F(b)[0]},EE:A}});var _=require("minifiedUtil")._;
function parseSourceSections(f){function n(){return{id:"anon"+h++,src:[],desc:"",requires:{},requiredBy:{},syntax:[],example:[],params:[]}}f=f.split("\n");var h=100,j=[],k=n(),s=!1;_.each(f,function(f){if(s&&/^.*\*\/\s*$/.test(f))s=!1;else if(s){var e=f.replace(/^\s*(\*\s?)?/,"").replace(/\s*$/,""),h=e.match(/^\s*@([a-z]+)/);h?(h=h[1],e=_.trim(e.replace(/^\s*@[a-z]+\s*/,"")),"syntax"==h||"example"==h?k[h].push(e):"requires"==h?e.length&&_.each(e.split(/\s+/),function(e){k.requires[e]=1}):"param"==
h?k.params.push({name:e.replace(/\s.*$/,""),desc:e.replace(/^\S+\s+/,"")}):"return"==h?k.params.push({name:"@return",desc:e}):"function"==h?k.params[k.params.length-1].funcs.push(e):k[h]=""!=e?e:1):k.params.length?k.params[k.params.length-1].desc+="\n"+_.trim(e):k.example.length?k.example[k.example.length-1]+="\n"+e:k.desc+=e+"\n"}else/^\s*\/\*\$/.test(f)&&!/\*\/\s*$/.test(f)&&(s=!0,j.push(k),k=n());k.src.push(f)});j.push(k);return j}
function createSectionMap(f){var n={};_.each(f,function(f){n[f.id]=f});return n}function completeRequirements(f,n){var h=0;_.each(f,function(f){_.eachObj(f.requires,function(k){var s=n[k];if(!s)throw Error('Unknown id in requirement: "'+k+'"');_.eachObj(s.requires,function(k){f.requires[k]||(h++,f.requires[k]=1)})})});0<h?completeRequirements(f,n):_.each(f,function(f){_.eachObj(f.requires,function(h){n[h].requiredBy[f.id]=1})})}
function calculateDependencies(f,n){var h={};_.eachObj(n,function(j){n[j]&&(h[j]=1,_.eachObj(f[j].requires,function(f){h[f]=1}))});return h}function createDefaultConfigurationMap(f,n){var h={};_.each(f,function(f){if(f.configurable&&("default"==f.configurable||n))h[f.id]=1});return h}
function compile(f,n,h){var j="",k=calculateDependencies(n,h),s=[],u=!0;_.filter(f,function(e){return k[e.id]||!(e.configurable||e.dependency)}).each(function(e){_.each(e.src,function(e){if(/^\s*$/.test(e))u||(j+="\n"),u=!0;else{var f=e.match(/^(\s*)\/\/\s*@(cond|condblock)\s+(\!?)(\w*)\s*(.*)$/);if(f&&"cond"==f[2]&&!!k[f[4]]!=("!"==f[3]))j+=f[1]+f[5]+"\n";else if(f&&"condblock"==f[2])s.unshift(!!k[f[4]]!=("!"==f[3]));else if(s.length&&/^\s*\/\/\s*@condend(\s|$)/.test(e))s.shift();else if(0==s.length||
s[0])j+=e+"\n";u=!1}})});return j}function prepareSections(f){f=parseSourceSections(f);var n=createSectionMap(f);completeRequirements(f,n);var h=createDefaultConfigurationMap(f);return{sections:f,sectionMap:n,enabledSections:h}}var CONFIG_START="minified.js config start --",CONFIG_COMMENT="// - ",CONFIG_ALL="All sections.",CONFIG_ALL_EXCEPT="All sections except ",CONFIG_ONLY="Only sections ";
function serializeEnabledSections(f,n){var h=_.filter(f,function(e){return e.configurable}),j=_.filter(_.keys(n),function(e){return n[e]}),k,s=[];j.length==h.length?(k=CONFIG_COMMENT+CONFIG_ALL,s=[]):j.length/3>h.length/2?(k=CONFIG_COMMENT+CONFIG_ALL_EXCEPT,s=_.filter(h,function(e){return!n[e.id]}).collect(function(e){return e.id})):(k=CONFIG_COMMENT+CONFIG_ONLY,s=j);var u="// "+CONFIG_START+" use this comment to re-create configuration in the Builder\n"+k,e=50;_(s).sort().each(function(f){e<f.length?
(e=70,u+="\n// - "+f+", "):(u+=f+", ",e-=f.length+2)});return u=u.replace(/,\s*$/,".\n")}function fixConfig(f,n){_.eachObj(n,function(h){f[h]?_.copyObj(f[h].requires,n):delete n[h]});return n}
function deserializeEnabledSections(f,n,h){function j(e){return RegExp("^"+e.replace(/ /g,"\\s+"))}var k=j(CONFIG_START+".*"),s=j(CONFIG_ALL.replace(/\./,"\\.")),u=j(CONFIG_ALL_EXCEPT+"\\s*"),e=j(CONFIG_ONLY+"\\s*"),x=j(CONFIG_COMMENT);h=h.split("\n");for(var t=0;t<h.length;t++){var m=h[t];if(/^\s*\/\/s*/.test(m)&&(m=m.replace(/^\s*\/\/\s*/,""),k.test(m)&&t+1<h.length)){for(var m="",E=t+1;E<h.length;E++)if(x.test(h[E])){if(m+=h[E].replace(x,""),/\s*\.\s*$/.test(h[E]))break}else break;if(s.test(m))return createDefaultConfigurationMap(f,
!0);m=m.replace(/\s*\.\s*$/,"");if(u.test(m)){var v=createDefaultConfigurationMap(f,!0);_.each(m.replace(u,"").split(/\s*,\s*/),function(e){delete v[e]});return fixConfig(n,v)}if(e.test(m))return console.log("only ",m),v={},_.each(m.replace(e,"").split(/\s*,\s*/),function(e){console.log("sec ",e);f[e]&&(v[e]=1)}),fixConfig(n,v)}}return null};var MINI=require("minified"),$=MINI.$,$$=MINI.$$,EE=MINI.EE,_=require("minifiedUtil")._,MAX_SIZE=4095,SRC="/minified-web-src.js",GROUPS="INTERNAL SELECTORS ELEMENT REQUEST JSON EVENTS COOKIE ANIMATION OPTIONS".split(" ");
function closureCompile(f,n,h){$.request("post","http://closure-compiler.appspot.com/compile",{js_code:f,output_format:"json",output_info:["compiled_code","statistics"],output_file_name:"minified-custom.js",compilation_level:n?"ADVANCED_OPTIMIZATIONS":"SIMPLE_OPTIMIZATIONS"}).then(function(f){h&&h($.parseJSON(f))},function(f,k,n){window.console&&console.log("error",f,k,n);h&&h(null)}).error(function(f){window.console&&console.log(f)})}
function setUpConfigurationUI(f){function n(){$(".modCheck").each(function(e){var f=0;$(".secCheck",e.parentNode.parentNode).each(function(e){e.checked&&f++});e.checked=0<f})}function h(e){var h=f.sectionMap[e.id.substr(4)];e.checked?_.eachObj(h.requires,function(e){$("#sec-"+e).set("checked",!0)}):_.eachObj(h.requiredBy,function(e){$("#sec-"+e).set("checked",!1)})}$("#compile").on("click",function(){var e={};$(".secCheck").each(function(f){f.checked&&(e[f.id.substr(4)]=1)});var h=compile(f.sections,
f.sectionMap,e),j=serializeEnabledSections(f.sections,e);$$("#compressionAdvanced").checked||$$("#compressionSimple").checked?($$("#compile").disabled=!0,closureCompile(h,$$("#compressionAdvanced").checked,function(e){$$("#compile").disabled=!1;$("#resultDiv").animate({$$slide:1});e?($("#gzipRow, #downloadRow").set({$display:"table-row"}),$$("#resultSrc").value=j+"\n"+e.compiledCode,$("#resultPlain").fill((e.statistics.compressedSize/1024).toFixed(2)+"kb ("+e.statistics.compressedSize+" bytes)"),
$("#resultGzippedSize").fill((e.statistics.compressedGzipSize/1024).toFixed(2)+"kb ("+e.statistics.compressedGzipSize+" bytes)"),$$("#resultLink").setAttribute("href","http://closure-compiler.appspot.com"+e.outputFilePath),$("#resultGzippedComment").set({$$fade:e.statistics.compressedGzipSize>MAX_SIZE?1:0})):alert("Google Closure Service not availble. Try again later.")})):($("#resultDiv").animate({$$slide:1}),$$("#resultSrc").value=j+h,$("#resultPlain").fill((h.length/1024).toFixed(2)+"kb"),$("#gzipRow, #downloadRow").set({$display:"none"}));
return!1});var j=$("#configSrcDiv").toggle({$$slide:0},{$$slide:1});$("#fromScratch").on("|click",j,[!1]);$("#loadConfig").on("|click",j,[!0]);$("#recreate").on("click",function(){try{var e=$$("#configSrc").value,h=deserializeEnabledSections(f.sections,f.sectionMap,e);h?(console.log("loading ",h),_.eachObj(f.sectionMap,function(e){var f=$$("#sec-"+e);f&&(f.checked=!!h[e])}),n()):alert("Can not find configuration in source.")}catch(j){console.log(j)}});for(var k=1;k<GROUPS.length;k++){var s;$("#sectionCheckboxes").add(s=
EE("div",{"@id":"divMod-"+k},EE("div",{className:"groupDescriptor"},[j=EE("input",{"@id":"mod-"+k,className:"modCheck","@type":"checkbox",checked:"checked"})(),EE("label",{"@for":"mod-"+k},GROUPS[k])]))());$(j).on("change",function(){var e=this.checked;$(".secCheck",this.parentNode.parentNode).each(function(f){f.checked=e;h(f)});n();return!0});var u;_.filter(f.sections,function(e){return e.group==GROUPS[k]&&e.configurable}).sort(function(e,f){var h=e.name||e.id,j=f.name||f.id;return h==j?0:h>j?1:
-1}).each(function(e){function j(e,h){var k=_.filter(_.keys(h),function(e){return!!h[e].name});if(!k.length)return null;var m=0,n=e;_.each(k,function(e){m++<Math.min(k.length,8)&&(1<m&&(n=m==Math.min(k.length,8)?n+" and ":n+", "),n=8==m&&8<k.length?n+"more":n+(f.sectionMap[e].name||f.sectionMap[e].id))});return n+="."}var k=j("Required by ",e.requiredBy),m=j("Requires ",e.requires);s.add(EE("div",{className:"sectionDescriptor"},[u=EE("input",{className:"secCheck","@type":"checkbox","@id":"sec-"+e.id,
checked:"default"==e.configurable?"checked":null})(),EE("label",{"@for":"sec-"+e.id},e.name||e.id),EE("div",{className:"requirements"},[k?[k,EE("br")]:null,m])]));$(u).on("change",function(){h(this);n();return!0})})}}$(function(){$.request("get",SRC,null).then(function(f){setUpConfigurationUI(prepareSections(f))}).error(function(f){window.console&&console.log(f)})});
