/*
 * Welcome to Minfied's gruntfile :)
 * 
 * Here are some tasks that may be interesting for development:
 * 
 * - all: compiles and tests everything, sets up the /WebContent dir that's used for the site
 * - code: compiles the code in /src, executes automated tests
 * - test: runs all available tests (util in Node.js, web in PhantomJS)
 * - testQuick: runs the most important tests, much faster than 'test'
 * - site: use after you changed site content in /srcContent
 * - assemble (default): just create minified.js and copy test cases into /WebDevelopment, but no (slow) closure compilation
 * - watch: watches over files, execute the tasks above automatically when files change
 * - server: starts a server on port 8080 that serves /WebContent
 * 
 */ 

module.exports = function(grunt) {
	grunt.initConfig({
		pkg: grunt.file.readJSON('package.json'),
		
		minitemplate: {
			staticPages: {
				options: {
					template: 'templates/page.template'
				},
				files: [{
			            expand: true,     
			            cwd: 'srcContent/',  
			            src: ['**/*.hson'],
			            dest: 'WebContent/',
			            ext: '.html'
			          
				}]
			},
			webTests: {
				options: {
					template: 'src/test-web/webtest.template'
				},
				files: [{
			            expand: true,     
			            cwd: 'src/test-web/',  
			            src: ['**/*.hson'],
			            dest: 'WebContent/test/',
			            ext: '.html'
			          
				}]
			}
		},
		
		writedocs: {
		    web: {
		      options: {  
		        destDir: 'srcContent/api/'
		      },
		      files: {
		    	  src: ['src/minified-web-src.js']
		      }
		    }
		},
		
		mergesrc: {
		    main: {
		      options: {
		    	  prolog: "\n\n// WARNING! This file is autogenerated from minified-shell.js and others.\n\n\n"
		      },
		      files: {
		    	  'src/minified-src.js': ['src/minified-shell.js', 'src/minified-web-src.js', 'src/minified-util-src.js']
		      }
		    }
		},
		
		rebuildsrc: {
			noie: {
				options: {
					config: "// minified.js config start -- use this comment to re-create your build configuration\n"+
					 "// - All sections except debug, ie6compatibility, ie7compatibility, ie8compatibility.\n"
				},
				files: {
					'WebContent/minified-noie-src.js': 'src/minified-src.js',
					'WebContent/minified-noie-web-src.js': 'src/minified-web-src.js'
				}
			},
			headless: {
				options: {
					config: "// minified.js config start -- use this comment to re-create your build configuration\n"+
					"// - All sections except ie6compatibility, ie7compatibility, ie8compatibility, ie9compatibility, amdfallback.\n",
					extraOptions: ['commonjs']
				},
				files: {
					'WebContent/minified-headless.js': 'src/minified-util-src.js',
				}
			}
		},
		
		htmlmin: {
		    dist: {
		      options: {  
		        removeComments: true,
		        collapseWhitespace: true
		      },
		      files: [{
		            expand: true,     
		            cwd: 'WebContent/',  
		            src: ['*.html', 'about/*.html', 'api/**/*.html', 'builder/*.html', 'docs/**/*.html', 'download/*.html'],
		            dest: 'WebContent/'		          
		      }]
		    }
		},
		
		'closurecompiler': {
			dist: {
				options: {
					compilation_level: 'ADVANCED_OPTIMIZATIONS'
				},
				files: {
					'tmp/minified-web.js':      'src/minified-web-src.js',
					'tmp/minified-noie-web.js': 'WebContent/minified-noie-web-src.js',
					'tmp/minified-util.js':     'src/minified-util-src.js',
					'tmp/minified-noie.js':     'WebContent/minified-noie-src.js',
					'tmp/minified.js':          'src/minified-src.js'
				}
			}
		},
		
		uglify: {
			dist: {
				options: {
					compress: {
						hoist_vars: true,
						unsafe: true
					},
					mangle: {
					}					
				},
				files: {
					'WebContent/minified-web.js': 'tmp/minified-web.js',
					'WebContent/minified-noie-web.js': 'tmp/minified-noie-web.js',
					'WebContent/minified-util.js': 'tmp/minified-util.js',
					'WebContent/minified-noie.js': 'tmp/minified-noie.js',
					'WebContent/minified.js': 'tmp/minified.js',
					'WebContent/minified.test.js': 'tmp/minified.js' // b/c /minified.js not usable on Eclipse web server!
					
				}
			},
			
			site: {
				options: {
					compress: {
					},
					mangle: {
					}					
				},
				files: {
					'WebContent/js/builder.js': ['src/minified-src.js', 'srcContent/js/parser-src.js', 'srcContent/js/builder-src.js'],
					'WebContent/js/homepage.js': ['srcContent/js/minified-homepage.js', 'srcContent/js/homepage-src.js']
				}
			}
		},
		
		copy: {
			sources: {
				files: {
					'WebContent/minified-web-src.js': 'src/minified-web-src.js',
					'WebContent/minified-util-src.js': 'src/minified-util-src.js',
					'WebContent/minified-src.js': 'src/minified-src.js',
					'WebContent/test/minified-util.js': 'src/minified-util-src.js',
					'WebContent/test/sparkplug.js': 'srcContent/js/sparkplug-src.js',
					'WebContent/test/mocha.js': 'node_modules/mocha/mocha.js',
					'WebContent/test/mocha.css': 'node_modules/mocha/mocha.css'
				}
			},
			pngs: {
				files: {
					'WebContent/img/': 'srcContent/img/*.png'
				}
			},
			test: {
				files: [{
		            expand: true,
		            cwd: 'srcContent/',
		            src: ['examples/*.html', 'test/**/*.js', 'test/**/*.html', 'test/**/*.txt'],
		            dest: 'WebContent/'
		      }]
			},
			testCases: {
				files: [{
		            expand: true,
		            cwd: 'src/test-web',  
		            src: ['*.js'],
		            dest: 'WebContent/test/'
		      }]
			}

		},
		
		cssmin: {
			site: {
				files: {
					'WebContent/css/minimum.css': 'srcContent/css/minimum.css',
					'WebContent/css/doc.css': ['srcContent/css/minimum.css', 'srcContent/css/doc.css'],
					'WebContent/css/links.css': ['srcContent/css/minimum.css', 'srcContent/css/links.css'],
					'WebContent/css/homepage.css': ['srcContent/css/minimum.css', 'srcContent/css/homepage.css'],
					'WebContent/css/reference.css': ['srcContent/css/minimum.css', 'srcContent/css/reference.css']
				}
			}
		},
		
		xmlmin: {
			site: {
			    files: [{
			            expand: true,     
			            cwd: 'srcContent/img',  
			            src: ['*.svg'],
			            dest: 'WebContent/img'		          
			    }]
			}
		},
		
		measuresize: {
			minified: {
				files: {
					'WebContent/minified-web.js': 'tmp/minified-web.js',
					'WebContent/minified-noie-web.js': 'tmp/minified-noie-web.js',
					'WebContent/minified-util.js': 'tmp/minified-util.js',
					'WebContent/minified-noie.js': 'tmp/minified-noie.js',
					'WebContent/minified.js': 'tmp/minified.js',
				}
			}
		},
		
		mochaTest: {
			util: {
				options: {
					bail: true,
				},
				src: [ 'src/test-util/*test.js' ]
			}
 	    },
 	    
 	    mocha: {
 	 		  quick: {
 	  			options: {
 	  				run: true,
 	  				timeout: 50000
 	  			},
 	  			src: [ 'WebContent/test/test-minified.html',  
 	  			       'WebContent/test/test-minified-noie.html']
 	  		  },
 	 		  all: {
 	  			options: {
 	  				run: true,
 	  				timeout: 50000
 	  			},
 	  			src: [ 'WebContent/test/test-minified*.html' ]
 	  		  }

 	    },
 	    
		clean: {
			tmp: ['tmp'],
			webContent: ['WebContent']
		},
		
		watch: {
			  test: {
				files: ['src/test-web/**/*'],
				tasks: ['assemble', 'testQuick']
			  },
			  code: {
				files: ['src/minified-web-src.js', 'src/minified-util-src.js', 'src/minified-shell.js'],
				tasks: ['code']
			  },
			  content: {
			    files: ['srcContent/**/*'],
			    tasks: ['site']
			  }
			},
		
		connect: {
		    server: {
		      options: {
		        port: 8080,
		        base: 'WebContent',
		        keepalive: true
		      }
		    }
		  }
	});
	
	grunt.loadTasks('build/tasks/');
	grunt.loadNpmTasks('grunt-contrib-htmlmin');
	grunt.loadNpmTasks('grunt-contrib-clean');
	grunt.loadNpmTasks('grunt-contrib-uglify');
	grunt.loadNpmTasks('grunt-closurecompiler');
	grunt.loadNpmTasks('grunt-contrib-copy');
	grunt.loadNpmTasks('grunt-contrib-cssmin');
	grunt.loadNpmTasks('grunt-mocha-test');
	grunt.loadNpmTasks('grunt-mocha');
	grunt.loadNpmTasks('grunt-xmlmin');
	grunt.loadNpmTasks('grunt-contrib-connect');
	grunt.loadNpmTasks('grunt-contrib-watch');
	
	grunt.registerTask('assemble', ['mergesrc', 'rebuildsrc', 'copy:sources', 'copy:test', 'copy:testCases', 'minitemplate:webTests']);
	grunt.registerTask('code', ['assemble', 'closurecompiler:dist', 'uglify', 'testQuick', 'measuresize']);
	grunt.registerTask('testQuick', ['mochaTest', 'mocha:quick']);
	grunt.registerTask('test', ['mochaTest', 'mocha:all']);
	grunt.registerTask('site', ['uglify:site', 'writedocs', 'minitemplate', 'copy:pngs', 'copy:test', 'cssmin', 'htmlmin', 'xmlmin']);
	grunt.registerTask('all', ['code', 'test', 'site']);
	grunt.registerTask('server', ['all', 'connect']);
	grunt.registerTask('default', ['code']);
	
	
};

