if(/^u/.test(typeof define)){var def={};this.define=function(f,m){def[f]=m()};this.require=function(f){return def[f]}}
define("minifiedUtil",function(){function f(c){return c.substr(0,3)}function m(c){return null!=c?""+c:""}function j(c){return"string"==typeof c}function k(c){return"function"==typeof c}function h(c){return!!c&&"object"==typeof c}function q(c){return"number"==typeof c}function u(c){return h(c)&&!!c.getDay}function e(c){return!0===c||!1===c}function x(c){var M=typeof c;return"object"==M?!(!c||!c.getDay):"string"==M||"number"==M||e(c)}function s(c){return!!c&&null!=c.length&&!j(c)&&!(c&&c.nodeType)&&
!k(c)}function t(c){return c}function B(c){return c+1}function v(c,M,a){return m(c).replace(M,null!=a?a:"")}function T(c){return v(c,/[\\\[\]\/{}()*+?.$|^-]/g,"\\$&")}function P(c){return v(c,/^\s+|\s+$/g)}function C(c,M){for(var a in c)c.hasOwnProperty(a)&&M(a,c[a]);return c}function y(c,a){if(c)for(var b=0;b<c.length;b++)a(c[b],b);return c}function Q(c,a){var b=[];y(c,function(c,d){a(c,d)&&b.push(c)});return b}function z(c,a,b){var d=[];c(a,function(c,a){s(c=b(c,a))?y(c,function(c){d.push(c)}):
null!=c&&d.push(c)});return d}function D(c,a){return z(y,c,a)}function E(c){var a=[];C(c,function(c){a.push(c)});return a}function w(c,a){var b=[];y(c,function(c,d){b.push(a(c,d))});return b}function A(c,a,b){var d=a;y(c,function(c,a){d=b(d,c,a)});return d}function F(c,a){if(s(c)){var b=N(a);return g(N(c).sub(0,b.length),b)}return null!=a&&c.substr(0,a.length)==a}function G(c,a){if(s(c)){var b=N(a);return N(c).sub(-b.length).equals(b)||!b.length}return null!=a&&c.substr(c.length-a.length)==a}function Y(c){var a=
c.length;return w(c,function(){return c[--a]})}function H(c,a,b){if(!s(c))return[];var d=c.length,g=0>a?d+a:a,n=null==b?d:0<=b?b:d+b;return Q(c,function(c,a){return a>=g&&a<n})}function U(c,a){var b={};y(c,function(c){b[c]=a});return b}function a(c,a,b){C(c,function(c,d){if(null==a[c]||!b)a[c]=d});return a}function b(c,a){for(var b=k(a)?a:function(c,b){if(a===c)return b},d,g=0;g<c.length;g++)if(null!=(d=b(c[g],g)))return d}function d(c,a){if(s(c))for(var b=0;b<c.length;b++)if(c[b]==a)return!0;return!1}
function g(c,a){if(c==a)return!0;if(null==c||null==a)return!1;if(x(c)||x(a))return u(c)&&u(a)&&c.getTime()==a.getTime();if(s(c))return s(a)?c.length!=a.length?!1:!b(c,function(c,b){if(!g(c,a[b]))return!0}):!1;if(s(a))return!1;var d=E(c),n=d.length,e=0;C(a,function(){e++});return n!=e?!1:!b(d,function(b){if(!g(c[b],a[b]))return!0})}function n(c,a,b){return c.apply(b&&a,w(b||a,t))}function O(c,a,b){return w(c,function(c){return k(c)?n(c,a,b):V})}function W(c,a,b,d){return function(){return n(c,a,D([b,
arguments,d],t))}}function I(c,a,b,d){setTimeout(function(){n(a,b,d)},c)}function ca(c,a,b){/^u/.test(typeof process)||!process.nextTick?setTimeout(function(){n(c,a,b)},delayMs):process.nextTick(function(){n(c,a,b)})}function Z(c,a){return da(a,0,0,0,c)}function da(c,a,b,d,g,n,e){function s(c){var a=c.length;return a>e?s(c.substr(0,a-e))+(n||",")+c.substr(a-e):c}var k=0>c,f=/(\d+)(\.(.*))?/.exec((k?-c:c).toFixed(a));c=f[1];for(d=(d||".")+f[3];c.length<(g||1);)c="0"+c;e&&(c=s(c));return(k?"-":"")+
c+(a?b?v(d,/[.,]?0+$/):d:"")}function X(c,a,b){return null==a||!c?0:60*parseInt(c[a])+parseInt(c[a+1])+b.getTimezoneOffset()}function aa(c,a){c=v(c,/^\?/);if(u(a)){var d,g,n=c,e=a,k={y:["FullYear",t],M:["Month",B],n:["Month",ja],N:["Month",ea],d:["Date",t],m:["Minutes",t],H:["Hours",t],h:["Hours",function(c){return c%12||12}],K:["Hours",B],k:["Hours",function(c){return c%12+1}],s:["Seconds",t],S:["Milliseconds",t],a:["Hours",function(c,a){return(a||ka)[12>c?0:1]}],w:["Day",qa],W:["Day",la],z:["TimezoneOffset",
function(c){if(d)return d;var a=0<c?c:-c;return(0>c?"+":"-")+Z(2,Math.floor(a/60))+Z(2,a%60)}]};if(g=/^\[(([+-]\d\d)(\d\d))\]\s*(.*)/.exec(c))d=g[1],e=ba(a,"minutes",X(g,2,a)),n=g[4];return v(n,/(\w)(\1*)(?:\[([^\]]+)\])?/g,function(c,a,b,d){if(a=k[a])c=e["get"+(s(a)?a[0]:a)].call(e),d=d&&d.split(","),c=s(a[1])?(d||a[1])[c]:a[1](c,d),null!=c&&!j(c)&&(c=Z(b.length+1,c));return c})}return b(c.split(/\s*\|\s*/),function(c){var b,d;if(b=/^([<>]?)(=?)([^:]*?)\s*:\s*(.*)$/.exec(c)){c=a;var g=parseFloat(b[3]);
if(isNaN(g)||!q(c))c=null==c?"null":m(c),g=b[3];if(b[1]){if(!b[2]&&c==g||"<"==b[1]&&c>g||">"==b[1]&&c<g)return null}else if(c!=g)return null;c=b[4]}if(q(a)&&(b=/(?:(0[0.,]*)|(#[#.,]*))(_*)(9*)/.exec(c))){d=m(b[1])+m(b[2]);var g=m(b[1]).length?v(d,/[.,]/g).length:1,n=v(v(d,/^.*[0#]/),/[^,.]/g),e=m(b[3]).length+m(b[4]).length,s,k;if(d=/([.,])[^.,]+[.,]/.exec(b[0]))s=d[1],k=d[0].length-2;s=da(a,e,m(b[3]).length,n,g,s,k);k=c;c=b.index;b=m(b[0]).length;return k.substr(0,c)+s+k.substr(c+b)}return c})}function ma(c,
a){if(1==arguments.length)return ma(null,c);if(/^\?/.test(c)){if(""==P(a))return null;c=c.substr(1)}var b,d=(b=/[0#]([.,])[_9]/.exec(c))?b[1]:(b=/^[.,]$/.exec(c))?b[0]:".";b=parseFloat(v(v(v(a,","==d?/\./g:/,/g),d,"."),/^[^\d-]*(-?\d)/,"$1"));return isNaN(b)?V:b}function na(c){return new Date(c.getTime())}function fa(c,a,b){c["set"+a].call(c,c["get"+a].call(c)+b);return c}function ba(c,a,b){return 3>arguments.length?ba(new Date,c,a):fa(na(c),a.charAt(0).toUpperCase()+a.substr(1),b)}function oa(c,
a,b){var d=a.getTime(),g=b.getTime(),n=g-d;if(0>n)return-oa(c,b,a);if(a={milliseconds:1,seconds:1E3,minutes:6E4,hours:36E5}[c])return n/a;a=c.charAt(0).toUpperCase()+c.substr(1);c=Math.floor(n/{fullYear:31536E6,month:2628E6,date:864E5}[c]-2);d=fa(new Date(d),a,c);for(n=c;n<1.2*c+4;n++)if(fa(d,a,1).getTime()>g)return n}function ga(c,a,b){var d=/^(([^.]|\.\.)+)\.([^.].*)/.exec(a);if(d){a=v(d[1],/\.\./g,".");var g=c[a];return ga(k(g)?g():g,d[3],b)}a=v(a,/\.\./g,".");g=c[a];return b===V?k(g)?g():g:k(g)?
g(b):c[a]=b}function ha(){function c(c,d){null==a&&(a=c,f=s(d)?d:[d],ca(function(){y(b,function(c){c()})}))}var a,b=[],d=arguments,g=d.length,e=0,f=[];y(d,function pa(a,b){try{a.then(function(a){a&&k(a.then)?pa(a.then,b):(f[b]=w(arguments,t),++e==g&&c(!0,2>g?f[b]:f))},function(a){f[b]=w(arguments,t);c(!1,2>g?f[b]:[f[b][0],f,b])})}catch(d){c(!1,[d,f,b])}});c.then=function(c,d){var g=ha(),e=function(){try{var b=a?c:d;if(k(b)){var e=n(b,f);e&&k(e.then)?e.then(function(c){g(!0,[c])},function(c){g(!1,
[c])}):g(!0,[e])}else g(a,f)}catch(s){g(!1,[s])}};null!=a?ca(e):b.push(e);return g};c.always=function(c){return then(c,c)};c.error=function(c){return then(0,c)};return c}function R(c,a){for(var b=0,d=0;d<c.length;d++){var g=c[d];if(a&&s(g))for(var n=0;n<g.length;n++)this[b++]=g[n];else this[b++]=g}this.length=b;this._=!0}function N(){return new R(arguments,!0)}function S(c){return function(a,b){return new R(c(this,a,b))}}function K(c){return function(a,b){return c(this,a,b)}}function L(c){return function(a,
b,d){return new R(c(a,b,d))}}var V,ea="January February March April May June July August September October November December".split(" "),ja=w(ea,f),la="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),qa=w(la,f),ka=["am","pm"],ra={'"':'\\"',"'":"\\'","\n":"\\n","\t":"\\t","\r":"\\r"},ia={};a({each:K(y),filter:S(Q),collect:S(D),map:S(w),reduce:K(A),toObject:K(U),equals:K(g),sub:S(H),reverse:S(Y),find:K(b),startsWith:K(F),endsWith:K(G),contains:K(d),call:S(O),array:function(){return w(this,
t)},func:function(){var c=this;return function(){return new R(O(c,arguments))}},join:function(c){return w(this,t).join(c)},sort:function(c){return new R(w(this,t).sort(c))},uniq:function(){var c={};return this.filter(function(a){if(c[a])return!1;c[a]=1;return!0})},intersection:function(c){var a=U(c,1);return this.filter(function(c){var b=a[c];a[c]=0;return b})},tap:function(c){c(this);return this},toString:function(){return"["+this.map(function(c){return j(c)?"'"+v(c,/'/g,"\\'")+"'":c}).join(", ")+
"]"}},R.prototype);a({bind:W,partial:function(c,a,b){return W(c,null,a,b)},once:function(c){var a=0;return function(){if(!a++)return n(c,this,arguments)}},selfFunc:t,each:y,eachObj:C,toObject:U,filter:L(Q),filterObj:function(c,a){var b={};C(c,function(c,d){a(c,d)&&(b[c]=d)});return b},collect:L(D),collectObj:L(function(c,a){return z(C,c,a)}),map:L(w),mapObj:function(a,b){var d={};C(a,function(a,c){d[a]=b(a,c)});return d},reduce:A,find:b,contains:d,sub:L(H),reverse:L(Y),startsWith:F,endsWith:G,equals:g,
toString:m,isList:s,isFunction:k,isObject:h,isNumber:q,isBool:e,isDate:u,isValue:x,isString:j,toString:m,prop:ga,escapeRegExp:T,trim:P,defer:ca,delay:I,dateClone:na,dateAdd:ba,dateDiff:oa,dateMidnight:function(a){a=a||new Date;return new Date(a.getFullYear(),a.getMonth(),a.getDate())},formatNumber:da,pad:Z,formatValue:aa,parseDate:function(a,d){var g={y:0,M:[1,1],n:[1,ja],N:[1,ea],d:2,m:4,H:3,h:3,K:[3,1],k:[3,1],s:5,S:6,a:[3,ka]},n={},e=1,k,f,m;if(/^\?/.test(a)){if(""==P(d))return null;a=a.substr(1)}if(m=
/^\[([+-]\d\d)(\d\d)\]\s*(.*)/.exec(a))k=m,a=m[3];if(!(m=RegExp(a.replace(/(.)(\1*)(?:\[([^\]]*)\])?/g,function(a,c,b,d){return/[dmhkyhs]/i.test(c)?(n[e++]=c,a=b.length+1,"(\\d"+(2>a?"+":"{1,"+a+"}")+")"):"z"==c?(f=e,e+=2,"([+-]\\d\\d)(\\d\\d)"):/[Nna]/.test(c)?(n[e++]=[c,d&&d.split(",")],"([a-zA-Z\u0080\ufffd\u1fff]+)"):/w/i.test(c)?"[a-zA-Z\u0080\ufffd\u1fff]+":/\s/.test(c)?"\\s+":T(a)})).exec(d)))return V;for(var h=[0,0,0,0,0,0,0],O=1;O<e;O++){var x=m[O],j=n[O];if(s(j)){var I=j[0],q=g[I],t=q[0],
j=b(j[1]||q[1],function(a,c){return F(x.toLowerCase(),a.toLowerCase())?c:null});if(null==j)return V;h[t]="a"==I?h[t]+12*j:j}else j&&(I=parseInt(x),q=g[j],s(q)?h[q[0]]+=I-q[1]:h[q]+=I)}g=new Date(h[0],h[1],h[2],h[3],h[4],h[5],h[6]);return ba(g,"minutes",-X(k,1,g)-X(m,f,g))},parseNumber:ma,keys:L(E),values:L(function(a){var b=[];C(a,function(a,c){b.push(c)});return b}),copyObj:a,coal:function(){return b(arguments,t)},promise:ha,format:function(a,b){return v(a,/{([^,}]*)(,([^}]*))?}/g,function(a,c,d,
g){a=""==c?b:ga(b,c);return d?aa(g,a):m(a)})},wait:function(a){var b=ha();I(function(){b(!0,[a])},a);return b},escapeHtml:function(a){return v(a,/[<>'"&]/g,function(a){return"&#"+a.charCodeAt(0)+";"})},template:function(a,b){if(ia[a])return ia[a];var d=new Function("obj","out","esc","print","_","with(obj||{}){"+w(a.split(/<%|%>/),function(a,c){if(c%2){var b=v(a,/^=/);return a==b?a:"print(esc("+b+"));\n"}return'print("'+v(a,/['"\t\n\r]/,function(a){return ra[a]})+'");\n'})+"}");return ia[a]=function(a){var c=
[];d(a,c,b||t,function(){n(c.push,c,arguments)},N);return c.join("")}}},N);return{_:N}});var l=!0,p=null,r=!1;if(/^u/.test(typeof define)){var J={};this.define=function(f,m){J[f]=m()};this.require=function(f){return J[f]}}
define("minified",function(){function f(a){return a!=p?""+a:""}function m(a){return"string"==typeof a}function j(a){return"function"==typeof a&&!a.item}function k(a){return a&&a.length!=p&&!m(a)&&!(a&&a.nodeType)&&!j(a)}function h(a,b){for(var d in a)a.hasOwnProperty(d)&&b(d,a[d]);return a}function q(a,b){for(var d=0;a&&d<a.length;d++)b(a[d],d);return a}function u(a,b){var d=[];q(a,function(a,n){b(a,n)&&d.push(a)});return d}function e(a,b){var d=[];q(a,function(a,n){k(a=b(a,n))?q(a,function(a){d.push(a)}):
a!=p&&d.push(a)});return d}function x(a,b){var d=[];h(a,function(a,n){k(a=b(a,n))?q(a,function(a){d.push(a)}):a!=p&&d.push(a)});return d}function s(a,b,d){return f(a).replace(b,d||"")}function t(a){return parseFloat(s(a,/^[^\d-]+/))}function B(a){var b={$position:"absolute",$visibility:"hidden",$display:"block",$height:p},d=a.get(b);a.set(b);b=a.get("$height",l);a.set(d);return b}function v(a){a()}function T(){q(F,v);F=p}function P(a){F?F.push(a):w.setTimeout(a,0)}function C(a,b,d,g){return function(){var n=
z(A.createElement(a));k(b)||"object"!=typeof b?n.add(b):n.set(b).add(d);g&&g(n);return n}}function y(){function a(a,n){b==p&&(b=a,d=n,w.setTimeout(function(){q(g,v)},0))}var b,d=[],g=[],n=a.then=function(a,n){function e(){try{var g=b?a:n;if(j(g)){var f=g.apply(p,d);f&&j(f.then)?f.then(function(a){k(l,[a])},function(a){k(r,[a])}):k(l,[f])}else k(b,d)}catch(s){k(r,[s])}}var k=y();b!=p?w.setTimeout(e,0):g.push(e);return k};a.always=function(a){return n(a,a)};a.error=function(a){return n(0,a)};return a}
function Q(a){return U[a]||"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}function z(a,b,d){return j(a)?P(a):new E(D(a,b,d))}function D(a,b,d){function g(a){a=function X(a){return k(a)?e(a,X):a}(a);return n?u(a,function(a){for(;a=a.parentNode;){if(a===n)return l;if(d)return r}}):a}var n,f,h,j,x;if(b&&1!=(b=D(b)).length)return e(b,function(b){return D(a,b,d)});n=b&&b[0];if(!m(a))return g(k(a)?a:[a]);if(1<(b=a.split(/\s*,\s*/)).length)return e(b,function(a){return D(a,n,d)});if(b=/(\S+)\s+(.+)$/.exec(a))return D(b[2],
D(b[1],n),d);if(a!=(b=s(a,/^#/)))return g([A.getElementById(b)]);n=n||A;f=(b=/([^.]*)\.?([^.]*)/.exec(a))[1];j=b[2];b=(h=n.getElementsByClassName&&j)?n.getElementsByClassName(j):n.getElementsByTagName(f||"*");if(f=h?f:j)x=RegExp("\\b"+f+"\\b","i"),b=u(b,function(a){return x.test(a[h?"nodeName":"className"])});return n?g(b):b}function E(a){for(var b=this.length=a.length,d=0;d<b;d++)this[d]=a[d]}var w=this,A=document,F=[],G=[],Y=e(["msR","webkitR","mozR","r"],function(a){return w[a+"equestAnimationFrame"]})[0]||
function(a){w.setTimeout(a,33)},H=!!A.all&&!F.map,U={"\t":"\\t","\r":"\\r","\n":"\\n",'"':'\\"',"\\":"\\\\"};h({each:function(a){return q(this,a)},filter:function(a){return new E(u(this,a))},collect:function(a){return new E(e(this,a))},sub:function(a,b){var d=0>a?this.length+a:a,g=0<=b?b:this.length+(b||0);return new E(u(this,function(a,b){return b>=d&&b<g}))},find:function(a){for(var b,d=j(a)?a:function(b,d){if(a===b)return d},g=0;g<this.length;g++)if((b=d(this[g],g))!=p)return b},hasClass:function(){var a=
RegExp("\\b"+name+"\\b");return this.find(function(b){return a.test(b.className)?b:p})},remove:function(){q(this,function(a){a.parentNode.removeChild(a)})},get:function(a,b){var d=this,g=d[0];if(g){if(m(a)){var n=s(a,/^[$@]/),e;e="$"==a?g.className:"$$"==a?H?g.style.cssText:g.getAttribute("style"):/\$\$/.test(a)&&("hidden"==g.style.visibility||"none"==g.style.display)?0:"$$fade"==a?isNaN(e=H?t(g.style.filter)/100:t(g.style.opacity))?1:e:"$$slide"==a?d.get("$height"):/^\$/.test(a)?w.getComputedStyle?
w.getComputedStyle(g,p).getPropertyValue(s(n,/[A-Z]/g,function(a){return"-"+a.toLowerCase()})):(g.currentStyle||g.style)[n]:/^@/.test(a)?g.getAttribute(n):g[n];return b?t(e):e}var f={};(k(a)?q:h)(a,function(a){f[a]=d.get(a,b)});return f}},set:function(a,b){var d=this,g;void 0!==b?"$$fade"==a||"$$slide"==a?d.set({$visibility:0<(g=t(b))?"visible":"hidden",$display:"block"}).set("$$fade"==a?H?{$filter:"alpha(opacity = "+100*g+")",$zoom:1}:{$opacity:g}:{$height:/px$/.test(b)?b:function(a,b,d){return g*
(g&&B(z(d)))+"px"},$overflow:"hidden"}):q(d,function(d,g){var e=s(a,/^[@$]/),f=d.className||"",k=/^\$/.test(a)?d.style:d,h=j(b)?b(z(d).get(a),g,d):b;"$"==a?h!=p&&(q(h.split(/\s+/),function(a){var b=s(a,/^[+-]/),d=f;f=s(f,RegExp("\\b"+b+"\\b"));if(/^\+/.test(a)||b==a&&d==f)f+=" "+b}),d.className=s(f,/^\s+|\s+(?=\s|$)/g)):"$$"==a?H?k.cssText=h:h!=p?d.setAttribute("style",h):d.removeAttribute("style"):/^@/.test(a)?h!=p?k.setAttribute(e,h):k.removeAttribute(e):k[e]=h}):m(a)||j(a)?d.set("$",a):h(a,function(a,
b){d.set(a,b)});return d},add:function(a,b){return q(this,function(d,g){var e;(function W(a){k(a)?q(a,W):j(a)?W(a(d,g)):a!=p&&(a=a&&a.nodeType?a:A.createTextNode(a),e?e.parentNode.insertBefore(a,e.nextSibling):b?b(a,d,d.parentNode):d.appendChild(a),e=a)})(a&&a.nodeType&&g?p:a)})},fill:function(a){return q(this,function(a){z(a.childNodes).remove()}).add(a)},addBefore:function(a){return this.add(a,function(a,d,g){g.insertBefore(a,d)})},addAfter:function(a){return this.add(a,function(a,d,g){g.insertBefore(a,
d.nextSibling)})},addFront:function(a){return this.add(a,function(a,d){d.insertBefore(a,d.firstChild)})},replace:function(a){return this.add(a,function(a,d,g){g.replaceChild(a,d)})},clone:function(a){return new E(e(this,function(b){var d=b&&b.nodeType;if(1==d){var g={$:b.className||p,$$:H?b.style.cssText:b.getAttribute("style")};q(b.attributes,function(a){var d=a.name;"id"!=d&&"style"!=d&&"class"!=d&&b.getAttribute(d)&&(g["@"+d]=a.value)});return C(b.tagName,g,z(b.childNodes).clone(),a)}return 5>
d?b.data:p}))},animate:function(a,b,d,g){var e=this,k=[],m=/-?[\d.]+/,x,u=y(),v=j(d)?d:function(a,b,g){return a+g*(b-a)*(d+(1-d)*g*(3-2*g))};g=g||{};g.time=0;g.stop=function(){x();u(r)};b=b||500;d=d||0;q(e,function(b){var d={a:z(b),c:{}};h(d.b=d.a.get(a),function(b,g){var e=a[b];"$$slide"==b&&(e=e*B(d.a)+"px");d.c[b]=/^[+-]=/.test(e)?s(e.substr(2),m,t(g)+t(s(e,/\+?=/))):e});k.push(d)});x=z.loop(function(a){function d(a,b){return/^#/.test(a)?parseInt(6<a.length?a.substr(1+2*b,2):(a=a.charAt(1+b))+
a,16):parseInt(s(a,/[^\d,]+/g).split(",")[b])}g.time=a;a>=b||0>a?(q(k,function(a){a.a.set(a.c)}),x(),g.time=p,u(l,[e])):q(k,function(g){h(g.b,function(e,k){var n="rgb(",h=g.c[e],j=a/b;if(/^#|rgb\(/.test(h))for(var x=0;3>x;x++)n+=Math.round(v(d(k,x),d(h,x),j))+(2>x?",":")");else n=s(h,m,f(v(t(k),t(h),j)));g.a.set(e,n)})})});return u},toggle:function(a,b,d,g){var e=this,f={},k=r,h=/\b(?=\w)/g;return!b?e.toggle(s(a,h,"-"),s(a,h,"+")):e.set(a)&&function(h){h!==k&&(k=h===l||h===r?h:!k,d?e.animate(k?b:
a,f.stop?f.stop()||f.time:d,g,f):e.set(k?b:a))}},on:function(a,b,d,g){return q(this,function(e,f){q(a.split(/\s/),function(a){function k(e){e=e||w.event;if((!b.apply(g?d:e.target,g||d||[e,f])||g)&&a==h)e.stopPropagation&&(e.preventDefault(),e.stopPropagation()),e.returnValue=r,e.cancelBubble=l}var h=s(a,/\|/);(b.M=b.M||[]).push({e:e,h:k,n:h});e.addEventListener?e.addEventListener(h,k,l):e.attachEvent("on"+h,k)})})}},function(a,b){E.prototype[a]=b});h({request:function(a,b,d,g,n,s){var j,q=d,t=0,u=
y();try{return j=w.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Msxml2.XMLHTTP.3.0"),d!=p&&(g=g||{},!m(d)&&!(d&&d.nodeType)&&(q=x(d,function aa(a,b){return k(b)?e(b,function(b){return aa(a,b)}):encodeURIComponent(a)+(b!=p?"="+encodeURIComponent(b):"")}).join("&")),/post/i.test(a)?!(d&&d.nodeType)&&!m(d)&&!g["Content-Type"]&&(g["Content-Type"]="application/x-www-form-urlencoded"):(b+="?"+q,q=p)),j.open(a,b,l,n,s),h(g,function(a,b){j.setRequestHeader(a,b)}),j.onreadystatechange=function(){4==
j.readyState&&!t++&&(200==j.status?u(l,[j.responseText,j.responseXML]):u(r,[j.status,j.statusText,j.responseText]))},j.send(q),u}catch(v){t||u(r,[0,p,f(v)])}},toJSON:function b(d){return d==p?""+d:m(d=d.valueOf())?'"'+s(d,/[\\\"\x00-\x1f\x22\x5c]/g,Q)+'"':k(d)?"["+e(d,b).join()+"]":"object"==typeof d?"{"+x(d,function(d,e){return b(d)+":"+b(e)}).join()+"}":f(d)},parseJSON:w.JSON?w.JSON.parse:function(b){b=s(b,/[\x00\xad\u0600-\uffff]/g,Q);if(/^[[\],:{}\s]*$/.test(s(s(b,/\\["\\\/bfnrtu]/g),/"[^"\\\n\r]*"|true|false|null|[\d.eE+-]+/g)))return eval("("+
b+")")},ready:P,setCookie:function(b,d,g,e,k,f){A.cookie=b+"="+(f?d:escape(d))+(g?"; expires="+("object"==typeof g?g:new Date((new Date).getTime()+864E5*g)).toUTCString():"")+"; path="+(e?escapeURI(e):"/")+(k?"; domain="+escape(k):"")},getCookie:function(b,d){var g,e=(g=RegExp("(^|;)\\s*"+b+"=([^;]*)").exec(A.cookie))&&g[2];return d?e:e&&unescape(e)},loop:function(b){var d={d:b,f:(new Date).getTime(),b:function(){for(var b=0;b<G.length;b++)G[b]===d&&G.splice(b--,1)}};2>G.push(d)&&function n(){q(G,
function(b){b.d(Math.max(0,(new Date).getTime()-b.f),b.b)}).length&&Y(n)}();return d.b},off:function(b){q(b.M,function(b){b.e.removeEventListener?b.e.removeEventListener(b.n,b.h,l):b.e.detachEvent("on"+b.n,b.h)});b.M=p}},function(b,d){z[b]=d});w.onload=T;A.addEventListener&&A.addEventListener("DOMContentLoaded",T,r);return{$:z,$$:function(b){return D(b)[0]},EE:C}});var _=require("minifiedUtil")._;
function parseSourceSections(f){function m(){return{id:"anon"+j++,src:[],desc:"",requires:{},requiredBy:{},syntax:[],example:[],params:[]}}f=f.split("\n");var j=100,k=[],h=m(),q=!1;_.each(f,function(f){if(q&&/^.*\*\/\s*$/.test(f))q=!1;else if(q){var e=f.replace(/^\s*(\*\s?)?/,"").replace(/\s*$/,""),j=e.match(/^\s*@([a-z]+)/);j?(j=j[1],e=_.trim(e.replace(/^\s*@[a-z]+\s*/,"")),"syntax"==j||"example"==j?h[j].push(e):"requires"==j?e.length&&_.each(e.split(/\s+/),function(e){h.requires[e]=1}):"param"==
j?h.params.push({name:e.replace(/\s.*$/,""),desc:e.replace(/^\S+\s+/,"")}):"return"==j?h.params.push({name:"@return",desc:e}):"function"==j?h.params[h.params.length-1].funcs.push(e):h[j]=""!=e?e:1):h.params.length?h.params[h.params.length-1].desc+="\n"+_.trim(e):h.example.length?h.example[h.example.length-1]+="\n"+e:h.desc+=e+"\n"}else/^\s*\/\*\$/.test(f)&&!/\*\/\s*$/.test(f)&&(q=!0,k.push(h),h=m());h.src.push(f)});k.push(h);return k}
function createSectionMap(f){var m={};_.each(f,function(f){m[f.id]=f});return m}function completeRequirements(f,m){var j=0;_.each(f,function(f){_.eachObj(f.requires,function(h){var q=m[h];if(!q)throw Error('Unknown id in requirement: "'+h+'"');_.eachObj(q.requires,function(h){f.requires[h]||(j++,f.requires[h]=1)})})});0<j?completeRequirements(f,m):_.each(f,function(f){_.eachObj(f.requires,function(h){m[h].requiredBy[f.id]=1})})}
function calculateDependencies(f,m){var j={};_.eachObj(m,function(k){m[k]&&(j[k]=1,_.eachObj(f[k].requires,function(f){j[f]=1}))});return j}function createDefaultConfigurationMap(f,m){var j={};_.each(f,function(f){if(f.configurable&&("default"==f.configurable||m))j[f.id]=1});return j}
function compile(f,m,j){var k="",h=calculateDependencies(m,j),q=[],u=!0;_.filter(f,function(e){return h[e.id]||!(e.configurable||e.dependency)}).each(function(e){_.each(e.src,function(e){if(/^\s*$/.test(e))u||(k+="\n"),u=!0;else{var f=e.match(/^(\s*)\/\/\s*@(cond|condblock)\s+(\!?)(\w*)\s*(.*)$/);if(f&&"cond"==f[2]&&!!h[f[4]]!=("!"==f[3]))k+=f[1]+f[5]+"\n";else if(f&&"condblock"==f[2])q.unshift(!!h[f[4]]!=("!"==f[3]));else if(q.length&&/^\s*\/\/\s*@condend(\s|$)/.test(e))q.shift();else if(0==q.length||
q[0])k+=e+"\n";u=!1}})});return k}function prepareSections(f){f=parseSourceSections(f);var m=createSectionMap(f);completeRequirements(f,m);var j=createDefaultConfigurationMap(f);return{sections:f,sectionMap:m,enabledSections:j}}var CONFIG_START="minified.js config start --",CONFIG_COMMENT="// - ",CONFIG_ALL="All sections.",CONFIG_ALL_EXCEPT="All sections except ",CONFIG_ONLY="Only sections ";
function serializeEnabledSections(f,m){var j=_.filter(f,function(e){return e.configurable}),k=_.filter(_.keys(m),function(e){return m[e]}),h,q=[];k.length==j.length?(h=CONFIG_COMMENT+CONFIG_ALL,q=[]):k.length/3>j.length/2?(h=CONFIG_COMMENT+CONFIG_ALL_EXCEPT,q=_.filter(j,function(e){return!m[e.id]}).collect(function(e){return e.id})):(h=CONFIG_COMMENT+CONFIG_ONLY,q=k);var u="// "+CONFIG_START+" use this comment to re-create configuration in the Builder\n"+h,e=50;_(q).sort().each(function(f){e<f.length?
(e=70,u+="\n// - "+f+", "):(u+=f+", ",e-=f.length+2)});return u=u.replace(/,\s*$/,".\n")}function fixConfig(f,m){_.eachObj(m,function(j){f[j]?_.copyObj(f[j].requires,m):delete m[j]});return m}
function deserializeEnabledSections(f,m,j){function k(e){return RegExp("^"+e.replace(/ /g,"\\s+"))}var h=k(CONFIG_START+".*"),q=k(CONFIG_ALL.replace(/\./,"\\.")),u=k(CONFIG_ALL_EXCEPT+"\\s*"),e=k(CONFIG_ONLY+"\\s*"),x=k(CONFIG_COMMENT);j=j.split("\n");for(var s=0;s<j.length;s++){var t=j[s];if(/^\s*\/\/s*/.test(t)&&(t=t.replace(/^\s*\/\/\s*/,""),h.test(t)&&s+1<j.length)){for(var t="",B=s+1;B<j.length;B++)if(x.test(j[B])){if(t+=j[B].replace(x,""),/\s*\.\s*$/.test(j[B]))break}else break;if(q.test(t))return createDefaultConfigurationMap(f,
!0);t=t.replace(/\s*\.\s*$/,"");if(u.test(t)){var v=createDefaultConfigurationMap(f,!0);_.each(t.replace(u,"").split(/\s*,\s*/),function(e){delete v[e]});return fixConfig(m,v)}if(e.test(t))return v={},_.each(t.replace(e,"").split(/\s*,\s*/),function(e){m[e]&&(v[e]=1)}),fixConfig(m,v)}}return null};var MINI=require("minified"),$=MINI.$,$$=MINI.$$,EE=MINI.EE,_=require("minifiedUtil")._,MAX_SIZE=4095,SRC="/minified-web-src.js",GROUPS="INTERNAL SELECTORS ELEMENT REQUEST JSON EVENTS COOKIE ANIMATION OPTIONS".split(" ");
function closureCompile(f,m,j){$.request("post","http://closure-compiler.appspot.com/compile",{js_code:f,output_format:"json",output_info:["compiled_code","statistics"],output_file_name:"minified-custom.js",compilation_level:m?"ADVANCED_OPTIMIZATIONS":"SIMPLE_OPTIMIZATIONS"}).then(function(f){j&&j($.parseJSON(f))},function(f,h,m){window.console&&console.log("error",f,h,m);j&&j(null)}).error(function(f){window.console&&console.log(f)})}
function setUpConfigurationUI(f){function m(){$(".modCheck").each(function(e){var f=0;$(".secCheck",e.parentNode.parentNode).each(function(e){e.checked&&f++});e.checked=0<f})}function j(e){var h=f.sectionMap[e.id.substr(4)];e.checked?_.eachObj(h.requires,function(e){$("#sec-"+e).set("checked",!0)}):_.eachObj(h.requiredBy,function(e){$("#sec-"+e).set("checked",!1)})}$("#compile").on("click",function(){var e={};$(".secCheck").each(function(f){f.checked&&(e[f.id.substr(4)]=1)});var h=compile(f.sections,
f.sectionMap,e),j=serializeEnabledSections(f.sections,e);if($$("#compressionAdvanced").checked)$$("#compile").disabled=!0,closureCompile(h,!0,function(e){$$("#compile").disabled=!1;$("#resultDiv").animate({$$slide:1});e?($("#gzipRow, #downloadRow").set({$display:"table-row"}),$$("#resultSrc").value=j+"\n"+e.compiledCode,$("#resultPlain").fill((e.statistics.compressedSize/1024).toFixed(2)+"kb ("+e.statistics.compressedSize+" bytes)"),$("#resultGzippedSize").fill((e.statistics.compressedGzipSize/1024).toFixed(2)+
"kb ("+e.statistics.compressedGzipSize+" bytes)"),$$("#resultLink").setAttribute("href","http://closure-compiler.appspot.com"+e.outputFilePath),$("#resultGzippedComment").set({$$fade:e.statistics.compressedGzipSize>MAX_SIZE?1:0})):alert("Google Closure Service not availble. Try again later.")});else try{$("#resultDiv").animate({$$slide:1}),$$("#resultSrc").value=j+h,$("#resultPlain").fill((h.length/1024).toFixed(2)+"kb"),$("#gzipRow, #downloadRow").set({$display:"none"})}catch(k){console.log(k)}return!1});
var k=$("#configSrcDiv").toggle({$$slide:0},{$$slide:1});$("#fromScratch").on("|click",k,[!1]);$("#loadConfig").on("|click",k,[!0]);$("#recreate").on("click",function(){try{var e=$$("#configSrc").value,h=deserializeEnabledSections(f.sections,f.sectionMap,e);h?(_.eachObj(f.sectionMap,function(e){var f=$$("#sec-"+e);f&&(f.checked=!!h[e])}),m()):alert("Can not find configuration in source.")}catch(j){console.log(j)}});$("#sectionCheckboxes").fill();for(var h=1;h<GROUPS.length;h++){var q;$("#sectionCheckboxes").add(q=
EE("div",{"@id":"divMod-"+h},EE("div",{className:"groupDescriptor"},[k=EE("input",{"@id":"mod-"+h,className:"modCheck","@type":"checkbox",checked:"checked"})(),EE("label",{"@for":"mod-"+h},GROUPS[h])]))());$(k).on("change",function(){var e=this.checked;$(".secCheck",this.parentNode.parentNode).each(function(f){f.checked=e;j(f)});m();return!0});var u;_.filter(f.sections,function(e){return e.group==GROUPS[h]&&e.configurable}).sort(function(e,f){var h=e.name||e.id,j=f.name||f.id;return h==j?0:h>j?1:
-1}).each(function(e){function h(e,j){var k=_.filter(_.keys(j),function(e){return!!j[e].name});if(!k.length)return null;var m=0,q=e;_.each(k,function(e){m++<Math.min(k.length,8)&&(1<m&&(q=m==Math.min(k.length,8)?q+" and ":q+", "),q=8==m&&8<k.length?q+"more":q+(f.sectionMap[e].name||f.sectionMap[e].id))});return q+="."}var k=h("Required by ",e.requiredBy),t=h("Requires ",e.requires);q.add(EE("div",{className:"sectionDescriptor"},[u=EE("input",{className:"secCheck","@type":"checkbox","@id":"sec-"+e.id,
checked:"default"==e.configurable?"checked":null})(),EE("label",{"@for":"sec-"+e.id},e.name||e.id),EE("div",{className:"requirements"},[k?[k,EE("br")]:null,t])]));$(u).on("change",function(){j(this);m();return!0})})}}$(function(){$.request("get",SRC,null).then(function(f){setUpConfigurationUI(prepareSections(f))}).error(function(f){window.console&&console.log(f)})});
