if(/^u/.test(typeof define)){var def={};this.define=function(j,e){def[j]=e()};this.require=function(j){return def[j]}}
define("minifiedUtil",function(){function j(q){return q.substr(0,3)}function e(q){return null!=q?""+q:""}function n(q){return"string"==typeof q}function g(q){return!!q&&"object"==typeof q}function l(q){return"number"==typeof q}function t(q){return g(q)&&!!q.getDay}function u(q){return!0===q||!1===q}function m(q){var a=typeof q;return"object"==a?!(!q||!q.getDay):"string"==a||"number"==a||u(q)}function h(q){return!!q&&null!=q.length&&!n(q)&&!(q&&q.nodeType)&&!Q(q)}function k(q){return q}function w(q){return q+
1}function p(q,a,b){return e(q).replace(a,null!=b?b:"")}function r(q){return p(q,/[\\\[\]\/{}()*+?.$|^-]/g,"\\$&")}function G(q){return p(q,/^\s+|\s+$/g)}function x(q,a){for(var b in q)q.hasOwnProperty(b)&&a(b,q[b]);return q}function A(a,b){if(a)for(var c=0;c<a.length;c++)b(a[c],c);return a}function L(a,b){var c=[],d=Q(b)?b:function(a){return b!=a};A(a,function(a,q){d(a,q)&&c.push(a)});return c}function X(a,b,c){var d=[];a(b,function(a,q){h(a=c(a,q))?A(a,function(a){d.push(a)}):null!=a&&d.push(a)});
return d}function U(a,b){return X(A,a,b)}function Y(a){var b=[];x(a,function(a){b.push(a)});return b}function B(a,b){var c=[];A(a,function(a,q){c.push(b(a,q))});return c}function V(a,b){if(h(a)){var c=R(b);return H(R(a).sub(0,c.length),c)}return null!=b&&a.substr(0,b.length)==b}function Z(a,b){if(h(a)){var c=R(b);return R(a).sub(-c.length).equals(c)||!c.length}return null!=b&&a.substr(a.length-b.length)==b}function aa(a){var b=a.length;return B(a,function(){return a[--b]})}function y(a,b,c){if(!a)return[];
var d=a.length,f=0>b?d+b:b,s=null==c?d:0<=c?c:d+c;return L(a,function(a,b){return b>=f&&b<s})}function D(a,b){var c={};A(a,function(a){c[a]=b});return c}function O(a,b,c){x(a,function(a,q){if(null==b[a]||!c)b[a]=q});return b}function I(a,b){for(var c=Q(b)?b:function(a,c){if(b===a)return c},d,f=0;f<a.length;f++)if(null!=(d=c(a[f],f)))return d}function M(a){return B(a,k)}function z(a){return function(){return new P(ba(a,arguments))}}function E(a){var b={};return L(a,function(a){if(b[a])return!1;b[a]=
1;return!0})}function ca(a,b){var c=D(b,1);return L(a,function(a){var b=c[a];c[a]=0;return b})}function J(a,b){for(var c=0;c<a.length;c++)if(a[c]==b)return!0;return!1}function H(a,b){var c=Q(a)?a():a,d=Q(b)?b():b;if(c==d)return!0;if(null==c||null==d)return!1;if(m(c)||m(d))return t(c)&&t(d)&&c.getTime()==d.getTime();if(h(c))return c.length!=d.length?!1:!I(c,function(a,b){if(!H(a,d[b]))return!0});if(h(d))return!1;var f=Y(c),s=f.length,v=0;x(d,function(){v++});return s!=v?!1:!I(f,function(a){if(!H(c[a],
d[a]))return!0})}function S(a,b,c){return a.apply(c&&b,B(c||b,k))}function ba(a,b,c){return B(a,function(a){return Q(a)?S(a,b,c):da})}function F(a,b,c,d){return function(){return S(a,b,U([c,arguments,d],k))}}function W(b,c){return a(c,0,0,0,b)}function a(a,b,c,d,f,s,h){function v(a){var b=a.length;return b>h?v(a.substr(0,b-h))+(s||",")+a.substr(b-h):a}var k=0>a,m=/(\d+)(\.(.*))?/.exec((k?-a:a).toFixed(b));a=m[1];for(d=(d||".")+m[3];a.length<(f||1);)a="0"+a;h&&(a=v(a));return(k?"-":"")+a+(b?c?p(d,
/[.,]?0+$/):d:"")}function b(a,b,c){return null==b||!a?0:60*parseInt(a[b])+parseInt(a[b+1])+c.getTimezoneOffset()}function c(a,b){if(1==arguments.length)return c(null,a);if(/^\?/.test(a)){if(""==G(b))return null;a=a.substr(1)}var d,f=(d=/[0#]([.,])[_9]/.exec(a))?d[1]:(d=/^[.,]$/.exec(a))?d[0]:".";d=parseFloat(p(p(p(b,","==f?/\./g:/,/g),f,"."),/^[^\d-]*(-?\d)/,"$1"));return isNaN(d)?da:d}function d(a){return new Date(a.getTime())}function f(a,b,c){a["set"+b].call(a,a["get"+b].call(a)+c);return a}function s(a,
b,c){return 3>arguments.length?s(new Date,a,b):f(d(a),b.charAt(0).toUpperCase()+b.substr(1),c)}function v(a,b,c){var d=b.getTime(),s=c.getTime(),h=s-d;if(0>h)return-v(a,c,b);if(b={milliseconds:1,seconds:1E3,minutes:6E4,hours:36E5}[a])return h/b;b=a.charAt(0).toUpperCase()+a.substr(1);a=Math.floor(h/{fullYear:31536E6,month:2628E6,date:864E5}[a]-2);d=f(new Date(d),b,a);for(h=a;h<1.2*a+4;h++)if(f(d,b,1).getTime()>s)return h}function T(a){return p(a,/['"\t\n\r]/g,function(a){return la[a]})}function ea(a,
b){if(fa[a])return fa[a];var c="with(_.isObject(obj)?obj:{}){"+B(a.split(/{{|}}}?/),function(a,b){var c,d=G(a),f=p(d,/^{/),d=d==f?"esc(":"";if(b%2)return(c=/^each\b(\s+([\w_]+(\s*,\s*[\w_]+)?)\s*:)?(.*)/.exec(f))?"each("+(""==G(c[4])?"this":c[4])+", function("+c[2]+"){":(c=/^if\b(.*)/.exec(f))?"if("+c[1]+"){":(c=/^else\b\s*(if\b(.*))?/.exec(f))?"}else "+(c[1]?"if("+c[2]+")":"")+"{":(c=/^\/(if)?/.exec(f))?c[1]?"}\n":"});\n":(c=/^#(.*)/.exec(f))?c[1]:(c=/(.*)::\s*(.*)/.exec(f))?"print("+d+'_.formatValue("'+
T(c[2])+'",'+(""==G(c[1])?"this":c[1])+(d&&")")+"));\n":"print("+d+(""==G(f)?"this":f)+(d&&")")+");\n";if(""!=a)return'print("'+T(a)+'");\n'}).join("")+"}",d=new Function("obj","each","esc","print","_",c);return fa[a]=function(a,c){var f=[];d.call(c||a,a,function(a,b){h(a)?A(a,function(a,c){b.call(a,a,c)}):x(a,function(a,c){b.call(c,a,c)})},b||k,function(){S(f.push,f,arguments)},R);return f.join("")}}function ha(a){return p(a,/[<>'"&]/g,function(a){return"&#"+a.charCodeAt(0)+";"})}function K(a){return function(b,
c){return new P(a(this,b,c))}}function N(a){return function(b,c){return a(this,b,c)}}function C(a){return function(b,c,d){return new P(a(b,c,d))}}function Q(a){return"function"==typeof a}function P(a,b){for(var c=0,d=0;d<a.length;d++){var f=a[d];if(b&&h(f))for(var s=0;s<f.length;s++)this[c++]=f[s];else this[c++]=f}this.length=c;this._=!0}function R(){return new P(arguments,!0)}var da,ga="January,February,March,April,May,June,July,August,September,October,November,December".split(/,/),ia=B(ga,j),ja=
"Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday".split(/,/),ma=B(ja,j),ka=["am","pm"],la={'"':'\\"',"'":"\\'","\n":"\\n","\t":"\\t","\r":"\\r"},fa={};O({each:N(A),filter:K(L),collect:K(U),map:K(B),toObject:N(D),equals:N(H),sub:K(y),reverse:K(aa),find:N(I),startsWith:N(V),endsWith:N(Z),contains:N(J),call:K(ba),array:N(M),unite:N(z),uniq:K(E),intersection:K(ca),join:function(a){return B(this,k).join(a)},sort:function(a){return new P(B(this,k).sort(a))}},P.prototype);O({filter:C(L),collect:C(U),
collectObj:C(function(a,b){return X(x,a,b)}),map:C(B),sub:C(y),reverse:C(aa),each:A,toObject:D,find:I,contains:J,startsWith:V,endsWith:Z,equals:H,keys:C(Y),values:C(function(a,b){var c=[];b?A(b,function(b){c.push(a[b])}):x(a,function(a,b){c.push(b)});return c}),call:C(ba),array:M,unite:z,uniq:C(E),intersection:C(ca),copyObj:O,range:function(a,b){for(var c=[],d=null==b?a:b,f=null!=b?a:0;f<d;f++)c.push(f);return new P(c)},bind:F,partial:function(a,b,c){return F(a,null,b,c)},eachObj:x,mapObj:function(a,
b){var c={};x(a,function(a,d){c[a]=b(a,d)});return c},filterObj:function(a,b){var c={};x(a,function(a,d){b(a,d)&&(c[a]=d)});return c},isList:h,isFunction:Q,isObject:g,isNumber:l,isBool:u,isDate:t,isValue:m,isString:n,toString:e,dateClone:d,dateAdd:s,dateDiff:v,dateMidnight:function(a){a=a||new Date;return new Date(a.getFullYear(),a.getMonth(),a.getDate())},pad:W,formatValue:function(c,d){c=p(c,/^\?/);if(t(d)){var f,v,m=c,g=d,T={y:["FullYear",k],Y:["FullYear",function(a){return a%100}],M:["Month",
w],n:["Month",ia],N:["Month",ga],d:["Date",k],m:["Minutes",k],H:["Hours",k],h:["Hours",function(a){return a%12||12}],k:["Hours",w],K:["Hours",function(a){return a%12}],s:["Seconds",k],S:["Milliseconds",k],a:["Hours",function(a,b){return(b||ka)[12>a?0:1]}],w:["Day",ma],W:["Day",ja],z:["TimezoneOffset",function(a){if(f)return f;var b=0<a?a:-a;return(0>a?"+":"-")+W(2,Math.floor(b/60))+W(2,b%60)}]};if(v=/^\[(([+-]\d\d)(\d\d))\]\s*(.*)/.exec(c))f=v[1],g=s(d,"minutes",b(v,2,d)),m=v[4];return p(m,/(\w)(\1*)(?:\[([^\]]+)\])?/g,
function(a,b,c,d){if(b=T[b])a=g["get"+(h(b)?b[0]:b)].call(g),d=d&&d.split(","),a=h(b[1])?(d||b[1])[a]:b[1](a,d),null!=a&&!n(a)&&(a=W(c.length+1,a));return a})}return I(c.split(/\s*\|\s*/),function(b){var c,f;if(c=/^([<>]?)(=?)([^:]*?)\s*:\s*(.*)$/.exec(b)){b=d;var s=parseFloat(c[3]);if(isNaN(s)||!l(b))b=null==b?"null":e(b),s=c[3];if(c[1]){if(!c[2]&&b==s||"<"==c[1]&&b>s||">"==c[1]&&b<s)return null}else if(b!=s)return null;b=c[4]}if(l(d)&&(c=/(?:(0[0.,]*)|(#[#.,]*))(_*)(9*)/.exec(b))){f=e(c[1])+e(c[2]);
var s=e(c[1]).length?p(f,/[.,]/g).length:1,h=p(p(f,/^.*[0#]/),/[^,.]/g),v=e(c[3]).length+e(c[4]).length,k,m;if(f=/([.,])[^.,]+[.,]/.exec(c[0]))k=f[1],m=f[0].length-2;k=a(d,v,e(c[3]).length,h,s,k,m);m=b;b=c.index;c=e(c[0]).length;return m.substr(0,b)+k+m.substr(b+c)}return b})},parseDate:function(a,c){var d={y:0,Y:[0,-2E3],M:[1,1],n:[1,ia],N:[1,ga],d:2,m:4,H:3,h:3,K:[3,1],k:[3,1],s:5,S:6,a:[3,ka]},f={},v=1,k,m,g;if(/^\?/.test(a)){if(""==G(c))return null;a=a.substr(1)}if(g=/^\[([+-]\d\d)(\d\d)\]\s*(.*)/.exec(a))k=
g,a=g[3];if(!(g=RegExp(a.replace(/(.)(\1*)(?:\[([^\]]*)\])?/g,function(a,b,c,d){return/[dmhkyhs]/i.test(b)?(f[v++]=b,a=c.length+1,"(\\d"+(2>a?"+":"{1,"+a+"}")+")"):"z"==b?(m=v,v+=2,"([+-]\\d\\d)(\\d\\d)"):/[Nna]/.test(b)?(f[v++]=[b,d&&d.split(",")],"([a-zA-Z\u0080\ufffd\u1fff]+)"):/w/i.test(b)?"[a-zA-Z\u0080\ufffd\u1fff]+":/\s/.test(b)?"\\s+":r(a)})).exec(c)))return da;for(var e=[0,0,0,0,0,0,0],l=1;l<v;l++){var T=g[l],j=f[l];if(h(j)){var n=j[0],p=d[n],C=p[0],j=I(j[1]||p[1],function(a,b){return V(T.toLowerCase(),
a.toLowerCase())?b:null});if(null==j)return da;e[C]="a"==n?e[C]+12*j:j}else j&&(n=parseInt(T),p=d[j],h(p)?e[p[0]]+=n-p[1]:e[p]+=n)}d=new Date(e[0],e[1],e[2],e[3],e[4],e[5],e[6]);return s(d,"minutes",-b(k,1,d)-b(g,m,d))},parseNumber:c,trim:G,escapeRegExp:r,escapeHtml:ha,format:function(a,b){return ea(a)(b)},template:ea,formatHtml:function(a,b){return ea(a,ha)(b)}},R);return{_:R,M:P}});/^u/.test(typeof define)&&(def={},this.define=function(j,e){def[j]=e()},this.require=function(j){return def[j]});
define("minified",function(){function j(){return 1}function e(a){return null!=a?""+a:""}function n(a){return"string"==typeof a}function g(a){return a&&a.nodeType}function l(a){return a&&null!=a.length&&!n(a)&&!g(a)&&!p(a)}function t(a){return a}function u(a,b){for(var c in a)a.hasOwnProperty(c)&&b(c,a[c])}function m(a,b){var c=[];r(a,function(a,f){b(a,f)&&c.push(a)});return c}function h(a,b,c){var d=[];a(b,function(a,b){r(c(a,b),function(a){d.push(a)})});return d}function k(a,b,c){return e(a).replace(b,
c||"")}function w(a,b){var c=RegExp("\\b"+a+"\\b","i");return a?function(a){return c.test(a[b])}:j}function p(a){return"function"==typeof a&&!a.item}function r(a,b){if(l(a))for(var c=0;c<a.length;c++)b(a[c],c);else null!=a&&b(a,0);return a}function G(a,b){for(var c=0;a&&c<a.length;c++)a[c]===b&&a.splice(c--,1)}function x(a){return parseFloat(k(a,/^[^\d-]+/))}function A(a){return a.minified=a.minified||++ca}function L(a,b){var c=[],d={},f;r(a,function(a){r(b(a),function(a){if(g(a)&&!d[f=A(a)])c.push(a),
d[f]=!0})});return c}function X(a){var b={$position:"absolute",$visibility:"hidden",$display:"block",$height:null},c=a.get(b);a.set(b);b=a.get("$height",!0);a.set(c);return b}function U(a){a()}function Y(a,b){r(b,function(a){a.e.detachEvent("on"+a.n,a.h)})}function B(){r(H,U);H=null}function V(a){H?H.push(a):z.setTimeout(a,0)}function Z(a,b,c,d){return function(){var f=y(E.createElement(a));l(b)||"object"!=typeof b?f.add(b):f.set(b).add(c);d&&d(f);return f}}function aa(a){return W[a]||"\\u"+("0000"+
a.charCodeAt(0).toString(16)).slice(-4)}function y(a,b,c){return p(a)?V(a):new M(D(a,b,c))}function D(a,b,c){function d(a){a=h(r,a,function K(a){return l(a)?h(r,a,K):a});return f?m(a,function(a){for(;a=a.parentNode;){if(a===f)return!0;if(c)return!1}}):a}var f,s,v,e;if(b&&1!=(b=D(b)).length)return L(b,function(b){return D(a,b,c)});f=b&&b[0];if(!n(a))return d(a);if(1<(b=a.split(/\s*,\s*/)).length)return L(b,function(a){return D(a,f,c)});if(b=/(\S+)\s+(.+)$/.exec(a))return D(b[2],D(b[1],f),c);if(a!=
(b=k(a,/^#/)))return d(E.getElementById(b));f=f||E;s=(b=/([\w-]*)\.?([\w-]*)/.exec(a))[1];e=b[2];b=(v=f.getElementsByClassName&&e)?f.getElementsByClassName(e):f.getElementsByTagName(s||"*");if(s=v?s:e)b=m(b,w(s,v?"nodeName":"className"));return f?d(b):b}function O(a,b){var c,d={};if(p(a))return a;if(!a||n(a)&&("*"==a||(c=/^([\w-]*)\.([\w-]+)$/.exec(a))||(c=/^([\w-]+)$/.exec(a)))){var f=w(c&&c[1],"nodeName"),s=w(c&&c[2],"className");return function(a){return 1==g(a)&&f(a)&&s(a)}}if(b)return function(c){return null!=
y(a,b).find(c)};y(a).each(function(a){d[A(a)]=!0});return function(a){return d[A(a)]}}function I(){var a,b=[],c=[],d=function(d,f){null==a&&(a=d,b=f,z.setTimeout(function(){r(c,U)},0))},f=d.then=function(d,f){var h=I(),k=function(){try{var c=a?d:f;if(p(c)){var k=c.apply(null,b);k&&p(k.then)?k.then(function(a){h(!0,[a])},function(a){h(!1,[a])}):h(!0,[k])}else h(a,b)}catch(e){h(!1,[e])}};null!=a?z.setTimeout(k,0):c.push(k);return h};d.error=function(a){return f(0,a)};return d}function M(a){for(var b=
this.length=a.length,c=0;c<b;c++)this[c]=a[c]}var z=this,E=document,ca=1,J={},H=[],S=[],ba=z.requestAnimationFrame||function(a){z.setTimeout(a,33)},F=!!E.all&&!H.map,W={"\t":"\\t","\r":"\\r","\n":"\\n",'"':'\\"',"\\":"\\\\"};u({each:function(a){return r(this,a)},filter:function(a){return new M(m(this,a))},collect:function(a){return new M(h(r,this,a))},sub:function(a,b){var c=0>a?this.length+a:a,d=0<=b?b:this.length+(b||0);return this.filter(function(a,b){return b>=c&&b<d})},find:function(a){for(var b,
c=p(a)?a:function(b,c){if(a===b)return c},d=0;d<this.length;d++)if(null!=(b=c(this[d],d)))return b},remove:function(){r(this,function(a){F&&1==g(a)&&(r(D("*",a),function(a){Y(0,J[a.minified]);delete J[a.minified]}),removeEvents(a));a.parentNode.removeChild(a)})},text:function(){function a(b){var c=g(b);return 1==c?h(r,b.childNodes,a):5>c?b.data:null}return h(r,this,a).join("")},trav:function(a,b,c){var d=O("number"==typeof b?null:b),f="number"==typeof b?b:c||1E9;return new M(L(this,function(b){for(var c=
[];(b=b[a])&&c.length<f;)d(b)&&c.push(b);return c}))},select:function(a,b){return y(a,this,b)},is:function(a){var b=O(a);return!this.find(function(a){if(!b(a))return!0})},only:function(a){return this.filter(O(a))},get:function(a,b){var c=this,d=c[0];if(d){if(n(a)){var f=k(k(a,/^%/,"data-"),/^[$@]/),h;h="$"==a?d.className:"$$"==a?F?d.style.cssText:d.getAttribute("style"):/\$\$/.test(a)&&("hidden"==d.style.visibility||"none"==d.style.display)?0:"$$fade"==a?isNaN(h=F?x(d.style.filter)/100:x(d.style.opacity))?
1:h:"$$slide"==a?c.get("$height"):/^\$/.test(a)?z.getComputedStyle?z.getComputedStyle(d,null).getPropertyValue(k(f,/[A-Z]/g,function(a){return"-"+a.toLowerCase()})):(d.currentStyle||d.style)[f]:/^[@%]/.test(a)?d.getAttribute(f):d[f];return b?x(h):h}var e={};(l(a)?r:u)(a,function(a){e[a]=c.get(a,b)});return e}},set:function(a,b){var c=this,d;void 0!==b?"$$fade"==a||"$$slide"==a?c.set({$visibility:0<(d=x(b))?"visible":"hidden",$display:"block"}).set("$$fade"==a?F?{$filter:"alpha(opacity = "+100*d+")",
$zoom:1}:{$opacity:d}:{$height:/px/.test(b)?b:function(a,b,c){return d*(d&&X(y(c)))+"px"},$overflow:"hidden"}):r(c,function(c,d){var h=k(k(a,/^%/,"data-"),/^[@$]/),e=c.className||"",m=/^\$/.test(a)?c.style:c,g=p(b)?b(y(c).get(a),d,c):b;"$"==a?null!=g&&(r(g.split(/\s+/),function(a){var b=k(a,/^[+-]/),c=e;e=k(e,RegExp("\\b"+b+"\\b","i"));if(/^\+/.test(a)||b==a&&c==e)e+=" "+b}),c.className=k(e,/^\s+|\s+(?=\s|$)/g)):"$$"==a?F?m.cssText=g:null!=g?c.setAttribute("style",g):c.removeAttribute("style"):/^[@%]/.test(a)?
null!=g?m.setAttribute(h,g):m.removeAttribute(h):m[h]=g}):n(a)||p(a)?c.set("$",a):u(a,function(a,b){c.set(a,b)});return c},add:function(a,b){return this.each(function(c,d){var f;(function v(a){l(a)?r(a,v):p(a)?v(a(c,d)):null!=a&&(a=g(a)?a:E.createTextNode(a),f?f.parentNode.insertBefore(a,f.nextSibling):b?b(a,c,c.parentNode):c.appendChild(a),f=a)})(g(a)&&d?null:a)})},fill:function(a){return this.each(function(a){y(a.childNodes).remove()}).add(a)},addBefore:function(a){return this.add(a,function(a,
c,d){d.insertBefore(a,c)})},addAfter:function(a){return this.add(a,function(a,c,d){d.insertBefore(a,c.nextSibling)})},addFront:function(a){return this.add(a,function(a,c){c.insertBefore(a,c.firstChild)})},replace:function(a){return this.add(a,function(a,c,d){d.replaceChild(a,c)})},clone:function(a){return this.collect(function(b){var c=g(b);if(1==c){var d={$:b.className||null,$$:F?b.style.cssText:b.getAttribute("style")};r(b.attributes,function(a){var c=a.name;"id"!=c&&("style"!=c&&"class"!=c&&b.getAttribute(c))&&
(d["@"+c]=a.value)});return Z(b.tagName,d,y(b.childNodes).clone(),a)}return 5>c?b.data:null})},animate:function(a,b,c,d){var f=this,h=[],m=/-?[\d.]+/,g,j=I(),l=p(c)?c:function(a,b,d){return a+d*(b-a)*(c+(1-c)*d*(3-2*d))};d=d||{};d.time=0;d.stop=function(){g();j(!1)};b=b||500;c=c||0;r(f,function(b){var c={o:y(b),e:{}};u(c.s=c.o.get(a),function(b,d){var f=a[b];"$$slide"==b&&(f=f*X(c.o)+"px");c.e[b]=/^[+-]=/.test(f)?k(f.substr(2),m,x(d)+x(k(f,/\+?=/))):f});h.push(c)});g=y.loop(function(a){function c(a,
b){return/^#/.test(a)?parseInt(6<a.length?a.substr(1+2*b,2):(a=a.charAt(1+b))+a,16):parseInt(k(a,/[^\d,]+/g).split(",")[b])}d.time=a;a>=b||0>a?(r(h,function(a){a.o.set(a.e)}),g(),d.time=null,j(!0,[f])):r(h,function(d){u(d.s,function(f,h){var g="rgb(",j=d.e[f],n=a/b;if(/^#|rgb\(/.test(j))for(var p=0;3>p;p++)g+=Math.round(l(c(h,p),c(j,p),n))+(2>p?",":")");else g=k(j,m,e(l(x(h),x(j),n)));d.o.set(f,g)})})});return j},toggle:function(a,b,c,d){var f=this,h={},e=!1,g=/\b(?=\w)/g,m;return b?f.set(a)&&function(g){if(g!==
e)return m=(e=!0===g||!1===g?g:!e)?b:a,p(m)?m(f,c,d):c?f.animate(m,h.stop?h.stop()||h.time:c,d,h):f.set(m)&&void 0}:f.toggle(k(a,g,"-"),k(a,g,"+"))},values:function(a){var b=a||{};this.each(function(a){var d=a.name,f=e(a.value),g=b[d];if(/form/i.test(a.tagName))y(h(r,a.elements,t)).values(b);else if(d&&(!/kbox|dio/i.test(a.type)||a.checked))l(g)?g.push(f):b[d]=null==g?f:[g,f]});return b},offset:function(){for(var a=this[0],b={x:0,y:0};a;)b.x+=a.offsetLeft,b.y+=a.offsetTop,a=a.offsetParent;return b},
on:function(a,b,c,d){return this.each(function(f,h){r(a.split(/\s/),function(a){var g=k(a,/\|/),e=p(b)||null,m=e?b:c,l=e&&d&&c,n=e&&(d||c),r=g==a,u=e?j:O(b,f),e=function(a,b){var c=a||z.event,d,f=b||c.target;if(u(f)&&(d=(!m.apply(l||f,n||[c,h])||n)&&r)&&!b)c.stopPropagation&&(c.preventDefault(),c.stopPropagation()),c.returnValue=!1,c.cancelBubble=!0;return d};a={e:f,h:e,n:g};(m.M=m.M||[]).push(a);F?(f.attachEvent("on"+g,e),g=A(f),(J[g]=J[g]||[]).push(a)):(f.addEventListener(g,e,!1),(f.minified2=f.minified2||
[]).push(a))})})},onOver:function(a){var b=this,c=[];return b.on("|mouseover |mouseout",function(d,f){var h="mouseout"!=d.type,g=d.relatedTarget||d.toElement;if(c[f]!==h&&(h||!g||g!=b[f]&&!y(g).trav("parentNode",b[f]).length))c[f]=h,a.call(this,h,f)})},trigger:function(a,b){return this.each(function(c){for(var d,f=c;f&&!d;)r(F?J[f.minified]:f.minified2,function(f){f.n==a&&(d=d||f.h(b,c))}),f=f.parentNode})}},function(a,b){M.prototype[a]=b});u({request:function(a,b,c,d,f,m){var k,j=c,l=0,p=I();try{k=
z.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Msxml2.XMLHTTP.3.0"),null!=c&&(d=d||{},!n(c)&&!g(c)&&(j=h(u,c,function(a,b){return h(r,b,function(b){return encodeURIComponent(a)+(null!=b?"="+encodeURIComponent(b):"")})}).join("&")),/post/i.test(a)?!g(c)&&(!n(c)&&!d["Content-Type"])&&(d["Content-Type"]="application/x-www-form-urlencoded"):(b+="?"+j,j=null)),k.open(a,b,!0,f,m),u(d,function(a,b){k.setRequestHeader(a,b)}),k.onreadystatechange=function(){4==k.readyState&&!l++&&(200==k.status?p(!0,
[k.responseText,k.responseXML]):p(!1,[k.status,k.statusText,k.responseText]))},k.send(j)}catch(w){l||p(!1,[0,null,e(w)])}return p},toJSON:function b(c){return null==c?""+c:n(c=c.valueOf())?'"'+k(c,/[\\\"\x00-\x1f\x22\x5c]/g,aa)+'"':l(c)?"["+h(r,c,b).join()+"]":"object"==typeof c?"{"+h(u,c,function(c,f){return b(c)+":"+b(f)}).join()+"}":e(c)},parseJSON:z.JSON?z.JSON.parse:function(b){b=k(b,/[\x00\xad\u0600-\uffff]/g,aa);if(/^[[\],:{}\s]*$/.test(k(k(b,/\\["\\\/bfnrtu]/g),/"[^"\\\n\r]*"|true|false|null|[\d.eE+-]+/g)))return eval("("+
b+")")},ready:V,setCookie:function(b,c,d,f,h,g){E.cookie=b+"="+(g?c:escape(c))+(d?"; expires="+("object"==typeof d?d:new Date((new Date).getTime()+864E5*d)).toUTCString():"")+"; path="+(f?escapeURI(f):"/")+(h?"; domain="+escape(h):"")},getCookie:function(b,c){var d,f=(d=RegExp("(^|;)\\s*"+b+"=([^;]*)").exec(E.cookie))&&d[2];return c?f:f&&unescape(f)},loop:function(b){var c={c:b,t:(new Date).getTime(),s:function(){G(S,c)}};2>S.push(c)&&function f(){r(S,function(b){b.c(Math.max(0,(new Date).getTime()-
b.t),b.s)}).length&&ba(f)}();return c.s},off:function(b){r(b.M,function(b){F?(b.e.detachEvent("on"+b.n,b.h),G(J[b.e.minified],b)):(b.e.removeEventListener(b.n,b.h,!1),G(b.e.minified2,b))});b.M=null}},function(b,c){y[b]=c});z.onload=B;E.addEventListener&&E.addEventListener("DOMContentLoaded",B,!1);z.unload=function(){r(J,Y)};return{$:y,$$:function(b){return D(b)[0]},EE:Z,M:M}});var _=(require("minifiedUtil")||require("minified"))._;
function parseSourceSections(j){function e(){return{id:"anon"+n++,src:[],desc:"",requires:{},requiredBy:{},syntax:[],example:[],params:[]}}j=j.split("\n");var n=100,g=[],l=e(),t=!1;_.each(j,function(j){if(t&&/^.*\*\/\s*$/.test(j))t=!1;else if(t){var m=j.replace(/^\s*(\*\s?)?/,"").replace(/\s*$/,""),h=m.match(/^\s*@([a-z]+)/);h?(h=h[1],m=_.trim(m.replace(/^\s*@[a-z]+\s*/,"")),"syntax"==h||"example"==h?l[h].push(m):"requires"==h?m.length&&_.each(m.split(/\s+/),function(h){l.requires[h]=1}):"param"==
h?l.params.push({name:m.replace(/\s.*$/,""),desc:m.replace(/^\S+\s+/,"")}):"return"==h?l.params.push({name:"@return",desc:m}):"function"==h?l.params[l.params.length-1].funcs.push(m):l[h]=""!=m?m:1):l.params.length?l.params[l.params.length-1].desc+="\n"+_.trim(m):l.example.length?l.example[l.example.length-1]+="\n"+m:l.desc+=m+"\n"}else/^\s*\/\*\$/.test(j)&&!/\*\/\s*$/.test(j)&&(t=!0,g.push(l),l=e());l.src.push(j)});g.push(l);return g}
function createSectionMap(j){var e={};_.each(j,function(j){e[j.id]=j});return e}function completeRequirements(j,e){var n=0;_.each(j,function(g){_.eachObj(g.requires,function(j){var t=e[j];if(!t)throw Error('Unknown id in requirement: "'+j+'"');_.eachObj(t.requires,function(e){g.requires[e]||(n++,g.requires[e]=1)})})});0<n?completeRequirements(j,e):_.each(j,function(g){_.eachObj(g.requires,function(j){e[j].requiredBy[g.id]=1})})}
function calculateDependencies(j,e){var n={};_.eachObj(e,function(g){e[g]&&(n[g]=1,_.eachObj(j[g].requires,function(g){n[g]=1}))});return n}function createDefaultConfigurationMap(j,e){var n={};_.each(j,function(g){if(g.configurable&&("default"==g.configurable||e))n[g.id]=1});return n}
function compile(j,e,n){var g="",l=calculateDependencies(e,n),t=[],u=!0;_.filter(j,function(g){return l[g.id]||!(g.configurable||g.dependency)}).each(function(e){_.each(e.src,function(h){if(/^\s*$/.test(h))u||(g+="\n"),u=!0;else{var e=h.match(/^(\s*)\/\/\s*@(cond|condblock)\s+(\!?)(\w*)\s*(.*)$/);if(e&&"cond"==e[2]&&!!l[e[4]]!=("!"==e[3]))g+=e[1]+e[5]+"\n";else{var j=!1,m=!0;e&&"condblock"==e[2]?t.push(!!l[e[4]]!=("!"==e[3])):/^\s*\/\/\s*@condend\b/.test(h)&&(j=!0);for(e=0;e<t.length;e++)if(!t[e]){m=
!1;break}m&&(g+=h+"\n");j&&t.pop()}u=!1}})});return g}function prepareSections(j){j=parseSourceSections(j);var e=createSectionMap(j);completeRequirements(j,e);var n=createDefaultConfigurationMap(j);return{sections:j,sectionMap:e,enabledSections:n}}var CONFIG_START="minified.js config start --",CONFIG_COMMENT="// - ",CONFIG_ALL="All sections.",CONFIG_ALL_EXCEPT="All sections except ",CONFIG_ONLY="Only sections ";
function serializeEnabledSections(j,e){var n=_.filter(j,function(h){return h.configurable}),g=_.filter(_.keys(e),function(h){return e[h]}),l,t=[];g.length==n.length?(l=CONFIG_COMMENT+CONFIG_ALL,t=[]):g.length/3>n.length/2?(l=CONFIG_COMMENT+CONFIG_ALL_EXCEPT,t=_.filter(n,function(h){return!e[h.id]}).collect(function(h){return h.id})):(l=CONFIG_COMMENT+CONFIG_ONLY,t=g);var u="// "+CONFIG_START+" use this comment to re-create configuration in the Builder\n"+l,m=50;_(t).sort().each(function(h){m<h.length?
(m=70,u+="\n// - "+h+", "):(u+=h+", ",m-=h.length+2)});return u=u.replace(/,\s*$/,".\n")}function fixConfig(j,e){_.eachObj(e,function(n){j[n]?_.copyObj(j[n].requires,e):delete e[n]});return e}
function deserializeEnabledSections(j,e,n){function g(h){return RegExp("^"+h.replace(/ /g,"\\s+"))}var l=g(CONFIG_START+".*"),t=g(CONFIG_ALL.replace(/\./,"\\.")),u=g(CONFIG_ALL_EXCEPT+"\\s*"),m=g(CONFIG_ONLY+"\\s*"),h=g(CONFIG_COMMENT);n=n.split("\n");for(var k=0;k<n.length;k++){var w=n[k];if(/^\s*\/\/s*/.test(w)&&(w=w.replace(/^\s*\/\/\s*/,""),l.test(w)&&k+1<n.length)){for(var w="",p=k+1;p<n.length;p++)if(h.test(n[p])){if(w+=n[p].replace(h,""),/\s*\.\s*$/.test(n[p]))break}else break;if(t.test(w))return createDefaultConfigurationMap(j,
!0);w=w.replace(/\s*\.\s*$/,"");if(u.test(w)){var r=createDefaultConfigurationMap(j,!0);_.each(w.replace(u,"").split(/\s*,\s*/),function(h){delete r[h]});return fixConfig(e,r)}if(m.test(w))return r={},_.each(w.replace(m,"").split(/\s*,\s*/),function(h){e[h]&&(r[h]=1)}),fixConfig(e,r)}}return null};var MINI=require("minified"),$=MINI.$,$$=MINI.$$,EE=MINI.EE,_=require("minifiedUtil")._,MAX_SIZE=4095,SRC="/download/minified-web-src.js",GROUPS="INTERNAL SELECTORS ELEMENT REQUEST JSON EVENTS COOKIE ANIMATION OPTIONS".split(" ");
function closureCompile(j,e,n){$.request("post","http://closure-compiler.appspot.com/compile",{js_code:j,output_format:"json",output_info:["compiled_code","statistics"],output_file_name:"minified-custom.js",compilation_level:e?"ADVANCED_OPTIMIZATIONS":"SIMPLE_OPTIMIZATIONS"}).then(function(e){n&&n($.parseJSON(e))},function(e,j,t){window.console&&console.log("error",e,j,t);n&&n(null)}).error(function(e){window.console&&console.log(e)})}
function setUpConfigurationUI(j){function e(){$(".modCheck").each(function(e){var h=0;$(".secCheck",e.parentNode.parentNode).each(function(e){e.checked&&h++});e.checked=0<h})}function n(e){var h=j.sectionMap[e.id.substr(4)];e.checked?_.eachObj(h.requires,function(e){$("#sec-"+e).set("checked",!0)}):_.eachObj(h.requiredBy,function(e){$("#sec-"+e).set("checked",!1)})}$("#compile").on("click",function(){var e={};$(".secCheck").each(function(h){h.checked&&(e[h.id.substr(4)]=1)});var h=compile(j.sections,
j.sectionMap,e),g=serializeEnabledSections(j.sections,e);if($$("#compressionAdvanced").checked)$$("#compile").disabled=!0,closureCompile(h,!0,function(e){$$("#compile").disabled=!1;$("#resultDiv").animate({$$slide:1});e?($("#gzipRow, #downloadRow").set({$display:"table-row"}),$$("#resultSrc").value=g+"\n"+e.compiledCode,$("#resultPlain").fill((e.statistics.compressedSize/1024).toFixed(2)+"kb ("+e.statistics.compressedSize+" bytes)"),$("#resultGzippedSize").fill((e.statistics.compressedGzipSize/1024).toFixed(2)+
"kb ("+e.statistics.compressedGzipSize+" bytes)"),$$("#resultLink").setAttribute("href","http://closure-compiler.appspot.com"+e.outputFilePath),$("#resultGzippedComment").set({$$fade:e.statistics.compressedGzipSize>MAX_SIZE?1:0})):alert("Google Closure Service not availble. Try again later.")});else try{$("#resultDiv").animate({$$slide:1}),$$("#resultSrc").value=g+h,$("#resultPlain").fill((h.length/1024).toFixed(2)+"kb"),$("#gzipRow, #downloadRow").set({$display:"none"})}catch(l){console.log(l)}return!1});
var g=$("#configSrcDiv").toggle({$$slide:0},{$$slide:1});$("#fromScratch").on("|click",g,[!1]);$("#loadConfig").on("|click",g,[!0]);$("#recreate").on("click",function(){try{var g=$$("#configSrc").value,h=deserializeEnabledSections(j.sections,j.sectionMap,g);h?(_.eachObj(j.sectionMap,function(e){var g=$$("#sec-"+e);g&&(g.checked=!!h[e])}),e()):alert("Can not find configuration in source.")}catch(k){console.log(k)}});$("#sectionCheckboxes").fill();for(var l=1;l<GROUPS.length;l++){var t;$("#sectionCheckboxes").add(t=
EE("div",{"@id":"divMod-"+l},EE("div",{className:"groupDescriptor"},[g=EE("input",{"@id":"mod-"+l,className:"modCheck","@type":"checkbox",checked:"checked"})(),EE("label",{"@for":"mod-"+l},GROUPS[l])]))());$(g).on("change",function(){var g=this.checked;$(".secCheck",this.parentNode.parentNode).each(function(e){e.checked=g;n(e)});e();return!0});var u;_.filter(j.sections,function(e){return e.group==GROUPS[l]&&e.configurable}).sort(function(e,h){var g=e.name||e.id,j=h.name||h.id;return g==j?0:g>j?1:
-1}).each(function(g){function h(e,h){var g=_.filter(_.keys(h),function(e){return!!h[e].name});if(!g.length)return null;var k=0,l=e;_.each(g,function(e){k++<Math.min(g.length,8)&&(1<k&&(l=k==Math.min(g.length,8)?l+" and ":l+", "),l=8==k&&8<g.length?l+"more":l+(j.sectionMap[e].name||j.sectionMap[e].id))});return l+="."}var k=h("Required by ",g.requiredBy),l=h("Requires ",g.requires);t.add(EE("div",{className:"sectionDescriptor"},[u=EE("input",{className:"secCheck","@type":"checkbox","@id":"sec-"+g.id,
checked:"default"==g.configurable?"checked":null})(),EE("label",{"@for":"sec-"+g.id},g.name||g.id),EE("div",{className:"requirements"},[k?[k,EE("br")]:null,l])]));$(u).on("change",function(){n(this);e();return!0})})}}
$(function(){var j=/MSIE\s([\d.]+)/i.exec(navigator.userAgent);j&&10>parseInt(j[1])?$("#builderDiv").fill("Sorry, the Builder tool requires at least Internet Explorer 10 (or, alternatively, Chrome or Firefox). Earlier versions lack CORS support required to use Google Closure's web service."):$.request("get",SRC,null).then(function(e){setUpConfigurationUI(prepareSections(e))}).error(function(e){window.console&&console.log(e)})});
