function hhToString(a){return null!=a?""+a:""}function hhTrim(a){return hhToString(a).replace(/^\s+|\s+$/,"")}function hhIsType(a,c){return typeof a==c}function hhIsString(a){return hhIsType(a,"string")}function hhIsFunction(a){return hhIsType(a,"function")}function hhIsObject(a){return hhIsType(a,"object")}function hhIsList(a){return a&&null!=a.length&&!hhIsString(a)&&!hhIsFunction(a)}
function hhEach(a,c){if(hhIsList(a))for(var d=0;d<a.length;d++)c(a[d],d);else for(d in a)a.hasOwnProperty(d)&&c(d,a[d]);return a}function hhFilter(a,c){var d=[];hhEach(a,function(a,f){(!c||c(a,f))&&d.push(a)});return d}function hhFilterMap(a,c){hhEach(list,function(d,h){if(!c||c(d,h))a[d]=h});return{}}function hhCollect(a,c,d){d=d||[];hhEach(a,function(a,f){hhIsList(a=c(a,f))?each(a,function(a){d.push(a)}):null!=a&&d.push(a)});return d}
function hhCopy(a,c){hhEach(a,function(a,h){c[a]=h});return c}function hhKeys(a){return hhCollect(a,function(a){return a})}function hhToList(a){return hhIsList(a)?a:[a]}function hhDefer(a){"undefined"!=typeof process&&process.nextTick?process.nextTick(a):window.setTimeout(a,0)}function hhCall(a,c,d){hhEach(hhToList(a),function(a){a.apply(d,hhToList(c))})}
function hhPromise(){function a(a,c){null==d&&(d=a,h=hhToList(c),hhDefer(function(){hhCall(f)}))}function c(a,c){var e=hhPromise(),g=function(){try{var g=d?a:c;if(hhIsFunction(g)){var f=g.apply(null,h);f&&hhIsFunction(f.then)?f.then(function(a){e.s(!0,[a])},function(a){e.s(!1,[a])}):e.s(!0,[f])}else e.s(d,h)}catch(p){e.s(!1,[p])}};null!=d?hhDefer(g):f.push(g);return e}var d,h=[],f=[];return{then:c,s:a,set:a,always:function(a){return c(a,a)},error:function(a){return c(0,a)},join:function(){var c=arguments,
d=0,e=Array(c.length),g=!1;hhEach(c,function(c,f){c.then(function(c){e[f]=c;++d==e.length&&!g&&a(!0,[e])},function(){e[f]=v;a(!1,[f,e]);g=!0})})}}}function hhTemplate(a,c){var d=a;hhEach(c,function(a,c){d=d.replace(RegExp(a,"g"),c.replace(/(\$)/g,"$1$1"))});return d};var j=!0,s=null,t=!1;
(function(a,c){function d(b){return b!=s?""+b:""}function h(b){return"string"==typeof b}function f(b){return"function"==typeof b}function m(b){return b&&b.length!=s&&!h(b)&&!b.nodeType&&!f(b)}function l(b,A){if(m(b))for(var a=0;a<b.length;a++)A(b[a],a);else for(a in b)b.hasOwnProperty(a)&&A(a,b[a]);return b}function e(b,a){var k=[];l(b,function(b,c){(!a||a(b,c))&&k.push(b)});return k}function g(b,a,k){k=k||[];l(b,function(b,c){m(b=a(b,c))?l(b,function(b){k.push(b)}):b!=s&&k.push(b)});return k}function n(b,
a,k){return d(b).replace(a,k||"")}function q(b,A){var k=a.setTimeout(A,b||0);return function(){b&&a.clearTimeout(k)}}function p(b){return parseFloat(n(b,/^[^\d-]/))}function I(b){var a={o:"absolute",g:"hidden",d:"block",f:s},k=b.get(a);b.set(a);a=b[0].offsetHeight;b.set(k);return a}function z(b){b()}function J(){l(E,z);E=s}function u(b){E?E.push(b):q(0,b)}function H(){function b(b,e){a==s&&(a=b,k=e,q(0,function(){l(c,z)}))}var a,k=[],c=[],e=b.then=function(b,e){function d(){try{var c=a?b:e;if(f(c)){var x=
c.apply(s,k);x&&f(x.then)?x.then(function(b){g(j,[b])},function(b){g(t,[b])}):g(j,[x])}else g(a,k)}catch(n){g(t,[n])}}var g=H();a!=s?q(0,d):c.push(d);return g};b.always=function(b){return e(b,b)};b.error=function(b){return e(0,b)};return b}function K(b){return P[b]||"\\u"+("0000"+b.charCodeAt(0).toString(16)).slice(-4)}function r(b,a,k){return f(b)?u(b):new G(B(b,a,k))}function B(b,a,k){function d(b){return m(b)?g(b,d):b}function f(b){b=d(b);return!y?b:e(b,function(b){for(;b=b.parentNode;){if(b===
y)return j;if(k)return t}})}var y,l,C,q,w;if(a&&1!=(a=B(a)).length)return g(a,function(a){return B(b,a)});y=a&&a[0];if(!h(b))return f(m(b)?b:[b]);if(1<(a=b.split(/\s*,\s*/)).length)return g(a,function(b){return B(b,y)});if(a=/(\S+)\s+(.+)$/.exec(b))return B(a[2],B(a[1],y));if(b!=(a=n(b,/^#/)))return f([c.getElementById(a)]);y=y||c;l=(a=/([^.]*)\.?([^.]*)/.exec(b))[1];q=a[2];a=(C=y.getElementsByClassName&&q)?y.getElementsByClassName(q):y.getElementsByTagName(l||"*");if(l=C?l:q)w=RegExp(D+l+D,"i"),
a=e(a,function(b){return w.test(b[C?"nodeName":"className"])});return k?f(a):a}function G(b){for(var a=0;a<b.length;a++)this[a]=b[a];this.length=b.length;this.raw=b}var D="\\b",E=[],F=[],Q=g(["msR","webkitR","mozR","r"],function(b){return a[b+"equestAnimationFrame"]})[0]||function(b){q(33,b)},L=!!c.all&&!E.map,P={"\t":"\\t","\r":"\\r","\n":"\\n",'"':'\\"',"\\":"\\\\"};l({each:function(b){l(this.raw,b);return this},filter:function(b){return new G(e(this.raw,b))},collect:function(b,a){return new G(g(this.raw,
b,a))},sub:function(b,a){var k=this.length,c=0>b?k+b:b,e=a==s?k:0<=a?a:k+a;return this.filter(function(b,a){return a>=c&&a<e})},find:function(b){for(var a=f(b)?b:function(a,k){if(b===a)return k},k,c=0;c<this.length;c++)if((k=a(this[c],c))!=s)return k},hasClass:function(b){var a=RegExp(D+b+D);return this.find(function(b){return a.test(b.className)?b:s})},remove:function(){this.each(function(b){b.parentNode.removeChild(b)})},get:function(b,c){var k=this,e=k[0];if(e){if(h(b)){var g=n(b,/^[$@]/),d,f=
/\$\$/.test(b)&&("hidden"==k.get("$visibility")||"none"==k.get("$display"));d="$"==b?e.className:"$$fade"==b?isNaN(d=f?0:L?p(k.get("$filter"))/100:p(k.get("$opacity")))?1:d:"$$slide"==b?(f?0:e.offsetHeight)+"px":/^\$/.test(b)?a.getComputedStyle?a.getComputedStyle(e,s).getPropertyValue(n(g,/[A-Z]/g,function(b){return"-"+b.toLowerCase()})):e.currentStyle[g]:/^@/.test(b)?e.getAttribute(g):e[g];return c?p(d):d}var C={};l(b,function(b){C[b]=k.get(b)});return C}},set:function(b,a,k){var c=this,e;void 0!==
a?"$$fade"==b||"$$slide"==b?c.set({g:0<(e=p(a))?"visible":"hidden",d:"block"}).set("$$fade"==b?L?{k:"alpha(opacity = "+100*e+")",p:1}:{l:e}:{f:/px$/.test(a)?a:function(a,b,k){return e*(e&&I($(k)))+"px"},m:"hidden"}):c.each(function(c,e){var d=f(a)?a:k,g=n(b,/^[@$]/),h=c.className||"",x=/^\$/.test(b)?c.style:c,d=d?d(r(c).get(b),e,c,a):a;"$"==b?(l(d.split(/\s+/),function(a){var b=n(a,/^[+-]/),k=h;h=n(h,RegExp(D+b+D));if(/^\+/.test(a)||b==a&&k==h)h+=" "+b}),c.className=n(h,/^\s+|\s+(?=\s|$)/g)):/^@/.test(b)?
d!=s&&x.setAttribute(g,d):x[g]=d}):h(b)||f(b)?c.set("$",b):l(b,function(a,b){c.set(a,b,k)});return c},append:function(a,c){return this.set(a,c,function(a,b,c,e){return d(a)+e})},prepend:function(a,c){return this.set(a,c,function(a,b,c,e){return e+d(a)})},add:function(a,e){return this.each(function(k,d){var g;(function N(a){m(a)?l(a,N):a!=s&&(a=a.nodeType?a:c.createTextNode(a),g?g.parentNode.insertBefore(a,g.nextSibling):e?e(a,k,k.parentNode):k.appendChild(a),g=a)})(f(a)?a(k,d):(a==s||a.nodeType||
m(a))&&d?s:a)})},fill:function(a){return this.each(function(a){r(a.childNodes).remove()}).add(a)},addBefore:function(a){return this.add(a,function(a,b,c){c.insertBefore(a,b)})},addAfter:function(a){return this.add(a,function(a,b,c){c.insertBefore(a,b.nextSibling)})},addFront:function(a){return this.add(a,function(a,b){b.insertBefore(a,b.firstChild)})},replace:function(a){return this.add(a,function(a,b,c){c.replaceChild(a,b)})},animate:function(a,c,e,d,g){var f=this,h=[],m=/-?[\d.]+/,u,w,z=H();g=g||
{};g.time=0;g.stop=function(){u&&u();w&&w();z(t)};u=q(d,function(){c=c||500;e=e||0;f.each(function(c){var e={b:r(c),a:{},c:{}};l(e.a=e.b.get(a),function(c,k){var g=a[c];"$$slide"==c&&(g=g*I(e.b)+"px");e.c[c]=/^[+-]=/.test(g)?n(g.substr(2),m,p(k)+p(n(g,/\+?=/))):g});h.push(e)});w=r.loop(function(a,b){function d(a,b){return/^#/.test(a)?parseInt(6<a.length?a.substr(1+2*b,2):(a=a.charAt(1+b))+a,16):parseInt(n(a,/[^\d,]+/g).split(",")[b])}function x(b,g){return b+a/c*(g-b)*(e+(1-e)*a/c*(3-2*a/c))}g.time=
a;a>=c||0>a?(l(h,function(a){a.b.set(a.c)}),b(),g.time=g.stop=s,z(j,[f])):l(h,function(a){l(a.a,function(b,c){var e="rgb(",g=a.c[b];if(/^#|rgb\(/.test(g))for(var k=0;3>k;k++)e+=Math.round(x(d(c,k),d(g,k)))+(2>k?",":")");else e=n(g,m,x(p(c),p(g)));a.b.set(b,e)})})})});return z},toggle:function(a,c,e,g){var d={},f=t,h=/\b(?=\w)/g,l=this;return!c?l.toggle(n(a,h,"-"),n(a,h,"+")):l.set(a)&&function(h){h!==f&&(f="boolean"==typeof h?h:!f,e?l.q(f?c:a,d.stop?d.stop()||d.time:e,g,0,d):l.set(f?c:a))}},on:function(b,
c,e,g){return this.each(function(d,f){function h(b){b=b||a.event;if(!c.apply(g||b.target,e||[b,f])||e)b.stopPropagation&&(b.preventDefault(),b.stopPropagation()),b.returnValue=t,b.cancelBubble=j}(c.M=c.M||[]).push({e:d,h:h,n:b});d.addEventListener?d.addEventListener(b,h,j):d.attachEvent("on"+b,h)})},values:function(a){var c=a||{};this.each(function(a){var b=a.name,e=d(a.value),g=c[b];if(/form/i.test(a.tagName))r(a.elements).values(c);else if(b&&(!/kbox|dio/i.test(a.type)||a.checked))m(g)?g.push(e):
c[b]=g==s?e:[g,e]});return c},offset:function(){for(var a=this[0],c={x:0,y:0};a;)c.x+=a.offsetLeft,c.y+=a.offsetTop,a=a.offsetParent;return c}},function(a,c){G.prototype[a]=c});l({$$:function(a){return B(a)[0]},el:function(a,e,g){var d=c.documentElement.namespaceURI;a=r(d?c.createElementNS(d,a):c.createElement(a));return m(e)||"object"!=typeof e?a.add(e):a.set(e).add(g)},request:function(b,c,e,f,n,q){var p,u=e,z=0,w=H();try{return p=a.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Msxml2.XMLHTTP.3.0"),
e!=s&&(f=f||{},!h(e)&&!e.nodeType&&(u=g(e,function O(a,b){return m(b)?g(b,function(b){return O(a,b)}):encodeURIComponent(a)+(b!=s?"="+encodeURIComponent(b):"")}).join("&")),/post/i.test(b)?!e.nodeType&&!h(e)&&!f["Content-Type"]&&(f["Content-Type"]="application/x-www-form-urlencoded"):(c+="?"+u,u=s)),p.open(b,c,j,n,q),l(f,function(a,b){p.setRequestHeader(a,b)}),p.onreadystatechange=function(){4==p.readyState&&!z++&&(200==p.status?w(j,[p.responseText,p.responseXML]):w(t,[p.status,p.statusText,p.responseText]))},
p.send(u),w}catch(r){z||w(t,[0,s,d(r)])}},toJSON:function A(a){return a==s?""+a:h(a=a.valueOf())?'"'+n(a,/[\\\"\x00-\x1f\x22\x5c]/g,K)+'"':m(a)?"["+g(a,A).join()+"]":"object"==typeof a?"{"+g(a,function(a,c){return A(a)+":"+A(c)}).join()+"}":d(a)},parseJSON:a.JSON?a.JSON.parse:function(a){a=n(a,/[\x00\xad\u0600-\uffff]/g,K);if(/^[[\],:{}\s]*$/.test(n(n(a,/\\["\\\/bfnrtu]/g),/"[^"\\\n\r]*"|true|false|null|[\d.eE+-]+/g)))return eval("("+a+")")},ready:u,setCookie:function(a,e,g,d,f,h){c.cookie=a+"="+
(h?e:escape(e))+(g?"; expires="+("object"==typeof g?g:new Date((new Date).getTime()+864E5*g)).toUTCString():"")+"; path="+(d?escapeURI(d):"/")+(f?"; domain="+escape(f):"")},getCookie:function(a,e){var g,d=(g=RegExp("(^|;)\\s*"+a+"=([^;]*)").exec(c.cookie))&&g[2];return e?d:d&&unescape(d)},loop:function(a){var c={i:a,j:(new Date).getTime(),a:function(){for(var a=0;a<F.length;a++)F[a]===c&&F.splice(a--,1)}};2>F.push(c)&&function M(){l(F,function(a){a.i(Math.max(0,(new Date).getTime()-a.j),a.a)}).length&&
Q(M)}();return c.a},off:function(a){l(a.M,function(a){a.e.addEventListener?a.e.removeEventListener(a.n,a.h,j):a.e.detachEvent("on"+a.n,a.h)});a.M=s}},function(a,c){r[a]=c});a.onload=J;c.addEventListener&&c.addEventListener("DOMContentLoaded",J,t);a.$=a.MINI=r;a.$$=r.$$;a.EE=r.el})(window,document);function parseSourceSections(a){function c(){return{id:"anon"+d++,src:[],desc:"",requires:{},requiredBy:{},syntax:[],example:[],params:[]}}a=a.split("\n");var d=100,h=[],f=c(),m=!1;hhEach(a,function(a){if(m&&/^.*\*\/\s*$/.test(a))m=!1;else if(m){var e=a.replace(/^\s*(\*\s?)?/,"").replace(/\s*$/,""),g=e.match(/^\s*@([a-z]+)/);g?(g=g[1],e=hhTrim(e.replace(/^\s*@[a-z]+\s*/,"")),"syntax"==g||"example"==g?f[g].push(e):"requires"==g?e.length&&hhEach(e.split(/\s+/),function(a){f.requires[a]=1}):"param"==
g?f.params.push({name:e.replace(/\s.*$/,""),desc:e.replace(/^\S+\s+/,"")}):"return"==g?f.params.push({name:"@return",desc:e}):"function"==g?f.params[f.params.length-1].funcs.push(e):f[g]=""!=e?e:1):f.params.length?f.params[f.params.length-1].desc+="\n"+hhTrim(e):f.example.length?f.example[f.example.length-1]+="\n"+e:f.desc+=e+"\n"}else/^\s*\/\*\*/.test(a)&&!/\*\/\s*$/.test(a)&&(m=!0,h.push(f),f=c());f.src.push(a)});h.push(f);return h}
function createSectionMap(a){var c={};hhEach(a,function(a){c[a.id]=a});return c}function completeRequirements(a,c){var d=0;hhEach(a,function(a){hhEach(a.requires,function(f){var m=c[f];if(!m)throw Error('Unknown id in requirement: "'+f+'"');hhEach(m.requires,function(c){a.requires[c]||(d++,a.requires[c]=1)})})});0<d?completeRequirements(a,c):hhEach(a,function(a){hhEach(a.requires,function(d){c[d].requiredBy[a.id]=1})})}
function calculateDependencies(a,c){var d={};hhEach(c,function(h){c[h]&&(d[h]=1,hhEach(a[h].requires,function(a){d[a]=1}))});return d}function createDefaultConfigurationMap(a,c){var d={};hhEach(a,function(a){if(a.configurable&&("default"==a.configurable||c))d[a.id]=1});return d}
function compile(a,c,d){var h="",f=calculateDependencies(c,d),m=[],l=!0;hhEach(hhFilter(a,function(a){return f[a.id]||!(a.configurable||a.dependency)}),function(a){hhEach(a.src,function(a){if(/^\s*$/.test(a))l||(h+="\n"),l=!0;else{var c=a.match(/^(\s*)\/\/\s*@(cond|condblock)\s+(\!?)(\w*)\s*(.*)$/);if(c&&"cond"==c[2]&&!!f[c[4]]!=("!"==c[3]))h+=c[1]+c[5]+"\n";else if(c&&"condblock"==c[2])m.unshift(!!f[c[4]]!=("!"==c[3]));else if(m.length&&/^\s*\/\/\s*@condend(\s|$)/.test(a))m.shift();else if(0==m.length||
m[0])h+=a+"\n";l=!1}})});return h}function closureCompile(a,c){MINI.request("post","http://closure-compiler.appspot.com/compile",{js_code:a,output_format:"json",output_info:["compiled_code","statistics"],output_file_name:"minified-custom.js",compilation_level:"ADVANCED_OPTIMIZATIONS"}).then(function(a){c&&c(MINI.parseJSON(a))},function(a,h,f){window.console&&console.log("error",a,h,f);c&&c(null)})}
function prepareSections(a){a=parseSourceSections(a);var c=createSectionMap(a);completeRequirements(a,c);var d=createDefaultConfigurationMap(a);return{sections:a,sectionMap:c,enabledSections:d}}var CONFIG_START="minified.js config start --",CONFIG_COMMENT="// - ",CONFIG_ALL="All sections",CONFIG_ALL_EXCEPT="All sections except ",CONFIG_ONLY="Only sections ";
function serializeEnabledSections(a,c){var d=hhFilter(a,function(a){return a.configurable}),h=hhFilter(hhKeys(c),function(a){return c[a]}),f,m=[];h.length==d.length?(f=CONFIG_COMMENT+CONFIG_ALL,m=[]):h.length>d.length/2?(f=CONFIG_COMMENT+CONFIG_ALL_EXCEPT,m=hhCollect(hhFilter(d,function(a){return!c[a.id]}),function(a){return a.id})):(f=CONFIG_COMMENT+CONFIG_ONLY,m=h);var l="// "+CONFIG_START+" use this comment to re-create your build configuration\n"+f,e=50;hhEach(m.sort(),function(a){e<a.length?
(e=70,l+="\n// - "+a+", "):(l+=a+", ",e-=a.length+2)});return l=l.replace(/,\s*$/,".\n")}
function deserializeEnabledSections(a,c){for(var d=makeRegexp(CONFIG_START),h=makeRegexp(CONFIG_ALL+"\\s*\\."),f=makeRegexp(CONFIG_ALL_EXCEPT+"\\s*"),m=makeRegexp(CONFIG_ONLY+"\\s*"),l=makeRegexp(CONFIG_COMMENT),e=c.split("\n"),g=0;g<e.length;g++){var n=e[g];if(/^\s*\/\/s*/.test(n)&&(n=n.replace(/^\s*\/\/s*/,""),d.test(n)&&g+1<e.length)){for(var n="",q=g+1;q<e.length;q++)if(l.test(e[q])){if(n+=e[q].replace(l,""),/\s*\.\s*$/.test(e[q]))break}else break;if(h.test(n))return createDefaultConfigurationMap(a,
!0);n=n.replace(/\s*\.\s*$/,"");if(f.test(n)){var p=createDefaultConfigurationMap(a,!0);hhEach(n.replace(f,"").split(/\s*,\s*/),function(a){delete p[a]});return p}if(m.test(n))return p={},hhEach(n.replace(m,"").split(/\s*,\s*/),function(a){p[a]=1}),p}}return null};var SRC="minified-src.js",MODULES="INTERNAL SELECTORS ELEMENT REQUEST JSON EVENTS COOKIE ANIMATION SHORTCUTS OPTIONS".split(" ");
function setUpConfigurationUI(a){function c(){$(".modCheck").each(function(a){var c=0;$(".secCheck",a.parentNode.parentNode).each(function(a){a.checked&&c++});a.checked=0<c})}function d(c){var d=a.sectionMap[c.id.substr(4)];c.checked?hhEach(d.requires,function(a){$("#sec-"+a).set("checked",!0)}):hhEach(d.requiredBy,function(a){$("#sec-"+a).set("checked",!1)})}$("#compile").on("click",function(){var c={};$(".secCheck").each(function(a){a.checked&&(c[a.id.substr(4)]=1)});var d=compile(a.sections,a.sectionMap,
c),f=serializeEnabledSections(a.sections,c);$$("#compressionClosure").checked?($$("#compile").disabled=!0,closureCompile(d,function(a){a&&($$("#compile").disabled=!1,$("#gzipRow, #downloadRow").set({$display:"table-row"}),$$("#resultSrc").value=f+a.compiledCode,$$("#resultPlain").innerHTML=(a.statistics.compressedSize/1024).toFixed(2)+"kb ("+a.statistics.compressedSize+" bytes)",$$("#resultGzipped").innerHTML=(a.statistics.compressedGzipSize/1024).toFixed(2)+"kb ("+a.statistics.compressedGzipSize+
" bytes)",$$("#resultLink").setAttribute("href","http://closure-compiler.appspot.com"+a.outputFilePath))})):($$("#resultSrc").value=f+d,$$("#resultPlain").innerHTML=(d.length/1024).toFixed(2)+"kb",$("#gzipRow, #downloadRow").set({$display:"none"}));return!1});for(var h=1;h<MODULES.length;h++){var f,m;$("#sectionCheckboxes").add(m=$.el("div",{"@id":"divMod-"+h},$.el("div",{className:"moduleDescriptor"},[f=$.el("input",{"@id":"mod-"+h,className:"modCheck","@type":"checkbox",checked:"checked"}),$.el("label",
{"@for":"mod-"+h},MODULES[h])])));$(f).on("change",function(){var a=this.checked;$(".secCheck",this.parentNode.parentNode).each(function(c){c.checked=a;d(c)});c();return!0});var l;hhEach(hhFilter(a.sections,function(c){return c.module==MODULES[h]&&a.enabledSections[c.id]}).sort(function(a,c){var d=a.name||a.id,f=c.name||c.id;return d==f?0:d>f?1:-1}),function(e){function f(c,e){var d=hhFilter(hhKeys(e),function(c){return!!a.sectionMap[c].name});if(!d.length)return null;var g=0,h=c;hhEach(d,function(c){g++<
Math.min(d.length,8)&&(1<g&&(h=g==Math.min(d.length,8)?h+" and ":h+", "),h=8==g&&8<d.length?h+"more":h+(a.sectionMap[c].name||a.sectionMap[c].id))});return h+="."}var h=f("Required by ",e.requiredBy),q=f("Requires ",e.requires);m.add($.el("div",{className:"sectionDescriptor"},[l=$.el("input",{className:"secCheck","@type":"checkbox","@id":"sec-"+e.id,checked:"default"==e.configurable?"checked":null}),$.el("label",{"@for":"sec-"+e.id},e.name||e.id),$.el("div",{className:"requirements"},[h?[h,$.el("br")]:
null,q])]));$(l).on("change",function(){d(this);c();return!0})})}}$(function(){$.request("get",SRC,null).then(function(a){setUpConfigurationUI(prepareSections(a))})});
