(function(){function h(a){return"function"==typeof a&&!a.item}function m(a){return a&&null!=a.length&&"string"!=typeof a&&!(a&&a.nodeType)&&!h(a)}function v(a,b){for(var c in a)a.hasOwnProperty(c)&&b(c,a[c]);return a}function f(a,b){for(var c=0;a&&c<a.length;c++)b(a[c],c);return a}function B(a,b){var c=[];f(a,function(a,d){b(a,d)&&c.push(a)});return c}function p(a,b){var c=[];f(a,function(a,d){m(a=b(a,d))?f(a,function(a){c.push(a)}):null!=a&&c.push(a)});return c}function l(a,b,c){return(null!=a?""+
a:"").replace(b,c||"")}function q(a){return parseFloat(l(a,/^[^\d-]+/))}function r(a){var b={$position:"absolute",$visibility:"hidden",$display:"block",$height:null},c=a.get(b);a.set(b);b=a[0].offsetHeight;a.set(c);return b}function w(a){a()}function t(){f(C,w);C=null}function D(a){C?C.push(a):u.setTimeout(a,0)}function E(){var a,b=[],c=[],e=function(d,e){null==a&&(a=d,b=e,u.setTimeout(function(){f(c,w)},0))},d=e.then=function(d,e){var g=E(),f=function(){try{var c=a?d:e;if(h(c)){var f=c.apply(null,
b);f&&h(f.then)?f.then(function(a){g(!0,[a])},function(a){g(!1,[a])}):g(!0,[f])}else g(a,b)}catch(H){g(!1,[H])}};null!=a?u.setTimeout(f,0):c.push(f);return g};e.always=function(a){return d(a,a)};e.error=function(a){return d(0,a)};return e}function x(a,b,c){return h(a)?D(a):new z(A(a,b,c))}function A(a,b,c){function e(a){a=function H(a){return m(a)?p(a,H):a}(a);return d?B(a,function(a){for(;a=a.parentNode;){if(a===d)return!0;if(c)return!1}}):a}var d,f,j,g,k;if(b&&1!=(b=A(b)).length)return p(b,function(b){return A(a,
b,c)});d=b&&b[0];if("string"!=typeof a)return e(m(a)?a:[a]);if(1<(b=a.split(/\s*,\s*/)).length)return p(b,function(a){return A(a,d,c)});if(b=/(\S+)\s+(.+)$/.exec(a))return A(b[2],A(b[1],d),c);if(a!=(b=l(a,/^#/)))return e([y.getElementById(b)]);d=d||y;f=(b=/([^.]*)\.?([^.]*)/.exec(a))[1];g=b[2];b=(j=d.getElementsByClassName&&g)?d.getElementsByClassName(g):d.getElementsByTagName(f||"*");if(f=j?f:g)k=RegExp("\\b"+f+"\\b","i"),b=B(b,function(a){return k.test(a[j?"nodeName":"className"])});return d?e(b):
b}function z(a){for(var b=this.length=a.length,c=0;c<b;c++)this[c]=a[c]}var u=this,y=document,C=[],F=[],I=p(["msR","webkitR","mozR","r"],function(a){return u[a+"equestAnimationFrame"]})[0]||function(a){u.setTimeout(a,33)},G=!!y.all&&!C.map;v({each:function(a){return f(this,a)},get:function(a,b){var c=this,e=c[0];if(e){if("string"==typeof a){var d=l(a,/^[$@]/),n;n="$"==a?e.className:"$$"==a?G?e.style.cssText:e.getAttribute("style"):/\$\$/.test(a)&&("hidden"==e.style.visibility||"none"==e.style.display)?
0:"$$fade"==a?isNaN(n=G?q(e.style.filter)/100:q(e.style.opacity))?1:n:"$$slide"==a?e.offsetHeight-c.get("$paddingTop",!0)-c.get("$paddingBottom",!0)+"px":/^\$/.test(a)?u.getComputedStyle?u.getComputedStyle(e,null).getPropertyValue(l(d,/[A-Z]/g,function(a){return"-"+a.toLowerCase()})):(e.currentStyle||e.style)[d]:/^@/.test(a)?e.getAttribute(d):e[d];return b?q(n):n}var j={};(m(a)?f:v)(a,function(a){j[a]=c.get(a,b)});return j}},set:function(a,b){var c=this,e;void 0!==b?"$$fade"==a||"$$slide"==a?c.set({$visibility:0<
(e=q(b))?"visible":"hidden",$display:"block"}).set("$$fade"==a?G?{$filter:"alpha(opacity = "+100*e+")",$zoom:1}:{$opacity:e}:{$height:/px$/.test(b)?b:function(a,b,c){return e*(e&&r(x(c)))+"px"},$overflow:"hidden"}):f(c,function(c,e){var j=l(a,/^[@$]/),g=c.className||"",k=/^\$/.test(a)?c.style:c,s=h(b)?b(x(c).get(a),e,c):b;"$"==a?null!=s&&(f(s.split(/\s+/),function(a){var b=l(a,/^[+-]/),c=g;g=l(g,RegExp("\\b"+b+"\\b"));if(/^\+/.test(a)||b==a&&c==g)g+=" "+b}),c.className=l(g,/^\s+|\s+(?=\s|$)/g)):"$$"==
a?G?k.cssText=s:null!=s?c.setAttribute("style",s):c.removeAttribute("style"):/^@/.test(a)?null!=s?k.setAttribute(j,s):k.removeAttribute(j):k[j]=s}):"string"==typeof a||h(a)?c.set("$",a):v(a,function(a,b){c.set(a,b)});return c},add:function(a,b){return f(this,function(c,e){var d;(function j(a){m(a)?f(a,j):h(a)?j(a(c,e)):null!=a&&(a=a&&a.nodeType?a:y.createTextNode(a),d?d.parentNode.insertBefore(a,d.nextSibling):b?b(a,c,c.parentNode):c.appendChild(a),d=a)})(a&&a.nodeType&&e?null:a)})},animate:function(a,
b,c,e){var d=this,n=[],j=/-?[\d.]+/,g,k=E(),s=h(c)?c:function(a,b,e){return a+e*(b-a)*(c+(1-c)*e*(3-2*e))};e=e||{};e.time=0;e.stop=function(){g();k(!1)};b=b||500;c=c||0;f(d,function(b){var c={o:x(b),e:{}};v(c.s=c.o.get(a),function(b,e){var d=a[b];"$$slide"==b&&(d=d*r(c.o)+"px");c.e[b]=/^[+-]=/.test(d)?l(d.substr(2),j,q(e)+q(l(d,/\+?=/))):d});n.push(c)});g=x.loop(function(a){function c(a,b){return/^#/.test(a)?parseInt(6<a.length?a.substr(1+2*b,2):(a=a.charAt(1+b))+a,16):parseInt(l(a,/[^\d,]+/g).split(",")[b])}
e.time=a;a>=b||0>a?(f(n,function(a){a.o.set(a.e)}),g(),e.time=null,k(!0,[d])):f(n,function(e){v(e.s,function(d,f){var g="rgb(",k=e.e[d],n=a/b;if(/^#|rgb\(/.test(k))for(var h=0;3>h;h++)g+=Math.round(s(c(f,h),c(k,h),n))+(2>h?",":")");else g=s(q(f),q(k),n),g=l(k,j,null!=g?""+g:"");e.o.set(d,g)})})});return k},toggle:function(a,b,c,e){var d=this,f={},j=!1,g=/\b(?=\w)/g;return!b?d.toggle(l(a,g,"-"),l(a,g,"+")):d.set(a)&&function(g){g!==j&&(j=!0===g||!1===g?g:!j,c?d.animate(j?b:a,f.stop?f.stop()||f.time:
c,e,f):d.set(j?b:a))}},on:function(a,b,c,e){return f(this,function(d,h){f(a.split(/\s/),function(a){var f=l(a,/\|/),k=function(d){d=d||u.event;if((!b.apply(e?c:d.target,e||c||[d,h])||e)&&a==f)d.stopPropagation&&(d.preventDefault(),d.stopPropagation()),d.returnValue=!1,d.cancelBubble=!0};(b.M=b.M||[]).push({e:d,h:k,n:f});d.addEventListener?d.addEventListener(f,k,!0):d.attachEvent("on"+f,k)})})}},function(a,b){z.prototype[a]=b});v({ready:D,loop:function(a){var b={c:a,t:(new Date).getTime(),s:function(){for(var a=
0;a<F.length;a++)F[a]===b&&F.splice(a--,1)}};2>F.push(b)&&function e(){f(F,function(a){a.c(Math.max(0,(new Date).getTime()-a.t),a.s)}).length&&I(e)}();return b.s},dummy:null},function(a,b){x[a]=b});u.onload=t;y.addEventListener&&y.addEventListener("DOMContentLoaded",t,!1);var J={$:x,EE:function(a,b,c,e){return function(){var d=x(y.createElement(a));m(b)||"object"!=typeof b?d.add(b):d.set(b).add(c);e&&e(d);return d}}};u.require=function(a){if("minified"==a)return J}})();var MINI=require("minified"),$=MINI.$,$$=MINI.$$,EE=MINI.EE;
$(function(){function h(){var f=Math.max(0,Math.min(Math.round(Math.random()*B-0.5),B));return f!=p?f:h()}function m(){D||($("#shareExt").add([EE("iframe",{"@allowtransparency":"true","@frameborder":0,"@scrolling":"no",$width:"100px",$height:"20px","@src":"http://ghbtns.com/github-btn.html?user=timjansen&repo=minified.js&type=watch&count=true"}),EE("iframe",{"@allowtransparency":"true","@frameborder":0,"@scrolling":"no",$width:"100px",$height:"20px","@src":"https://platform.twitter.com/widgets/tweet_button.html"}),
EE("div",{$:"g-plusone",$display:"inline","@data-size":"medium"})]),$("head").add(EE("script",{type:"text/javascript",async:!0,src:"https://apis.google.com/js/plusone.js"})),D=!0)}var v=["","-moz-","-ms-","-webkit-"],f="#f00 #0f0 #00f #0ff #f0f #ff0".split(" "),B=f.length,p=h(),l=h(),q=h(),r={percentage:0,preColor:f[p],postColor:f[q],running:!1},w=$(".shareButton"),t,D,E=$("#shareDiv").toggle({$$fade:0,$$slide:0},{$$fade:1,$$slide:1},700,1);w.on("mouseover",function(){m();t||(t=$.loop(function(m){r.running||
(r.running=!0,$(r).animate({percentage:100,preColor:f[l],postColor:f[p]},2E3,1).then(function(){r.percentage=0;r.running=!1;q=p;p=l;l=h()}));var t="linear-gradient("+Math.round(100*(10*(m/360)-75))/100+"deg, "+r.preColor+" 0%, "+f[p]+" "+Math.round(100*r.percentage)/100+"%, "+r.postColor+" 100%); ",z="";$(v).each(function(f){z+="background: "+f+t});w.set("$$",z)}))});w.on("mouseout",function(){t&&t();t=null;w.set("$$","")});w.on("click",function(){m();E()});"#share"==window.location.hash&&(m(),E(!0))});
