(function(){function h(a){return"function"==typeof a&&!a.item}function u(a){return a&&null!=a.length&&"string"!=typeof a&&!(a&&a.nodeType)&&!h(a)}function v(a,b){for(var d in a)a.hasOwnProperty(d)&&b(d,a[d]);return a}function f(a,b){for(var d=0;a&&d<a.length;d++)b(a[d],d);return a}function I(a,b){var d=[];f(a,function(a,c){b(a,c)&&d.push(a)});return d}function B(a,b){var d=[];f(a,function(a,c){u(a=b(a,c))?f(a,function(a){d.push(a)}):null!=a&&d.push(a)});return d}function l(a,b,d){return(null!=a?""+
a:"").replace(b,d||"")}function z(a,b){A.setTimeout(a,b||0)}function p(a){return parseFloat(l(a,/^[^\d-]+/))}function C(a){var b={$position:"absolute",$visibility:"hidden",$display:"block",$height:null},d=a.get(b);a.set(b);b=a[0].offsetHeight;a.set(d);return b}function F(a){a()}function q(){f(G,F);G=null}function w(a){G?G.push(a):z(a)}function x(){function a(a,c){null==b&&(b=a,d=c,z(function(){f(e,F)}))}var b,d=[],e=[],c=a.then=function(a,c){function g(){try{var e=b?a:c;if(h(e)){var g=e.apply(null,
d);g&&h(g.then)?g.then(function(a){k(!0,[a])},function(a){k(!1,[a])}):k(!0,[g])}else k(b,d)}catch(f){k(!1,[f])}}var k=x();null!=b?z(g):e.push(g);return k};a.always=function(a){return c(a,a)};a.error=function(a){return c(0,a)};return a}function s(a,b,d){return h(a)?w(a):new L(t(a,b,d))}function t(a,b,d){function e(a){a=function N(a){return u(a)?B(a,N):a}(a);return c?I(a,function(a){for(;a=a.parentNode;){if(a===c)return!0;if(d)return!1}}):a}var c,m,n,g,k;if(b&&1!=(b=t(b)).length)return B(b,function(b){return t(a,
b,d)});c=b&&b[0];if("string"!=typeof a)return e(u(a)?a:[a]);if(1<(b=a.split(/\s*,\s*/)).length)return B(b,function(a){return t(a,c,d)});if(b=/(\S+)\s+(.+)$/.exec(a))return t(b[2],t(b[1],c),d);if(a!=(b=l(a,/^#/)))return e([r.getElementById(b)]);c=c||r;m=(b=/([^.]*)\.?([^.]*)/.exec(a))[1];g=b[2];b=(n=c.getElementsByClassName&&g)?c.getElementsByClassName(g):c.getElementsByTagName(m||"*");if(m=n?m:g)k=RegExp("\\b"+m+"\\b","i"),b=I(b,function(a){return k.test(a[n?"nodeName":"className"])});return c?e(b):
b}function L(a){for(var b=this.length=a.length,d=0;d<b;d++)this[d]=a[d]}var A=this,r=document,G=[],H=[],O=B(["msR","webkitR","mozR","r"],function(a){return A[a+"equestAnimationFrame"]})[0]||function(a){z(a,33)},J=!!r.all&&!G.map;v({each:function(a){return f(this,a)},get:function(a,b){var d=this,e=d[0];if(e){if("string"==typeof a){var c=l(a,/^[$@]/),m;m="$"==a?e.className:"$$"==a?J?e.style.cssText:e.getAttribute("style"):!/\$\$/.test(a)||"hidden"!=e.style.visibility&&"none"!=e.style.display?"$$fade"==
a?isNaN(m=J?p(e.style.filter)/100:p(e.style.opacity))?1:m:"$$slide"==a?e.offsetHeight-d.get("$paddingTop",!0)-d.get("$paddingBottom",!0)+"px":/^\$/.test(a)?A.getComputedStyle?A.getComputedStyle(e,null).getPropertyValue(l(c,/[A-Z]/g,function(a){return"-"+a.toLowerCase()})):(e.currentStyle||e.style)[c]:/^@/.test(a)?e.getAttribute(c):e[c]:0;return b?p(m):m}var n={};(u(a)?f:v)(a,function(a){n[a]=d.get(a,b)});return n}},set:function(a,b){function d(a,b,d){null!=d?a.setAttribute(b,d):a.removeAttribute(b)}
var e=this,c;void 0!==b?"$$fade"==a||"$$slide"==a?e.set({$visibility:0<(c=p(b))?"visible":"hidden",$display:"block"}).set("$$fade"==a?J?{$filter:"alpha(opacity = "+100*c+")",$zoom:1}:{$opacity:c}:{$height:/px$/.test(b)?b:function(a,b,d){return c*(c&&C(s(d)))+"px"},$overflow:"hidden"}):f(e,function(c,e){var g=l(a,/^[@$]/),k=c.className||"",D=/^\$/.test(a)?c.style:c,E=h(b)?b(s(c).get(a),e,c):b;"$"==a?null!=E&&(f(E.split(/\s+/),function(a){var b=l(a,/^[+-]/),d=k;k=l(k,RegExp("\\b"+b+"\\b"));if(/^\+/.test(a)||
b==a&&d==k)k+=" "+b}),c.className=l(k,/^\s+|\s+(?=\s|$)/g)):"$$"==a?J?D.cssText=E:d(c,"style",E):/^@/.test(a)?d(D,g,E):D[g]=E}):"string"==typeof a||h(a)?e.set("$",a):v(a,function(a,b){e.set(a,b)});return e},add:function(a,b){return f(this,function(d,e){var c;(function n(a){u(a)?f(a,n):h(a)?n(a(d,e)):null!=a&&(a=a&&a.nodeType?a:r.createTextNode(a),c?c.parentNode.insertBefore(a,c.nextSibling):b?b(a,d,d.parentNode):d.appendChild(a),c=a)})(a&&a.nodeType&&e?null:a)})},animate:function(a,b,d,e){var c=this,
m=[],n=/-?[\d.]+/,g,k=x(),D=h(d)?d:function(a,b,c){return a+c*(b-a)*(d+(1-d)*c*(3-2*c))};e=e||{};e.time=0;e.stop=function(){g();k(!1)};b=b||500;d=d||0;f(c,function(b){var d={a:s(b),c:{}};v(d.b=d.a.get(a),function(b,c){var e=a[b];"$$slide"==b&&(e=e*C(d.a)+"px");d.c[b]=/^[+-]=/.test(e)?l(e.substr(2),n,p(c)+p(l(e,/\+?=/))):e});m.push(d)});g=s.loop(function(a){function d(a,b){return/^#/.test(a)?parseInt(6<a.length?a.substr(1+2*b,2):(a=a.charAt(1+b))+a,16):parseInt(l(a,/[^\d,]+/g).split(",")[b])}e.time=
a;a>=b||0>a?(f(m,function(a){a.a.set(a.c)}),g(),e.time=null,k(!0,[c])):f(m,function(c){v(c.b,function(e,k){var g="rgb(",f=c.c[e],m=a/b;if(/^#|rgb\(/.test(f))for(var h=0;3>h;h++)g+=Math.round(D(d(k,h),d(f,h),m))+(2>h?",":")");else g=D(p(k),p(f),m),g=l(f,n,null!=g?""+g:"");c.a.set(e,g)})})});return k},toggle:function(a,b,d,e){var c=this,f={},n=!1,g=/\b(?=\w)/g;return b?c.set(a)&&function(g){g!==n&&(n=!0===g||!1===g?g:!n,d?c.animate(n?b:a,f.stop?f.stop()||f.time:d,e,f):c.set(n?b:a))}:c.toggle(l(a,g,
"-"),l(a,g,"+"))},on:function(a,b,d,e){return f(this,function(c,h){f(a.split(/\s/),function(a){function g(c){c=c||A.event;b.apply(e?d:c.target,e||d||[c,h])&&!e||a!=f||(c.stopPropagation&&(c.preventDefault(),c.stopPropagation()),c.returnValue=!1,c.cancelBubble=!0)}var f=l(a,/\|/);(b.M=b.M||[]).push({e:c,h:g,n:f});c.addEventListener?c.addEventListener(f,g,!0):c.attachEvent("on"+f,g)})})}},function(a,b){L.prototype[a]=b});v({ready:w,loop:function(a){var b={q:a,r:(new Date).getTime(),b:function(){for(var a=
0;a<H.length;a++)H[a]===b&&H.splice(a--,1)}};2>H.push(b)&&function e(){f(H,function(a){a.q(Math.max(0,(new Date).getTime()-a.r),a.b)}).length&&O(e)}();return b.b},v:null},function(a,b){s[a]=b});A.onload=q;r.addEventListener&&r.addEventListener("DOMContentLoaded",q,!1);var P={$:s,EE:function(a,b,d,e){return function(){var c=s(r.createElement(a));u(b)||"object"!=typeof b?c.add(b):c.set(b).add(d);e&&e(c);return c}}};A.require=function(a){if("minified"==a)return P}})();var y=require("minified"),K=y.k,M=y.t;
K(function(){function h(){var f=Math.max(0,Math.min(Math.round(Math.random()*z-0.5),z));return f!=p?f:h()}function u(){q.f=!0;K(q).u({d:100,j:l[C],i:l[p]},B,1).A(function(){q.d=0;q.f=!1;F=p;p=C;C=h()})}function v(){x||(x=K.loop(function(f){q.f||u();var h="linear-gradient("+Math.round(100*(10*(f/360)-75))/100+"deg, "+q.j+" 0%, "+l[p]+" "+Math.round(100*q.d)/100+"%, "+q.i+" 100%); ",r="";K(I).w(function(f){r+="background: "+f+h});w.set("$$",r)}))}function f(){s++||(K("#shareExt").add([M("iframe",{"@allowtransparency":"true",
"@frameborder":0,"@scrolling":"no",p:"100px",o:"20px","@src":"http://ghbtns.com/github-btn.html?user=timjansen&repo=minified.js&type=watch&count=true"}),M("iframe",{"@allowtransparency":"true","@frameborder":0,"@scrolling":"no",p:"100px",o:"20px","@src":"https://platform.twitter.com/widgets/tweet_button.html"}),M("div",{k:"g-plusone",s:"inline","@data-size":"medium"})]),K("head").add(M("script",{type:"text/javascript",async:!0,src:"https://apis.google.com/js/plusone.js"})))}var I=["","-moz-","-ms-",
"-webkit-"],B=2E3,l="#f00 #0f0 #00f #0ff #f0f #ff0".split(" "),z=l.length,p=h(),C=h(),F=h(),q={d:0,j:l[p],i:l[F],f:!1},w=K(".shareButton"),x,s=0,t=K("#shareDiv").toggle({l:0,m:0},{l:1,m:1},700,1);w.g("mouseover",function(){f();v()});w.g("mouseout",function(){x&&x();x=null;w.set("$$","")});w.g("click",function(){f();t()});"#share"==window.location.hash&&(f(),t(!0));window.setTimeout(f,2500)});
