var j=!0,s=null,t=!1;
(function(k,p){function A(a){return a!=s?""+a:""}function x(a){return"string"==typeof a}function v(a){return"function"==typeof a}function q(a){return a&&a.length!=s&&!x(a)&&!a.nodeType&&!v(a)}function l(a,b){if(q(a))for(var c=0;c<a.length;c++)b(a[c],c);else for(c in a)a.hasOwnProperty(c)&&b(c,a[c]);return a}function G(a,b){var c=[];l(a,function(a,d){(!b||b(a,d))&&c.push(a)});return c}function u(a,b,c){c=c||[];l(a,function(a,d){q(a=b(a,d))?l(a,function(a){c.push(a)}):a!=s&&c.push(a)});return c}function n(a,
b,c){return A(a).replace(b,c||"")}function C(a,b){var c=k.setTimeout(b,a||0);return function(){a&&k.clearTimeout(c)}}function w(a){return parseFloat(n(a,/^[^\d-]/))}function I(a){var b={o:"absolute",g:"hidden",d:"block",f:s},c=a.get(b);a.set(b);b=a[0].offsetHeight;a.set(c);return b}function J(a){a()}function K(){l(D,J);D=s}function L(a){D?D.push(a):C(0,a)}function H(){function a(a,d){b==s&&(b=a,c=d,C(0,function(){l(e,J)}))}var b,c=[],e=[],d=a.then=function(a,d){function h(){try{var e=b?a:d;if(v(e)){var h=
e.apply(s,c);h&&v(h.then)?h.then(function(a){m(j,[a])},function(a){m(t,[a])}):m(j,[h])}else m(b,c)}catch(l){m(t,[l])}}var m=H();b!=s?C(0,h):e.push(h);return m};a.always=function(a){return d(a,a)};a.error=function(a){return d(0,a)};return a}function M(a){return P[a]||"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}function r(a,b,c){return v(a)?L(a):new F(z(a,b,c))}function z(a,b,c){function e(a){return q(a)?u(a,e):a}function d(a){a=e(a);return!f?a:G(a,function(a){for(;a=a.parentNode;){if(a===
f)return j;if(c)return t}})}var f,g,h,m,l;if(b&&1!=(b=z(b)).length)return u(b,function(b){return z(a,b)});f=b&&b[0];if(!x(a))return d(q(a)?a:[a]);if(1<(b=a.split(/\s*,\s*/)).length)return u(b,function(a){return z(a,f)});if(b=/(\S+)\s+(.+)$/.exec(a))return z(b[2],z(b[1],f));if(a!=(b=n(a,/^#/)))return d([p.getElementById(b)]);f=f||p;g=(b=/([^.]*)\.?([^.]*)/.exec(a))[1];m=b[2];b=(h=f.getElementsByClassName&&m)?f.getElementsByClassName(m):f.getElementsByTagName(g||"*");if(g=h?g:m)l=RegExp(B+g+B,"i"),
b=G(b,function(a){return l.test(a[h?"nodeName":"className"])});return c?d(b):b}function F(a){for(var b=0;b<a.length;b++)this[b]=a[b];this.length=a.length;this.raw=a}var B="\\b",D=[],E=[],Q=u(["msR","webkitR","mozR","r"],function(a){return k[a+"equestAnimationFrame"]})[0]||function(a){C(33,a)},N=!!p.all&&!D.map,P={"\t":"\\t","\r":"\\r","\n":"\\n",'"':'\\"',"\\":"\\\\"};l({each:function(a){l(this.raw,a);return this},filter:function(a){return new F(G(this.raw,a))},collect:function(a,b){return new F(u(this.raw,
a,b))},sub:function(a,b){var c=this.length,e=0>a?c+a:a,d=b==s?c:0<=b?b:c+b;return this.filter(function(a,b){return b>=e&&b<d})},find:function(a){for(var b=v(a)?a:function(b,c){if(a===b)return c},c,e=0;e<this.length;e++)if((c=b(this[e],e))!=s)return c},hasClass:function(a){var b=RegExp(B+a+B);return this.find(function(a){return b.test(a.className)?a:s})},remove:function(){this.each(function(a){a.parentNode.removeChild(a)})},get:function(a,b){var c=this,e=c[0];if(e){if(x(a)){var d=n(a,/^[$@]/),f,g=
/\$\$/.test(a)&&("hidden"==c.get("$visibility")||"none"==c.get("$display"));f="$"==a?e.className:"$$fade"==a?isNaN(f=g?0:N?w(c.get("$filter"))/100:w(c.get("$opacity")))?1:f:"$$slide"==a?(g?0:e.offsetHeight)+"px":/^\$/.test(a)?k.getComputedStyle?k.getComputedStyle(e,s).getPropertyValue(n(d,/[A-Z]/g,function(a){return"-"+a.toLowerCase()})):e.currentStyle[d]:/^@/.test(a)?e.getAttribute(d):e[d];return b?w(f):f}var h={};l(a,function(a){h[a]=c.get(a)});return h}},set:function(a,b,c){var e=this,d;void 0!==
b?"$$fade"==a||"$$slide"==a?e.set({g:0<(d=w(b))?"visible":"hidden",d:"block"}).set("$$fade"==a?N?{k:"alpha(opacity = "+100*d+")",p:1}:{l:d}:{f:/px$/.test(b)?b:function(a,b,c){return d*(d&&I($(c)))+"px"},m:"hidden"}):e.each(function(e,d){var h=v(b)?b:c,m=n(a,/^[@$]/),y=e.className||"",k=/^\$/.test(a)?e.style:e,h=h?h(r(e).get(a),d,e,b):b;"$"==a?(l(h.split(/\s+/),function(a){var b=n(a,/^[+-]/),c=y;y=n(y,RegExp(B+b+B));if(/^\+/.test(a)||b==a&&c==y)y+=" "+b}),e.className=n(y,/^\s+|\s+(?=\s|$)/g)):/^@/.test(a)?
h!=s&&k.setAttribute(m,h):k[m]=h}):x(a)||v(a)?e.set("$",a):l(a,function(a,b){e.set(a,b,c)});return e},append:function(a,b){return this.set(a,b,function(a,b,d,f){return A(a)+f})},prepend:function(a,b){return this.set(a,b,function(a,b,d,f){return f+A(a)})},add:function(a,b){return this.each(function(c,e){var d;(function g(a){q(a)?l(a,g):a!=s&&(a=a.nodeType?a:p.createTextNode(a),d?d.parentNode.insertBefore(a,d.nextSibling):b?b(a,c,c.parentNode):c.appendChild(a),d=a)})(v(a)?a(c,e):(a==s||a.nodeType||
q(a))&&e?s:a)})},fill:function(a){return this.each(function(a){r(a.childNodes).remove()}).add(a)},addBefore:function(a){return this.add(a,function(a,c,e){e.insertBefore(a,c)})},addAfter:function(a){return this.add(a,function(a,c,e){e.insertBefore(a,c.nextSibling)})},addFront:function(a){return this.add(a,function(a,c){c.insertBefore(a,c.firstChild)})},replace:function(a){return this.add(a,function(a,c,e){e.replaceChild(a,c)})},animate:function(a,b,c,e,d){var f=this,g=[],h=/-?[\d.]+/,m,k,p=H();d=d||
{};d.time=0;d.stop=function(){m&&m();k&&k();p(t)};m=C(e,function(){b=b||500;c=c||0;f.each(function(b){var c={b:r(b),a:{},c:{}};l(c.a=c.b.get(a),function(b,e){var d=a[b];"$$slide"==b&&(d=d*I(c.b)+"px");c.c[b]=/^[+-]=/.test(d)?n(d.substr(2),h,w(e)+w(n(d,/\+?=/))):d});g.push(c)});k=r.loop(function(a,e){function m(a,b){return/^#/.test(a)?parseInt(6<a.length?a.substr(1+2*b,2):(a=a.charAt(1+b))+a,16):parseInt(n(a,/[^\d,]+/g).split(",")[b])}function k(e,d){return e+a/b*(d-e)*(c+(1-c)*a/b*(3-2*a/b))}d.time=
a;a>=b||0>a?(l(g,function(a){a.b.set(a.c)}),e(),d.time=d.stop=s,p(j,[f])):l(g,function(a){l(a.a,function(b,c){var e="rgb(",d=a.c[b];if(/^#|rgb\(/.test(d))for(var f=0;3>f;f++)e+=Math.round(k(m(c,f),m(d,f)))+(2>f?",":")");else e=n(d,h,k(w(c),w(d)));a.b.set(b,e)})})})});return p},toggle:function(a,b,c,e){var d={},f=t,g=/\b(?=\w)/g,h=this;return!b?h.toggle(n(a,g,"-"),n(a,g,"+")):h.set(a)&&function(g){g!==f&&(f="boolean"==typeof g?g:!f,c?h.q(f?b:a,d.stop?d.stop()||d.time:c,e,0,d):h.set(f?b:a))}},on:function(a,
b,c,e){return this.each(function(d,f){function g(a){a=a||k.event;if(!b.apply(e||a.target,c||[a,f])||c)a.stopPropagation&&(a.preventDefault(),a.stopPropagation()),a.returnValue=t,a.cancelBubble=j}(b.M=b.M||[]).push({e:d,h:g,n:a});d.addEventListener?d.addEventListener(a,g,j):d.attachEvent("on"+a,g)})},values:function(a){var b=a||{};this.each(function(a){var e=a.name,d=A(a.value),f=b[e];if(/form/i.test(a.tagName))r(a.elements).values(b);else if(e&&(!/kbox|dio/i.test(a.type)||a.checked))q(f)?f.push(d):
b[e]=f==s?d:[f,d]});return b},offset:function(){for(var a=this[0],b={x:0,y:0};a;)b.x+=a.offsetLeft,b.y+=a.offsetTop,a=a.offsetParent;return b}},function(a,b){F.prototype[a]=b});l({$$:function(a){return z(a)[0]},el:function(a,b,c){var e=p.documentElement.namespaceURI;a=r(e?p.createElementNS(e,a):p.createElement(a));return q(b)||"object"!=typeof b?a.add(b):a.set(b).add(c)},request:function(a,b,c,e,d,f){var g,h=c,m=0,n=H();try{return g=k.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Msxml2.XMLHTTP.3.0"),
c!=s&&(e=e||{},!x(c)&&!c.nodeType&&(h=u(c,function O(a,b){return q(b)?u(b,function(b){return O(a,b)}):encodeURIComponent(a)+(b!=s?"="+encodeURIComponent(b):"")}).join("&")),/post/i.test(a)?!c.nodeType&&(!x(c)&&!e["Content-Type"])&&(e["Content-Type"]="application/x-www-form-urlencoded"):(b+="?"+h,h=s)),g.open(a,b,j,d,f),l(e,function(a,b){g.setRequestHeader(a,b)}),g.onreadystatechange=function(){4==g.readyState&&!m++&&(200==g.status?n(j,[g.responseText,g.responseXML]):n(t,[g.status,g.statusText,g.responseText]))},
g.send(h),n}catch(p){m||n(t,[0,s,A(p)])}},toJSON:function b(c){return c==s?""+c:x(c=c.valueOf())?'"'+n(c,/[\\\"\x00-\x1f\x22\x5c]/g,M)+'"':q(c)?"["+u(c,b).join()+"]":"object"==typeof c?"{"+u(c,function(c,d){return b(c)+":"+b(d)}).join()+"}":A(c)},parseJSON:k.JSON?k.JSON.parse:function(b){b=n(b,/[\x00\xad\u0600-\uffff]/g,M);if(/^[[\],:{}\s]*$/.test(n(n(b,/\\["\\\/bfnrtu]/g),/"[^"\\\n\r]*"|true|false|null|[\d.eE+-]+/g)))return eval("("+b+")")},ready:L,setCookie:function(b,c,e,d,f,g){p.cookie=b+"="+
(g?c:escape(c))+(e?"; expires="+("object"==typeof e?e:new Date((new Date).getTime()+864E5*e)).toUTCString():"")+"; path="+(d?escapeURI(d):"/")+(f?"; domain="+escape(f):"")},getCookie:function(b,c){var e,d=(e=RegExp("(^|;)\\s*"+b+"=([^;]*)").exec(p.cookie))&&e[2];return c?d:d&&unescape(d)},loop:function(b){var c={i:b,j:(new Date).getTime(),a:function(){for(var b=0;b<E.length;b++)E[b]===c&&E.splice(b--,1)}};2>E.push(c)&&function d(){l(E,function(b){b.i(Math.max(0,(new Date).getTime()-b.j),b.a)}).length&&
Q(d)}();return c.a},off:function(b){l(b.M,function(b){b.e.addEventListener?b.e.removeEventListener(b.n,b.h,j):b.e.detachEvent("on"+b.n,b.h)});b.M=s}},function(b,c){r[b]=c});k.onload=K;p.addEventListener&&p.addEventListener("DOMContentLoaded",K,t);k.$=k.MINI=r;k.$$=r.$$;k.EE=r.el})(window,document);
