var j=!0,s=null,t=!1;
(function(k,p){function A(a){return a!=s?""+a:""}function y(a){return"string"==typeof a}function v(a){return"function"==typeof a}function w(a){return a&&a.length!=s&&!y(a)&&!(a&&a.nodeType)&&!v(a)}function m(a,b){if(w(a))for(var c=0;c<a.length;c++)b(a[c],c);else for(c in a)a.hasOwnProperty(c)&&b(c,a[c]);return a}function F(a,b){var c=[];m(a,function(a,e){b(a,e)&&c.push(a)});return c}function u(a,b,c){c=c||[];m(a,function(a,e){w(a=b(a,e))?m(a,function(a){c.push(a)}):a!=s&&c.push(a)});return c}function l(a,
b,c){return A(a).replace(b,c||"")}function x(a){return parseFloat(l(a,/^[^\d-]/))}function H(a){var b={o:"absolute",g:"hidden",d:"block",f:s},c=a.get(b);a.set(b);b=a[0].offsetHeight;a.set(c);return b}function I(a){a()}function J(){m(B,I);B=s}function K(a){B?B.push(a):k.setTimeout(a,0)}function G(){function a(a,e){b==s&&(b=a,c=e,k.setTimeout(function(){m(d,I)},0))}var b,c=[],d=[],e=a.then=function(a,e){function f(){try{var d=b?a:e;if(v(d)){var f=d.apply(s,c);f&&v(f.then)?f.then(function(a){n(j,[a])},
function(a){n(t,[a])}):n(j,[f])}else n(b,c)}catch(m){n(t,[m])}}var n=G();b!=s?k.setTimeout(f,0):d.push(f);return n};a.always=function(a){return e(a,a)};a.error=function(a){return e(0,a)};return a}function L(a){return N[a]||"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}function q(a,b,c){return v(a)?K(a):new D(z(a,b,c))}function z(a,b,c){function d(a){return w(a)?u(a,d):a}function e(a){a=d(a);return h?F(a,function(a){for(;a=a.parentNode;){if(a===h)return j;if(c)return t}}):a}var h,g,f,n,r;if(b&&
1!=(b=z(b)).length)return u(b,function(b){return z(a,b)});h=b&&b[0];if(!y(a))return e(w(a)?a:[a]);if(1<(b=a.split(/\s*,\s*/)).length)return u(b,function(a){return z(a,h)});if(b=/(\S+)\s+(.+)$/.exec(a))return z(b[2],z(b[1],h));if(a!=(b=l(a,/^#/)))return e([p.getElementById(b)]);h=h||p;g=(b=/([^.]*)\.?([^.]*)/.exec(a))[1];n=b[2];b=(f=h.getElementsByClassName&&n)?h.getElementsByClassName(n):h.getElementsByTagName(g||"*");if(g=f?g:n)r=RegExp("\\b"+g+"\\b","i"),b=F(b,function(a){return r.test(a[f?"nodeName":
"className"])});return c?e(b):b}function D(a){for(var b=0;b<a.length;b++)this[b]=a[b];this.length=a.length}var B=[],C=[],O=u(["msR","webkitR","mozR","r"],function(a){return k[a+"equestAnimationFrame"]})[0]||function(a){k.setTimeout(a,33)},E=!!p.all&&!B.map,N={"\t":"\\t","\r":"\\r","\n":"\\n",'"':'\\"',"\\":"\\\\"};m({each:function(a){m(this,a);return this},filter:function(a){return new D(F(this,a))},collect:function(a,b){return new D(u(this,a,b))},sub:function(a,b){var c=this.length,d=0>a?c+a:a,e=
b==s?c:0<=b?b:c+b;return this.filter(function(a,b){return b>=d&&b<e})},find:function(a){for(var b=v(a)?a:function(b,c){if(a===b)return c},c,d=0;d<this.length;d++)if((c=b(this[d],d))!=s)return c},hasClass:function(a){var b=RegExp("\\b"+a+"\\b");return this.find(function(a){return b.test(a.className)?a:s})},remove:function(){this.each(function(a){a.parentNode.removeChild(a)})},get:function(a,b){var c=this,d=c[0];if(d){if(y(a)){var e=l(a,/^[$@]/),h,g=/^\$\$/.test(a)&&("hidden"==c.get("$visibility")||
"none"==c.get("$display"));h="$"==a?d.className:"$$"==a?E?d.style.cssText:d.getAttribute("style"):"$$fade"==a?isNaN(h=g?0:E?x(c.get("$filter"))/100:x(c.get("$opacity")))?1:h:"$$slide"==a?(g?0:d.offsetHeight)+"px":/^\$/.test(a)?k.getComputedStyle?k.getComputedStyle(d,s).getPropertyValue(l(e,/[A-Z]/g,function(a){return"-"+a.toLowerCase()})):d.currentStyle[e]:/^@/.test(a)?d.getAttribute(e):d[e];return b?x(h):h}var f={};m(a,function(a){f[a]=c.get(a)});return f}},set:function(a,b,c){var d=this,e;void 0!==
b?"$$fade"==a||"$$slide"==a?d.set({g:0<(e=x(b))?"visible":"hidden",d:"block"}).set("$$fade"==a?E?{k:"alpha(opacity = "+100*e+")",p:1}:{l:e}:{f:/px$/.test(b)?b:function(a,b,c){return e*(e&&H($(c)))+"px"},m:"hidden"}):d.each(function(d,e){var f=v(b)?b:c,n=l(a,/^[@$]/),r=d.className||"",k=/^\$/.test(a)?d.style:d,f=f?f(q(d).get(a),e,d,b):b;"$"==a?(m(f.split(/\s+/),function(a){var b=l(a,/^[+-]/),c=r;r=l(r,RegExp("\\b"+b+"\\b"));if(/^\+/.test(a)||b==a&&c==r)r+=" "+b}),d.className=l(r,/^\s+|\s+(?=\s|$)/g)):
"$$"==a?E?k.cssText=f:d.setAttribute("style",f):/^@/.test(a)?f!=s&&k.setAttribute(n,f):k[n]=f}):y(a)||v(a)?d.set("$",a):m(a,function(a,b){d.set(a,b,c)});return d},append:function(a,b){return this.set(a,b,function(a,b,e,h){return A(a)+h})},prepend:function(a,b){return this.set(a,b,function(a,b,e,h){return h+A(a)})},add:function(a,b){return this.each(function(c,d){var e;(function g(a){w(a)?m(a,g):v(a)?g(a(c,d)):a!=s&&(a=a&&a.nodeType?a:p.createTextNode(a),e?e.parentNode.insertBefore(a,e.nextSibling):
b?b(a,c,c.parentNode):c.appendChild(a),e=a)})(a&&a.nodeType&&d?s:a)})},fill:function(a){return this.each(function(a){q(a.childNodes).remove()}).add(a)},addBefore:function(a){return this.add(a,function(a,c,d){d.insertBefore(a,c)})},addAfter:function(a){return this.add(a,function(a,c,d){d.insertBefore(a,c.nextSibling)})},addFront:function(a){return this.add(a,function(a,c){c.insertBefore(a,c.firstChild)})},replace:function(a){return this.add(a,function(a,c,d){d.replaceChild(a,c)})},clone:function(){return this.collect(function(a){var b=
{},c,d=a&&a.nodeType;return 1==d?(m(a.attributes,function(a){c=a.name;b["style"==c?"$$":"class"==c?"$":"@"+c]=a.value}),q.el(a.tagName,b,q(a.childNodes).clone())):2<d&&5>d?a.textContent:s})},animate:function(a,b,c,d){var e=this,h=[],g=/-?[\d.]+/,f,n=G();d=d||{};d.time=0;d.stop=function(){f();n(t)};b=b||500;c=c||0;e.each(function(b){var c={b:q(b),a:{},c:{}};m(c.a=c.b.get(a),function(b,d){var e=a[b];"$$slide"==b&&(e=e*H(c.b)+"px");c.c[b]=/^[+-]=/.test(e)?l(e.substr(2),g,x(d)+x(l(e,/\+?=/))):e});h.push(c)});
f=q.loop(function(a,f){function k(a,b){return/^#/.test(a)?parseInt(6<a.length?a.substr(1+2*b,2):(a=a.charAt(1+b))+a,16):parseInt(l(a,/[^\d,]+/g).split(",")[b])}function p(d,e){return d+a/b*(e-d)*(c+(1-c)*a/b*(3-2*a/b))}d.time=a;a>=b||0>a?(m(h,function(a){a.b.set(a.c)}),f(),d.time=d.stop=s,n(j,[e])):m(h,function(a){m(a.a,function(b,c){var d="rgb(",e=a.c[b];if(/^#|rgb\(/.test(e))for(var f=0;3>f;f++)d+=Math.round(p(k(c,f),k(e,f)))+(2>f?",":")");else d=l(e,g,p(x(c),x(e)));a.b.set(b,d)})})});return n},
toggle:function(a,b,c,d){var e={},h=t,g=/\b(?=\w)/g,f=this;return!b?f.toggle(l(a,g,"-"),l(a,g,"+")):f.set(a)&&function(g){g!==h&&(h="boolean"==typeof g?g:!h,c?f.q(h?b:a,e.stop?e.stop()||e.time:c,d,e):f.set(h?b:a))}},on:function(a,b,c,d){return this.each(function(e,h){function g(a){a=a||k.event;if(!b.apply(d||a.target,c||[a,h])||c)a.stopPropagation&&(a.preventDefault(),a.stopPropagation()),a.returnValue=t,a.cancelBubble=j}(b.M=b.M||[]).push({e:e,h:g,n:a});e.addEventListener?e.addEventListener(a,g,
j):e.attachEvent("on"+a,g)})},offset:function(){for(var a=this[0],b={x:0,y:0};a;)b.x+=a.offsetLeft,b.y+=a.offsetTop,a=a.offsetParent;return b}},function(a,b){D.prototype[a]=b});m({$$:function(a){return z(a)[0]},el:function(a,b,c,d){return function(){var e=p.documentElement.namespaceURI,e=q(e?p.createElementNS(e,a):p.createElement(a));w(b)||"object"!=typeof b?e.add(b):e.set(b).add(c);d&&d(e);return e}},request:function(a,b,c,d,e,h){var g,f=c,n=0,l=G();try{return g=k.XMLHttpRequest?new XMLHttpRequest:
new ActiveXObject("Msxml2.XMLHTTP.3.0"),c!=s&&(d=d||{},!y(c)&&(!c||!c.nodeType)&&(f=u(c,function M(a,b){return w(b)?u(b,function(b){return M(a,b)}):encodeURIComponent(a)+(b!=s?"="+encodeURIComponent(b):"")}).join("&")),/post/i.test(a)?(!c||!c.nodeType)&&(!y(c)&&!d["Content-Type"])&&(d["Content-Type"]="application/x-www-form-urlencoded"):(b+="?"+f,f=s)),g.open(a,b,j,e,h),m(d,function(a,b){g.setRequestHeader(a,b)}),g.onreadystatechange=function(){4==g.readyState&&!n++&&(200==g.status?l(j,[g.responseText,
g.responseXML]):l(t,[g.status,g.statusText,g.responseText]))},g.send(f),l}catch(p){n||l(t,[0,s,A(p)])}},toJSON:function b(c){return c==s?""+c:y(c=c.valueOf())?'"'+l(c,/[\\\"\x00-\x1f\x22\x5c]/g,L)+'"':w(c)?"["+u(c,b).join()+"]":"object"==typeof c?"{"+u(c,function(c,e){return b(c)+":"+b(e)}).join()+"}":A(c)},parseJSON:k.JSON?k.JSON.parse:function(b){b=l(b,/[\x00\xad\u0600-\uffff]/g,L);if(/^[[\],:{}\s]*$/.test(l(l(b,/\\["\\\/bfnrtu]/g),/"[^"\\\n\r]*"|true|false|null|[\d.eE+-]+/g)))return eval("("+b+
")")},ready:K,setCookie:function(b,c,d,e,h,g){p.cookie=b+"="+(g?c:escape(c))+(d?"; expires="+("object"==typeof d?d:new Date((new Date).getTime()+864E5*d)).toUTCString():"")+"; path="+(e?escapeURI(e):"/")+(h?"; domain="+escape(h):"")},getCookie:function(b,c){var d,e=(d=RegExp("(^|;)\\s*"+b+"=([^;]*)").exec(p.cookie))&&d[2];return c?e:e&&unescape(e)},loop:function(b){var c={i:b,j:(new Date).getTime(),a:function(){for(var b=0;b<C.length;b++)C[b]===c&&C.splice(b--,1)}};2>C.push(c)&&function e(){m(C,function(b){b.i(Math.max(0,
(new Date).getTime()-b.j),b.a)}).length&&O(e)}();return c.a},off:function(b){m(b.M,function(b){b.e.addEventListener?b.e.removeEventListener(b.n,b.h,j):b.e.detachEvent("on"+b.n,b.h)});b.M=s}},function(b,c){q[b]=c});k.onload=J;p.addEventListener&&p.addEventListener("DOMContentLoaded",J,t);k.$=k.MINI=q;k.$$=q.$$;k.EE=q.el})(this,document);
