var j=!0,r=null,s=!1;if(/^u/.test(typeof define)){var J={};this.define=function(t,u){J[t]=u()};this.require=function(t){return J[t]}}
define("minified",function(){function t(a){return a!=r?""+a:""}function u(a){return"string"==typeof a}function x(a){return"function"==typeof a}function B(a){return a&&a.nodeType}function y(a){return a&&a.length!=r&&!u(a)&&!B(a)&&!x(a)}function l(a,b){if(y(a))for(var c=0;c<a.length;c++)b(a[c],c);else for(c in a)a.hasOwnProperty(c)&&b(c,a[c]);return a}function G(a,b){var c=[];l(a,function(a,e){b(a,e)&&c.push(a)});return c}function v(a,b){var c=[];l(a,function(a,e){y(a=b(a,e))?l(a,function(a){c.push(a)}):
a!=r&&c.push(a)});return c}function k(a,b,c){return t(a).replace(b,c||"")}function z(a){return parseFloat(k(a,/^[^\d-]/))}function K(a){var b={o:"absolute",g:"hidden",d:"block",f:r},c=a.get(b);a.set(b);b=a[0].offsetHeight;a.set(c);return b}function L(a){a()}function M(){l(C,L);C=r}function N(a){C?C.push(a):p.setTimeout(a,0)}function H(){function a(a,e){b==r&&(b=a,c=e,p.setTimeout(function(){l(d,L)},0))}var b,c=[],d=[],e=a.then=function(a,e){function f(){try{var d=b?a:e;if(x(d)){var f=d.apply(r,c);
f&&x(f.then)?f.then(function(a){m(j,[a])},function(a){m(s,[a])}):m(j,[f])}else m(b,c)}catch(l){m(s,[l])}}var m=H();b!=r?p.setTimeout(f,0):d.push(f);return m};a.always=function(a){return e(a,a)};a.error=function(a){return e(0,a)};return a}function O(a){return Q[a]||"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}function w(a,b,c){return x(a)?N(a):new E(A(a,b,c))}function A(a,b,c){function d(a){return y(a)?v(a,d):a}function e(a){a=d(a);return h?G(a,function(a){for(;a=a.parentNode;){if(a===h)return j;
if(c)return s}}):a}var h,g,f,m,q;if(b&&1!=(b=A(b)).length)return v(b,function(b){return A(a,b)});h=b&&b[0];if(!u(a))return e(y(a)?a:[a]);if(1<(b=a.split(/\s*,\s*/)).length)return v(b,function(a){return A(a,h)});if(b=/(\S+)\s+(.+)$/.exec(a))return A(b[2],A(b[1],h));if(a!=(b=k(a,/^#/)))return e([n.getElementById(b)]);h=h||n;g=(b=/([^.]*)\.?([^.]*)/.exec(a))[1];m=b[2];b=(f=h.getElementsByClassName&&m)?h.getElementsByClassName(m):h.getElementsByTagName(g||"*");if(g=f?g:m)q=RegExp("\\b"+g+"\\b","i"),b=
G(b,function(a){return q.test(a[f?"nodeName":"className"])});return c?e(b):b}function E(a){for(var b=0;b<a.length;b++)this[b]=a[b];this.length=a.length}var p=this,n=document,C=[],D=[],R=v(["msR","webkitR","mozR","r"],function(a){return p[a+"equestAnimationFrame"]})[0]||function(a){p.setTimeout(a,33)},F=!!n.all&&!C.map,Q={"\t":"\\t","\r":"\\r","\n":"\\n",'"':'\\"',"\\":"\\\\"};l({each:function(a){l(this,a);return this},filter:function(a){return new E(G(this,a))},collect:function(a){return new E(v(this,
a))},sub:function(a,b){var c=this.length,d=0>a?c+a:a,e=b==r?c:0<=b?b:c+b;return this.filter(function(a,b){return b>=d&&b<e})},find:function(a){for(var b=x(a)?a:function(b,c){if(a===b)return c},c,d=0;d<this.length;d++)if((c=b(this[d],d))!=r)return c},hasClass:function(a){var b=RegExp("\\b"+a+"\\b");return this.find(function(a){return b.test(a.className)?a:r})},remove:function(){this.each(function(a){a.parentNode.removeChild(a)})},get:function(a,b){var c=this,d=c[0];if(d){if(u(a)){var e=k(a,/^[$@]/),
h,g=/^\$\$/.test(a)&&("hidden"==c.get("$visibility")||"none"==c.get("$display"));h="$"==a?d.className:"$$"==a?F?d.style.cssText:d.getAttribute("style"):"$$fade"==a?isNaN(h=g?0:F?z(c.get("$filter"))/100:z(c.get("$opacity")))?1:h:"$$slide"==a?(g?0:d.offsetHeight)+"px":/^\$/.test(a)?p.getComputedStyle?p.getComputedStyle(d,r).getPropertyValue(k(e,/[A-Z]/g,function(a){return"-"+a.toLowerCase()})):d.currentStyle[e]:/^@/.test(a)?d.getAttribute(e):d[e];return b?z(h):h}var f={};l(a,function(a){f[a]=c.get(a)});
return f}},set:function(a,b,c){var d=this,e;void 0!==b?"$$fade"==a||"$$slide"==a?d.set({g:0<(e=z(b))?"visible":"hidden",d:"block"}).set("$$fade"==a?F?{k:"alpha(opacity = "+100*e+")",p:1}:{l:e}:{f:/px$/.test(b)?b:function(a,b,c){return e*(e&&K($(c)))+"px"},m:"hidden"}):d.each(function(d,e){var f=x(b)?b:c,m=k(a,/^[@$]/),q=d.className||"",I=/^\$/.test(a)?d.style:d,f=f?f(w(d).get(a),e,d,b):b;"$"==a?(l(f.split(/\s+/),function(a){var b=k(a,/^[+-]/),c=q;q=k(q,RegExp("\\b"+b+"\\b"));if(/^\+/.test(a)||b==
a&&c==q)q+=" "+b}),d.className=k(q,/^\s+|\s+(?=\s|$)/g)):"$$"==a?F?I.cssText=f:d.setAttribute("style",f):/^@/.test(a)?f!=r&&I.setAttribute(m,f):I[m]=f}):u(a)||x(a)?d.set("$",a):l(a,function(a,b){d.set(a,b,c)});return d},append:function(a,b){return this.set(a,b,function(a,b,e,h){return t(a)+h})},prepend:function(a,b){return this.set(a,b,function(a,b,e,h){return h+t(a)})},add:function(a,b){return this.each(function(c,d){var e;(function g(a){y(a)?l(a,g):x(a)?g(a(c,d)):a!=r&&(a=B(a)?a:n.createTextNode(a),
e?e.parentNode.insertBefore(a,e.nextSibling):b?b(a,c,c.parentNode):c.appendChild(a),e=a)})(B(a)&&d?r:a)})},fill:function(a){return this.each(function(a){w(a.childNodes).remove()}).add(a)},addBefore:function(a){return this.add(a,function(a,c,d){d.insertBefore(a,c)})},addAfter:function(a){return this.add(a,function(a,c,d){d.insertBefore(a,c.nextSibling)})},addFront:function(a){return this.add(a,function(a,c){c.insertBefore(a,c.firstChild)})},replace:function(a){return this.add(a,function(a,c,d){d.replaceChild(a,
c)})},clone:function(){return this.collect(function(a){var b={},c,d=B(a);return 1==d?(l(a.attributes,function(a){c=a.name;"id"!=c&&(b["style"==c?"$$":"class"==c?"$":"@"+c]=a.value)}),w.EE(a.tagName,b,w(a.childNodes).clone())):5>d?a.textContent:r})},animate:function(a,b,c,d){var e=this,h=[],g=/-?[\d.]+/,f,m=H();d=d||{};d.time=0;d.stop=function(){f();m(s)};b=b||500;c=c||0;e.each(function(b){var c={b:w(b),a:{},c:{}};l(c.a=c.b.get(a),function(b,d){var e=a[b];"$$slide"==b&&(e=e*K(c.b)+"px");c.c[b]=/^[+-]=/.test(e)?
k(e.substr(2),g,z(d)+z(k(e,/\+?=/))):e});h.push(c)});f=w.loop(function(a,f){function p(a,b){return/^#/.test(a)?parseInt(6<a.length?a.substr(1+2*b,2):(a=a.charAt(1+b))+a,16):parseInt(k(a,/[^\d,]+/g).split(",")[b])}function n(d,e){return d+a/b*(e-d)*(c+(1-c)*a/b*(3-2*a/b))}d.time=a;a>=b||0>a?(l(h,function(a){a.b.set(a.c)}),f(),d.time=d.stop=r,m(j,[e])):l(h,function(a){l(a.a,function(b,c){var d="rgb(",e=a.c[b];if(/^#|rgb\(/.test(e))for(var f=0;3>f;f++)d+=Math.round(n(p(c,f),p(e,f)))+(2>f?",":")");else d=
k(e,g,n(z(c),z(e)));a.b.set(b,d)})})});return m},toggle:function(a,b,c,d){var e={},h=s,g=/\b(?=\w)/g,f=this;return!b?f.toggle(k(a,g,"-"),k(a,g,"+")):f.set(a)&&function(g){g!==h&&(h="boolean"==typeof g?g:!h,c?f.q(h?b:a,e.stop?e.stop()||e.time:c,d,e):f.set(h?b:a))}},on:function(a,b,c,d){return this.each(function(e,h){function g(a){a=a||p.event;if(!b.apply(d?c:a.target,d||c||[a,h])||d)a.stopPropagation&&(a.preventDefault(),a.stopPropagation()),a.returnValue=s,a.cancelBubble=j}(b.M=b.M||[]).push({e:e,
h:g,n:a});e.addEventListener?e.addEventListener(a,g,j):e.attachEvent("on"+a,g)})},offset:function(){for(var a=this[0],b={x:0,y:0};a;)b.x+=a.offsetLeft,b.y+=a.offsetTop,a=a.offsetParent;return b}},function(a,b){E.prototype[a]=b});l({$$:function(a){return A(a)[0]},EE:function(a,b,c,d){return function(){var e=n.documentElement.namespaceURI,e=w(e?n.createElementNS(e,a):n.createElement(a));y(b)||"object"!=typeof b?e.add(b):e.set(b).add(c);d&&d(e);return e}},request:function(a,b,c,d,e,h){var g,f=c,m=0,
k=H();try{return g=p.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Msxml2.XMLHTTP.3.0"),c!=r&&(d=d||{},!u(c)&&!B(c)&&(f=v(c,function P(a,b){return y(b)?v(b,function(b){return P(a,b)}):encodeURIComponent(a)+(b!=r?"="+encodeURIComponent(b):"")}).join("&")),/post/i.test(a)?!B(c)&&(!u(c)&&!d["Content-Type"])&&(d["Content-Type"]="application/x-www-form-urlencoded"):(b+="?"+f,f=r)),g.open(a,b,j,e,h),l(d,function(a,b){g.setRequestHeader(a,b)}),g.onreadystatechange=function(){4==g.readyState&&!m++&&
(200==g.status?k(j,[g.responseText,g.responseXML]):k(s,[g.status,g.statusText,g.responseText]))},g.send(f),k}catch(n){m||k(s,[0,r,t(n)])}},toJSON:function b(c){return c==r?""+c:u(c=c.valueOf())?'"'+k(c,/[\\\"\x00-\x1f\x22\x5c]/g,O)+'"':y(c)?"["+v(c,b).join()+"]":"object"==typeof c?"{"+v(c,function(c,e){return b(c)+":"+b(e)}).join()+"}":t(c)},parseJSON:p.JSON?p.JSON.parse:function(b){b=k(b,/[\x00\xad\u0600-\uffff]/g,O);if(/^[[\],:{}\s]*$/.test(k(k(b,/\\["\\\/bfnrtu]/g),/"[^"\\\n\r]*"|true|false|null|[\d.eE+-]+/g)))return eval("("+
b+")")},ready:N,setCookie:function(b,c,d,e,h,g){n.cookie=b+"="+(g?c:escape(c))+(d?"; expires="+("object"==typeof d?d:new Date((new Date).getTime()+864E5*d)).toUTCString():"")+"; path="+(e?escapeURI(e):"/")+(h?"; domain="+escape(h):"")},getCookie:function(b,c){var d,e=(d=RegExp("(^|;)\\s*"+b+"=([^;]*)").exec(n.cookie))&&d[2];return c?e:e&&unescape(e)},loop:function(b){var c={i:b,j:(new Date).getTime(),a:function(){for(var b=0;b<D.length;b++)D[b]===c&&D.splice(b--,1)}};2>D.push(c)&&function e(){l(D,
function(b){b.i(Math.max(0,(new Date).getTime()-b.j),b.a)}).length&&R(e)}();return c.a},off:function(b){l(b.M,function(b){b.e.addEventListener?b.e.removeEventListener(b.n,b.h,j):b.e.detachEvent("on"+b.n,b.h)});b.M=r}},function(b,c){w[b]=c});p.onload=M;n.addEventListener&&n.addEventListener("DOMContentLoaded",M,s);return{$:w}});
