var j=!0,s=null,t=!1;
(function(k,n){function A(a){return a!=s?""+a:""}function x(a){return"string"==typeof a}function v(a){return"function"==typeof a}function r(a){return a&&a.length!=s&&!x(a)&&!a.nodeType&&!v(a)}function l(a,b){if(r(a))for(var c=0;c<a.length;c++)b(a[c],c);else for(c in a)a.hasOwnProperty(c)&&b(c,a[c]);return a}function G(a,b){var c=[];l(a,function(a,e){(!b||b(a,e))&&c.push(a)});return c}function u(a,b,c){c=c||[];l(a,function(a,e){r(a=b(a,e))?l(a,function(a){c.push(a)}):a!=s&&c.push(a)});return c}function m(a,
b,c){return A(a).replace(b,c||"")}function C(a,b){var c=k.setTimeout(b,a||0);return function(){a&&k.clearTimeout(c)}}function w(a){return parseFloat(m(a,/^[^\d-]/))}function I(a){var b={p:"absolute",g:"hidden",d:"block",f:s},c=a.get(b);a.set(b);b=a[0].offsetHeight;a.set(c);return b}function J(a){a()}function K(){l(D,J);D=s}function L(a){D?D.push(a):C(0,a)}function H(){function a(a,f){function g(){try{var d=b?a:f;if(v(d)){var g=d.apply(s,c);g&&v(g.k)?g.k(function(a){h.s(j,[a])},function(a){h.a(t,[a])}):
h.s(j,[g])}else h.s(b,c)}catch(O){h.s(t,[O])}}var h=H();b!=s?C(0,g):d.push(g);return h}var b,c=[],d=[];return{then:a,s:function(a,f){b==s&&(b=a,c=f,C(0,function(){l(d,J)}))},always:function(b){return a(b,b)},error:function(b){return a(0,b)}}}function M(a){return P[a]||"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}function q(a,b,c){return v(a)?L(a):new F(z(a,b,c))}function z(a,b,c){function d(a){return r(a)?u(a,d):a}function e(a){a=d(a);return!f?a:G(a,function(a){for(;a=a.parentNode;){if(a===
f)return j;if(c)return t}})}var f,g,h,p,l;if(b&&1!=(b=z(b)).length)return u(b,function(b){return z(a,b)});f=b&&b[0];if(!x(a))return e(r(a)?a:[a]);if(1<(b=a.split(/\s*,\s*/)).length)return u(b,function(a){return z(a,f)});if(b=/(\S+)\s+(.+)$/.exec(a))return z(b[2],z(b[1],f));if(a!=(b=m(a,/^#/)))return e([n.getElementById(b)]);f=f||n;g=(b=/([^.]*)\.?([^.]*)/.exec(a))[1];p=b[2];b=(h=f.getElementsByClassName&&p)?f.getElementsByClassName(p):f.getElementsByTagName(g||"*");if(g=h?g:p)l=RegExp(B+g+B,"i"),
b=G(b,function(a){return l.test(a[h?"nodeName":"className"])});return c?e(b):b}function F(a){for(var b=0;b<a.length;b++)this[b]=a[b];this.length=a.length;this.raw=a}var B="\\b",D=[],E=[],Q=u(["msR","webkitR","mozR","r"],function(a){return k[a+"equestAnimationFrame"]})[0]||function(a){C(33,a)},N=!!n.all&&!D.map,P={"\t":"\\t","\r":"\\r","\n":"\\n",'"':'\\"',"\\":"\\\\"};l({each:function(a){l(this.raw,a);return this},filter:function(a){return new F(G(this.raw,a))},collect:function(a,b){return new F(u(this.raw,
a,b))},sub:function(a,b){var c=0>a?this.length+a:a,d=b==s?this.length:0<=b?b:this.length+b;return this.filter(function(a,b){return b>=c&&b<d})},find:function(a){for(var b=v(a)?a:function(b,c){if(a===b)return c},c,d=0;d<this.length;d++)if((c=b(this[d],d))!=s)return c},hasClass:function(a){var b=RegExp(B+a+B);return this.find(function(a){return b.test(a.className)?a:s})},remove:function(){this.each(function(a){a.parentNode.removeChild(a)})},get:function(a,b){var c=this,d=c[0];if(d){if(x(a)){var e=m(a,
/^[$@]/),f,g=/\$\$/.test(a)&&("hidden"==c.get("$visibility")||"none"==c.get("$display"));f="$"==a?d.className:"$$fade"==a?isNaN(f=g?0:N?w(c.get("$filter"))/100:w(c.get("$opacity")))?1:f:"$$slide"==a?(g?0:d.offsetHeight)+"px":/^\$/.test(a)?k.getComputedStyle?k.getComputedStyle(d,s).getPropertyValue(m(e,/[A-Z]/g,function(a){return"-"+a.toLowerCase()})):d.currentStyle[e]:/^@/.test(a)?d.getAttribute(e):d[e];return b?w(f):f}var h={};l(a,function(a){h[a]=c.get(a)});return h}},set:function(a,b,c){var d=
this,e;void 0!==b?"$$fade"==a||"$$slide"==a?d.set({g:0<(e=w(b))?"visible":"hidden",d:"block"}).set("$$fade"==a?N?{l:"alpha(opacity = "+100*e+")",q:1}:{m:e}:{f:/px$/.test(b)?b:function(a,b,c){return e*(e&&I($(c)))+"px"},o:"hidden"}):d.each(function(d,e){var h=v(b)?b:c,p=m(a,/^[@$]/),y=d.className||"",k=/^\$/.test(a)?d.style:d,h=h?h(q(d).get(a),e,d,b):b;"$"==a?(l(h.split(/\s+/),function(a){var b=m(a,/^[+-]/),c=y;y=m(y,RegExp(B+b+B));if(/^\+/.test(a)||b==a&&c==y)y+=" "+b}),d.className=m(y,/^\s+|\s+(?=\s|$)/g)):
/^@/.test(a)?h!=s&&k.setAttribute(p,h):k[p]=h}):x(a)||v(a)?d.set("$",a):l(a,function(a,b){d.set(a,b,c)});return d},append:function(a,b){return this.set(a,b,function(a,b,e,f){return A(a)+f})},prepend:function(a,b){return this.set(a,b,function(a,b,e,f){return f+A(a)})},add:function(a,b){return this.each(function(c,d){var e;(function g(a){r(a)?l(a,g):a!=s&&(a=a.nodeType?a:n.createTextNode(a),e?e.parentNode.insertBefore(a,e.nextSibling):b?b(a,c,c.parentNode):c.appendChild(a),e=a)})(v(a)?a(c,d):(a==s||
a.nodeType||r(a))&&d?s:a)})},fill:function(a){return this.each(function(a){q(a.childNodes).remove()}).add(a)},addBefore:function(a){return this.add(a,function(a,c,d){d.insertBefore(a,c)})},addAfter:function(a){return this.add(a,function(a,c,d){d.insertBefore(a,c.nextSibling)})},addFront:function(a){return this.add(a,function(a,c){c.insertBefore(a,c.firstChild)})},replace:function(a){return this.add(a,function(a,c,d){d.replaceChild(a,c)})},animate:function(a,b,c,d,e){var f=this,g=[],h=/-?[\d.]+/,p,
k,n=H();e=e||{};e.time=0;e.stop=function(){p&&p();k&&k();n.s(t)};p=C(d,function(){b=b||500;c=c||0;f.each(function(b){var c={b:q(b),a:{},c:{}};l(c.a=c.b.get(a),function(b,d){var e=a[b];"$$slide"==b&&(e=e*I(c.b)+"px");c.c[b]=/^[+-]=/.test(e)?m(e.substr(2),h,w(d)+w(m(e,/\+?=/))):e});g.push(c)});k=q.loop(function(a,d){function k(a,b){return/^#/.test(a)?parseInt(6<a.length?a.substr(1+2*b,2):(a=a.charAt(1+b))+a,16):parseInt(m(a,/[^\d,]+/g).split(",")[b])}function p(d,e){return d+a/b*(e-d)*(c+(1-c)*a/b*
(3-2*a/b))}e.time=a;a>=b||0>a?(l(g,function(a){a.b.set(a.c)}),d(),e.time=e.stop=s,n.s(j,[f])):l(g,function(a){l(a.a,function(b,c){var d="rgb(",e=a.c[b];if(/^#|rgb\(/.test(e))for(var f=0;3>f;f++)d+=Math.round(p(k(c,f),k(e,f)))+(2>f?",":")");else d=m(e,h,p(w(c),w(e)));a.b.set(b,d)})})})});return n},toggle:function(a,b,c,d){var e={},f=t,g=/\b(?=\w)/g,h=this;return!b?h.toggle(m(a,g,"-"),m(a,g,"+")):h.set(a)&&function(g){g!==f&&(f="boolean"==typeof g?g:!f,c?h.r(f?b:a,e.stop?e.stop()||e.time:c,d,0,e):h.set(f?
b:a))}},on:function(a,b,c,d){return this.each(function(e,f){function g(a){a=a||k.event;if(!b.apply(d||a.target,c||[a,f])||c)a.stopPropagation&&(a.preventDefault(),a.stopPropagation()),a.returnValue=t,a.cancelBubble=j}(b.M=b.M||[]).push({e:e,h:g,n:a});e.addEventListener?e.addEventListener(a,g,j):e.attachEvent("on"+a,g)})},values:function(a){var b=a||{};this.each(function(a){var d=a.name,e=A(a.value),f=b[d];if(/form/i.test(a.tagName))q(a.elements).values(b);else if(d&&(!/kbox|dio/i.test(a.type)||a.checked))r(f)?
f.push(e):b[d]=f==s?e:[f,e]});return b},offset:function(){for(var a=this[0],b={x:0,y:0};a;)b.x+=a.offsetLeft,b.y+=a.offsetTop,a=a.offsetParent;return b}},function(a,b){F.prototype[a]=b});l({$$:function(a){return z(a)[0]},el:function(a,b,c){var d=n.documentElement.namespaceURI;a=q(d?n.createElementNS(d,a):n.createElement(a));return r(b)||"object"!=typeof b?a.add(b):a.set(b).add(c)},request:function(a,b,c,d,e,f){var g,h=c,m=0,n=H();try{return g=k.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Msxml2.XMLHTTP.3.0"),
c!=s&&(d=d||{},!x(c)&&!c.nodeType&&(h=u(c,function R(a,b){return r(b)?u(b,function(b){return R(a,b)}):encodeURIComponent(a)+(b!=s?"="+encodeURIComponent(b):"")}).join("&")),/post/i.test(a)?!c.nodeType&&(!x(c)&&!d["Content-Type"])&&(d["Content-Type"]="application/x-www-form-urlencoded"):(b+="?"+h,h=s)),g.open(a,b,j,e,f),l(d,function(a,b){g.setRequestHeader(a,b)}),g.onreadystatechange=function(){4==g.readyState&&!m++&&(200==g.status?n.s(j,[g.responseText,g.responseXML]):n.s(t,[g.status,g.statusText,
g.responseText]))},g.send(h),n}catch(q){m||n.s(t,[0,s,A(q)])}},toJSON:function b(c){return c==s?""+c:x(c=c.valueOf())?'"'+m(c,/[\\\"\x00-\x1f\x22\x5c]/g,M)+'"':r(c)?"["+u(c,b).join()+"]":"object"==typeof c?"{"+u(c,function(c,e){return b(c)+":"+b(e)}).join()+"}":A(c)},parseJSON:k.JSON?k.JSON.parse:function(b){b=m(b,/[\x00\xad\u0600-\uffff]/g,M);if(/^[[\],:{}\s]*$/.test(m(m(b,/\\["\\\/bfnrtu]/g),/"[^"\\\n\r]*"|true|false|null|[\d.eE+-]+/g)))return eval("("+b+")")},ready:L,setCookie:function(b,c,d,e,
f,g){n.cookie=b+"="+(g?c:escape(c))+(d?"; expires="+("object"==typeof d?d:new Date((new Date).getTime()+864E5*d)).toUTCString():"")+"; path="+(e?escapeURI(e):"/")+(f?"; domain="+escape(f):"")},getCookie:function(b,c){var d,e=(d=RegExp("(^|;)\\s*"+b+"=([^;]*)").exec(n.cookie))&&d[2];return c?e:e&&unescape(e)},loop:function(b){var c={i:b,j:(new Date).getTime(),a:function(){for(var b=0;b<E.length;b++)E[b]===c&&E.splice(b--,1)}};2>E.push(c)&&function e(){l(E,function(b){b.i(Math.max(0,(new Date).getTime()-
b.j),b.a)}).length&&Q(e)}();return c.a},off:function(b){l(b.M,function(b){b.e.addEventListener?b.e.removeEventListener(b.n,b.h,j):b.e.detachEvent("on"+b.n,b.h)});b.M=s}},function(b,c){q[b]=c});k.onload=K;n.addEventListener&&n.addEventListener("DOMContentLoaded",K,t);k.$=k.MINI=q;k.$$=q.$$;k.EE=q.el})(window,document);
