var n=!0,r=null,s=!1;
(function(j,p){function A(a){return a!=r?""+a:""}function x(a){return"string"==typeof a}function u(a){return"function"==typeof a}function v(a){return a&&a.length!=r&&!x(a)&&!(a&&a.nodeType)&&!u(a)}function k(a,b){if(v(a))for(var c=0;c<a.length;c++)b(a[c],c);else for(c in a)a.hasOwnProperty(c)&&b(c,a[c]);return a}function G(a,b){var c=[];k(a,function(a,d){(!b||b(a,d))&&c.push(a)});return c}function t(a,b,c){c=c||[];k(a,function(a,d){v(a=b(a,d))?k(a,function(a){c.push(a)}):a!=r&&c.push(a)});return c}
function m(a,b,c){return A(a).replace(b,c||"")}function B(a,b){var c=j.setTimeout(b,a||0);return function(){a&&j.clearTimeout(c)}}function w(a){return parseFloat(m(a,/^[^\d-]/))}function I(a){var b={o:"absolute",g:"hidden",d:"block",f:r},c=a.get(b);a.set(b);b=a[0].offsetHeight;a.set(c);return b}function J(a){a()}function K(){k(C,J);C=r}function L(a){C?C.push(a):B(0,a)}function H(){function a(a,d){b==r&&(b=a,c=d,B(0,function(){k(e,J)}))}var b,c=[],e=[],d=a.then=function(a,d){function h(){try{var e=
b?a:d;if(u(e)){var h=e.apply(r,c);h&&u(h.then)?h.then(function(a){l(n,[a])},function(a){l(s,[a])}):l(n,[h])}else l(b,c)}catch(k){l(s,[k])}}var l=H();b!=r?B(0,h):e.push(h);return l};a.always=function(a){return d(a,a)};a.error=function(a){return d(0,a)};return a}function M(a){return O[a]||"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}function q(a,b,c){return u(a)?L(a):new E(z(a,b,c))}function z(a,b,c){function e(a){return v(a)?t(a,e):a}function d(a){a=e(a);return!f?a:G(a,function(a){for(;a=
a.parentNode;){if(a===f)return n;if(c)return s}})}var f,g,h,l,k;if(b&&1!=(b=z(b)).length)return t(b,function(b){return z(a,b)});f=b&&b[0];if(!x(a))return d(v(a)?a:[a]);if(1<(b=a.split(/\s*,\s*/)).length)return t(b,function(a){return z(a,f)});if(b=/(\S+)\s+(.+)$/.exec(a))return z(b[2],z(b[1],f));if(a!=(b=m(a,/^#/)))return d([p.getElementById(b)]);f=f||p;g=(b=/([^.]*)\.?([^.]*)/.exec(a))[1];l=b[2];b=(h=f.getElementsByClassName&&l)?f.getElementsByClassName(l):f.getElementsByTagName(g||"*");if(g=h?g:
l)k=RegExp("\\b"+g+"\\b","i"),b=G(b,function(a){return k.test(a[h?"nodeName":"className"])});return c?d(b):b}function E(a){for(var b=0;b<a.length;b++)this[b]=a[b];this.length=a.length;this.raw=a}var C=[],D=[],P=t(["msR","webkitR","mozR","r"],function(a){return j[a+"equestAnimationFrame"]})[0]||function(a){B(33,a)},F=!!p.all&&!C.map,O={"\t":"\\t","\r":"\\r","\n":"\\n",'"':'\\"',"\\":"\\\\"};k({each:function(a){k(this.raw,a);return this},filter:function(a){return new E(G(this.raw,a))},collect:function(a,
b){return new E(t(this.raw,a,b))},sub:function(a,b){var c=this.length,e=0>a?c+a:a,d=b==r?c:0<=b?b:c+b;return this.filter(function(a,b){return b>=e&&b<d})},find:function(a){for(var b=u(a)?a:function(b,c){if(a===b)return c},c,e=0;e<this.length;e++)if((c=b(this[e],e))!=r)return c},hasClass:function(a){var b=RegExp("\\b"+a+"\\b");return this.find(function(a){return b.test(a.className)?a:r})},remove:function(){this.each(function(a){a.parentNode.removeChild(a)})},get:function(a,b){var c=this,e=c[0];if(e){if(x(a)){var d=
m(a,/^[$@]/),f,g=/^\$\$/.test(a)&&("hidden"==c.get("$visibility")||"none"==c.get("$display"));f="$"==a?e.className:"$$"==a?F?e.style.cssText:e.getAttribute("style"):"$$fade"==a?isNaN(f=g?0:F?w(c.get("$filter"))/100:w(c.get("$opacity")))?1:f:"$$slide"==a?(g?0:e.offsetHeight)+"px":/^\$/.test(a)?j.getComputedStyle?j.getComputedStyle(e,r).getPropertyValue(m(d,/[A-Z]/g,function(a){return"-"+a.toLowerCase()})):e.currentStyle[d]:/^@/.test(a)?e.getAttribute(d):e[d];return b?w(f):f}var h={};k(a,function(a){h[a]=
c.get(a)});return h}},set:function(a,b,c){var e=this,d;void 0!==b?"$$fade"==a||"$$slide"==a?e.set({g:0<(d=w(b))?"visible":"hidden",d:"block"}).set("$$fade"==a?F?{k:"alpha(opacity = "+100*d+")",p:1}:{l:d}:{f:/px$/.test(b)?b:function(a,b,c){return d*(d&&I($(c)))+"px"},m:"hidden"}):e.each(function(e,d){var h=u(b)?b:c,l=m(a,/^[@$]/),y=e.className||"",j=/^\$/.test(a)?e.style:e,h=h?h(q(e).get(a),d,e,b):b;"$"==a?(k(h.split(/\s+/),function(a){var b=m(a,/^[+-]/),c=y;y=m(y,RegExp("\\b"+b+"\\b"));if(/^\+/.test(a)||
b==a&&c==y)y+=" "+b}),e.className=m(y,/^\s+|\s+(?=\s|$)/g)):"$$"==a?F?j.cssText=h:e.setAttribute("style",h):/^@/.test(a)?h!=r&&j.setAttribute(l,h):j[l]=h}):x(a)||u(a)?e.set("$",a):k(a,function(a,b){e.set(a,b,c)});return e},append:function(a,b){return this.set(a,b,function(a,b,d,f){return A(a)+f})},prepend:function(a,b){return this.set(a,b,function(a,b,d,f){return f+A(a)})},add:function(a,b){return this.each(function(c,e){var d;(function g(a){v(a)?k(a,g):u(a)?g(a(c,e)):a!=r&&(a=a&&a.nodeType?a:p.createTextNode(a),
d?d.parentNode.insertBefore(a,d.nextSibling):b?b(a,c,c.parentNode):c.appendChild(a),d=a)})(a&&a.nodeType&&e?r:a)})},fill:function(a){return this.each(function(a){q(a.childNodes).remove()}).add(a)},addBefore:function(a){return this.add(a,function(a,c,e){e.insertBefore(a,c)})},addAfter:function(a){return this.add(a,function(a,c,e){e.insertBefore(a,c.nextSibling)})},addFront:function(a){return this.add(a,function(a,c){c.insertBefore(a,c.firstChild)})},replace:function(a){return this.add(a,function(a,
c,e){e.replaceChild(a,c)})},clone:function(){return this.collect(function(a){var b={},c,e=a&&a.nodeType;if(1==e)return k(a.attributes,function(a){c=a.name;b["style"==c?"$$":"class"==c?"$":"@"+c]=a.value}),q.el(a.tagName,b,q(a.childNodes).clone());if(2<e&&5>e)return a.textContent})},animate:function(a,b,c,e,d){var f=this,g=[],h=/-?[\d.]+/,l,j,p=H();d=d||{};d.time=0;d.stop=function(){l&&l();j&&j();p(s)};l=B(e,function(){b=b||500;c=c||0;f.each(function(b){var c={b:q(b),a:{},c:{}};k(c.a=c.b.get(a),function(b,
e){var d=a[b];"$$slide"==b&&(d=d*I(c.b)+"px");c.c[b]=/^[+-]=/.test(d)?m(d.substr(2),h,w(e)+w(m(d,/\+?=/))):d});g.push(c)});j=q.loop(function(a,e){function l(a,b){return/^#/.test(a)?parseInt(6<a.length?a.substr(1+2*b,2):(a=a.charAt(1+b))+a,16):parseInt(m(a,/[^\d,]+/g).split(",")[b])}function j(e,d){return e+a/b*(d-e)*(c+(1-c)*a/b*(3-2*a/b))}d.time=a;a>=b||0>a?(k(g,function(a){a.b.set(a.c)}),e(),d.time=d.stop=r,p(n,[f])):k(g,function(a){k(a.a,function(b,c){var e="rgb(",d=a.c[b];if(/^#|rgb\(/.test(d))for(var f=
0;3>f;f++)e+=Math.round(j(l(c,f),l(d,f)))+(2>f?",":")");else e=m(d,h,j(w(c),w(d)));a.b.set(b,e)})})})});return p},toggle:function(a,b,c,e){var d={},f=s,g=/\b(?=\w)/g,h=this;return!b?h.toggle(m(a,g,"-"),m(a,g,"+")):h.set(a)&&function(g){g!==f&&(f="boolean"==typeof g?g:!f,c?h.q(f?b:a,d.stop?d.stop()||d.time:c,e,0,d):h.set(f?b:a))}},on:function(a,b,c,e){return this.each(function(d,f){function g(a){a=a||j.event;if(!b.apply(e||a.target,c||[a,f])||c)a.stopPropagation&&(a.preventDefault(),a.stopPropagation()),
a.returnValue=s,a.cancelBubble=n}(b.M=b.M||[]).push({e:d,h:g,n:a});d.addEventListener?d.addEventListener(a,g,n):d.attachEvent("on"+a,g)})},offset:function(){for(var a=this[0],b={x:0,y:0};a;)b.x+=a.offsetLeft,b.y+=a.offsetTop,a=a.offsetParent;return b}},function(a,b){E.prototype[a]=b});k({$$:function(a){return z(a)[0]},el:function(a,b,c,e){return function(){var d=p.documentElement.namespaceURI,d=q(d?p.createElementNS(d,a):p.createElement(a));v(b)||"object"!=typeof b?d.add(b):d.set(b).add(c);e&&e(d);
return d}},request:function(a,b,c,e,d,f){var g,h=c,l=0,m=H();try{return g=j.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Msxml2.XMLHTTP.3.0"),c!=r&&(e=e||{},!x(c)&&(!c||!c.nodeType)&&(h=t(c,function N(a,b){return v(b)?t(b,function(b){return N(a,b)}):encodeURIComponent(a)+(b!=r?"="+encodeURIComponent(b):"")}).join("&")),/post/i.test(a)?(!c||!c.nodeType)&&(!x(c)&&!e["Content-Type"])&&(e["Content-Type"]="application/x-www-form-urlencoded"):(b+="?"+h,h=r)),g.open(a,b,n,d,f),k(e,function(a,b){g.setRequestHeader(a,
b)}),g.onreadystatechange=function(){4==g.readyState&&!l++&&(200==g.status?m(n,[g.responseText,g.responseXML]):m(s,[g.status,g.statusText,g.responseText]))},g.send(h),m}catch(p){l||m(s,[0,r,A(p)])}},toJSON:function b(c){return c==r?""+c:x(c=c.valueOf())?'"'+m(c,/[\\\"\x00-\x1f\x22\x5c]/g,M)+'"':v(c)?"["+t(c,b).join()+"]":"object"==typeof c?"{"+t(c,function(c,d){return b(c)+":"+b(d)}).join()+"}":A(c)},parseJSON:j.JSON?j.JSON.parse:function(b){b=m(b,/[\x00\xad\u0600-\uffff]/g,M);if(/^[[\],:{}\s]*$/.test(m(m(b,
/\\["\\\/bfnrtu]/g),/"[^"\\\n\r]*"|true|false|null|[\d.eE+-]+/g)))return eval("("+b+")")},ready:L,setCookie:function(b,c,e,d,f,g){p.cookie=b+"="+(g?c:escape(c))+(e?"; expires="+("object"==typeof e?e:new Date((new Date).getTime()+864E5*e)).toUTCString():"")+"; path="+(d?escapeURI(d):"/")+(f?"; domain="+escape(f):"")},getCookie:function(b,c){var e,d=(e=RegExp("(^|;)\\s*"+b+"=([^;]*)").exec(p.cookie))&&e[2];return c?d:d&&unescape(d)},loop:function(b){var c={i:b,j:(new Date).getTime(),a:function(){for(var b=
0;b<D.length;b++)D[b]===c&&D.splice(b--,1)}};2>D.push(c)&&function d(){k(D,function(b){b.i(Math.max(0,(new Date).getTime()-b.j),b.a)}).length&&P(d)}();return c.a},off:function(b){k(b.M,function(b){b.e.addEventListener?b.e.removeEventListener(b.n,b.h,n):b.e.detachEvent("on"+b.n,b.h)});b.M=r}},function(b,c){q[b]=c});j.onload=K;p.addEventListener&&p.addEventListener("DOMContentLoaded",K,s);j.$=j.MINI=q;j.$$=q.$$;j.EE=q.el})(this,document);
